import fs from 'node:fs';
import path from 'node:path';
import yaml from 'js-yaml';

const DESIGN_DIR = './design';
const CSS_VARS_OUTPUT = './src/styles/themes.css';
const TW_THEME_OUTPUT = './src/styles/tailwind-theme.css';
const JS_OUTPUT = './tailwind.tokens.js';

interface DesignTokens {
  name: string;
  colors?: Record<string, string>;
  spacing?: Record<string, string>;
  rounded?: Record<string, string>;
  typography?: Record<string, any>;
}

const REQUIRED_SEMANTIC_COLORS = [
  'success',
  'on-success',
  'success-container',
  'on-success-container',
  'warning',
  'on-warning',
  'warning-container',
  'on-warning-container',
  'info',
  'on-info',
  'info-container',
  'on-info-container',
] as const;

function parseDesignFile(filePath: string): DesignTokens {
  const content = fs.readFileSync(filePath, 'utf8');
  const match = content.match(/^---([\s\S]+?)---/);
  if (!match) throw new Error(`No front matter found in ${filePath}`);
  return yaml.load(match[1]) as DesignTokens;
}

function flattenTokens(obj: any, separator = '-'): Record<string, any> {
  const result: Record<string, any> = {};
  const walk = (current: any, prefix = '') => {
    for (const [key, value] of Object.entries(current)) {
      const newKey = prefix ? `${prefix}${separator}${key}` : key;
      if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
        walk(value, newKey);
      } else {
        result[newKey] = value;
      }
    }
  };
  if (obj) walk(obj);
  return result;
}

function generateCSS(themes: Record<string, DesignTokens>) {
  let css = '/* Generated by sync-design.ts - DO NOT EDIT */\n\n';

  const getVars = (tokens: any) => {
    let vars = '';
    
    const colors = flattenTokens(tokens.colors);
    for (const [key, val] of Object.entries(colors)) vars += `  --color-${key}: ${val};\n`;

    const spacing = flattenTokens(tokens.spacing);
    for (const [key, val] of Object.entries(spacing)) vars += `  --spacing-${key}: ${val};\n`;
    
    const radii = flattenTokens(tokens.radius || tokens.rounded);
    for (const [key, val] of Object.entries(radii)) {
      const k = key === 'DEFAULT' ? 'base' : key;
      vars += `  --rounded-${k}: ${val};\n`;
      vars += `  --ui-radius-${k}: ${val};\n`;
    }

    const elevation = flattenTokens(tokens.elevation);
    for (const [key, val] of Object.entries(elevation)) vars += `  --ui-elevation-${key}: ${val};\n`;

    const ui = flattenTokens(tokens.ui);
    for (const [key, val] of Object.entries(ui)) vars += `  --ui-${key}: ${val};\n`;

    const fonts = flattenTokens(tokens.fonts);
    for (const [key, val] of Object.entries(fonts)) vars += `  --font-${key}: ${val};\n`;

    const animations = flattenTokens(tokens.animations);
    for (const [key, val] of Object.entries(animations)) vars += `  --animate-${key}: ${val};\n`;

    return vars;
  };

  const defaultTheme = themes['nova'] || Object.values(themes)[0];
  css += `:root {\n${getVars(defaultTheme)}}\n\n`;

  for (const [slug, tokens] of Object.entries(themes)) {
    if (slug === 'nova') continue;
    css += `[data-theme="${slug}"] {\n${getVars(tokens)}}\n\n`;
  }

  return css;
}

function validateSemanticColors(themes: Record<string, DesignTokens>) {
  for (const [slug, tokens] of Object.entries(themes)) {
    const colors = flattenTokens(tokens.colors);
    const missing = REQUIRED_SEMANTIC_COLORS.filter((key) => !colors[key]);
    if (missing.length > 0) {
      throw new Error(`Theme "${slug}" is missing semantic colors: ${missing.join(', ')}`);
    }
  }
}

function generateTailwindTheme(baseTokens: any) {
  let tw = '/* Generated by sync-design.ts - DO NOT EDIT */\n\n@theme {\n';

  const colors = flattenTokens(baseTokens.colors);
  for (const key of Object.keys(colors)) tw += `  --color-${key}: var(--color-${key});\n`;

  const spacing = flattenTokens(baseTokens.spacing);
  for (const key of Object.keys(spacing)) tw += `  --spacing-${key}: var(--spacing-${key});\n`;
  
  const radii = flattenTokens(baseTokens.radius || baseTokens.rounded);
  for (const key of Object.keys(radii)) {
    const k = key === 'DEFAULT' ? 'base' : key;
    tw += `  --radius-${k}: var(--rounded-${k});\n`;
  }

  const elevation = flattenTokens(baseTokens.elevation);
  for (const key of Object.keys(elevation)) tw += `  --shadow-${key}: var(--ui-elevation-${key});\n`;

  const fonts = flattenTokens(baseTokens.fonts);
  for (const key of Object.keys(fonts)) tw += `  --font-${key}: var(--font-${key});\n`;

  const animations = flattenTokens(baseTokens.animations);
  for (const key of Object.keys(animations)) tw += `  --animate-${key}: var(--animate-${key});\n`;

  tw += `  --max-width-xs: 20rem;\n`;
  tw += `  --max-width-sm: 24rem;\n`;
  tw += `  --max-width-md: 28rem;\n`;
  tw += `  --max-width-lg: 32rem;\n`;
  tw += `  --max-width-xl: 36rem;\n`;
  tw += `  --max-width-2xl: 42rem;\n`;
  tw += `  --max-width-3xl: 48rem;\n`;
  tw += `  --max-width-4xl: 56rem;\n`;
  tw += `  --max-width-5xl: 64rem;\n`;
  tw += `  --max-width-full: 100%;\n`;

  tw += '}\n';
  return tw;
}

function generateJS(baseTokens: any) {
  const js: any = {
    colors: {},
    spacing: {},
    borderRadius: {},
    elevation: {},
    ui: {}
  };

  const colors = flattenTokens(baseTokens.colors);
  for (const key of Object.keys(colors)) js.colors[key] = `var(--color-${key})`;

  const spacing = flattenTokens(baseTokens.spacing);
  for (const key of Object.keys(spacing)) js.spacing[key] = `var(--spacing-${key})`;
  
  const radii = flattenTokens(baseTokens.radius || baseTokens.rounded);
  for (const key of Object.keys(radii)) {
    const k = key === 'DEFAULT' ? 'base' : key;
    js.borderRadius[k] = `var(--rounded-${k})`;
  }

  const elevation = flattenTokens(baseTokens.elevation);
  for (const key of Object.keys(elevation)) js.elevation[key] = `var(--ui-elevation-${key})`;

  const ui = flattenTokens(baseTokens.ui);
  for (const key of Object.keys(ui)) js.ui[key] = `var(--ui-${key})`;

  return `/* Generated by sync-design.ts - DO NOT EDIT */\n\nexport const tokens = ${JSON.stringify(js, null, 2)};\n`;
}

async function sync() {
  const files = fs.readdirSync(DESIGN_DIR)
    .filter(f => f.endsWith('.md'))
    .filter(f => fs.readFileSync(path.join(DESIGN_DIR, f), 'utf8').startsWith('---'));
  const themes: Record<string, DesignTokens> = {};

  for (const file of files) {
    const slug = path.basename(file, '.md');
    themes[slug] = parseDesignFile(path.join(DESIGN_DIR, file));
  }

  if (Object.keys(themes).length === 0) {
    throw new Error('No design profile found in design/.');
  }

  const defaultTheme = themes['nova'] || Object.values(themes)[0];

  validateSemanticColors(themes);

  const cssVars = generateCSS(themes);
  const twTheme = generateTailwindTheme(defaultTheme);
  const js = generateJS(defaultTheme);

  const outputs = [
    { path: CSS_VARS_OUTPUT, content: cssVars },
    { path: TW_THEME_OUTPUT, content: twTheme },
    { path: JS_OUTPUT, content: js }
  ];

  for (const { path: outPath, content } of outputs) {
    if (!fs.existsSync(path.dirname(outPath))) {
      fs.mkdirSync(path.dirname(outPath), { recursive: true });
    }
    fs.writeFileSync(outPath, content);
  }

  console.log(`✅ Synced ${Object.keys(themes).length} themes.`);
  console.log(`📄 Generated: ${outputs.map(o => o.path).join(', ')}`);
}

sync().catch(console.error);
