import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';

// Why: The contract test reflects the HTML structure generated by
// AboutMarqueeSplitBlock to detect regressions in bare-metal rendering
// full build. Pattern: hero-contract.test.ts.

interface AboutMarqueeData {
  sectionId?: string;
  heading?: string;
  lead?: string;
  paragraphs?: string[];
  clientsHeadline?: string;
  clients?: string[];
  labels?: string[];
  moreClients?: string[];
}

const DEFAULT_CLIENTS = ['Budownictwo', 'Architektura', 'Energetyka', 'IT'];
const DEFAULT_LABELS = ['Wycena', 'Projekt', 'Realizacja'];
const DEFAULT_MORE = ['Stal', 'Beton', 'Drewno', 'Szkło'];

// Why: track is a span list; a second copy (aria-hidden) is needed
// for a seamless marquee animation loop.
function trackHtml(items: string[], direction: string, hidden: boolean): string {
  return `
    <div class="ui-marquee-track ${direction}${hidden ? '' : ''}"${hidden ? ' aria-hidden="true"' : ''}>
      ${items.map((item) => `<span class="text-sm font-bold tracking-widest text-neutral-800 whitespace-nowrap uppercase">${item}</span>`).join('')}
    </div>`;
}

function renderAboutMarqueeHtml(data: AboutMarqueeData): string {
  const {
    sectionId = 'o-nas',
    heading = 'O nas',
    lead = '',
    paragraphs = [],
    clientsHeadline = 'Klienci',
    clients = DEFAULT_CLIENTS,
    labels = DEFAULT_LABELS,
    moreClients = DEFAULT_MORE,
  } = data;

  const leadHtml = lead ? `<p class="leading-relaxed ui-type-lead mt-6 text-neutral-800">${lead}</p>` : '';

  const paragraphsHtml = paragraphs
    .map((paragraph) => `<p class="leading-relaxed text-sm text-neutral-500">${paragraph}</p>`)
    .join('');

  // Why: 3 marquee lanes (ltr customers, rtl labels, more ltr customers),
  // each with its own speed given by inline variables.
  const marqueeHtml = `
    <div class="mt-10 space-y-6">
      <div class="ui-marquee-row" style="--ui-marquee-desktop-duration: 36s; --ui-marquee-mobile-duration: 28s;">
        ${trackHtml(clients, 'ui-marquee-ltr', false)}
        ${trackHtml(clients, 'ui-marquee-ltr', true)}
      </div>
      <div class="ui-marquee-row" style="--ui-marquee-desktop-duration: 32s; --ui-marquee-mobile-duration: 24s;">
        ${trackHtml(labels, 'ui-marquee-rtl', false)}
        ${trackHtml(labels, 'ui-marquee-rtl', true)}
      </div>
      <div class="ui-marquee-row" style="--ui-marquee-desktop-duration: 45s; --ui-marquee-mobile-duration: 30s;">
        ${trackHtml(moreClients, 'ui-marquee-ltr', false)}
        ${trackHtml(moreClients, 'ui-marquee-ltr', true)}
      </div>
    </div>`;

  return `<section id="${sectionId}" class="ui-section ui-bg-base relative overflow-hidden">
    <div class="ui-container">
      <div class="grid gap-8 lg:grid-cols-2 lg:gap-12 items-center">
        <div class="overflow-hidden rounded shadow-xl aspect-[4/5] max-w-md mx-auto lg:mr-0 lg:ml-auto">
          <img src="/assets/images/about-profile.webp" alt="Zdjęcie zespołu" class="w-full h-full object-cover grayscale" />
        </div>
        <div class="max-w-lg text-center lg:text-left">
          <h2 class="font-heading font-bold text-3xl font-light tracking-[0.08em] text-neutral-900 sm:text-4xl">${heading}</h2>
          ${leadHtml}
          <div class="mt-6 space-y-3">${paragraphsHtml}</div>
        </div>
      </div>
      <div class="ui-divider mt-16 mb-8">
        <h3 class="text-xl sm:text-2xl font-light tracking-[0.08em] text-neutral-900 text-center shrink-0">${clientsHeadline}</h3>
      </div>
      ${marqueeHtml}
    </div>
  </section>`;
}

describe('AboutMarqueeSplit, kontrakt renderowania', () => {
  const defaultData: AboutMarqueeData = {
    heading: 'O nas',
    lead: 'Poznaj naszą filozofię pracy.',
    paragraphs: ['Pierwszy akapit o firmie.', 'Drugi akapit o podejściu.'],
    clientsHeadline: 'Klienci',
    clients: DEFAULT_CLIENTS,
    labels: DEFAULT_LABELS,
    moreClients: DEFAULT_MORE,
  };

  it('renderuje <section> z ui-section i id', () => {
    const $ = cheerio.load(renderAboutMarqueeHtml(defaultData));
    expect($('section').length).toBe(1);
    expect($('section').hasClass('ui-section')).toBe(true);
    expect($('section').attr('id')).toBe('o-nas');
  });

  it('zawiera .ui-container', () => {
    const $ = cheerio.load(renderAboutMarqueeHtml(defaultData));
    expect($('.ui-container').length).toBe(1);
  });

  it('renderuje h2 z headingiem', () => {
    const $ = cheerio.load(renderAboutMarqueeHtml(defaultData));
    expect($('h2').length).toBe(1);
    expect($('h2').text()).toContain('O nas');
  });

  it('renderuje lead jako .ui-type-lead gdy podany', () => {
    const $ = cheerio.load(renderAboutMarqueeHtml(defaultData));
    expect($('.ui-type-lead').length).toBe(1);
    expect($('.ui-type-lead').text()).toContain('Poznaj naszą filozofię');
  });

  it('renderuje akapity', () => {
    const $ = cheerio.load(renderAboutMarqueeHtml(defaultData));
    expect($('p').text()).toContain('Pierwszy akapit o firmie.');
    expect($('p').text()).toContain('Drugi akapit o podejściu.');
  });

  it('nagłówek klientów używa .ui-divider', () => {
    const $ = cheerio.load(renderAboutMarqueeHtml(defaultData));
    expect($('.ui-divider').length).toBe(1);
    expect($('.ui-divider h3').text()).toBe('Klienci');
  });

  it('zdjęcie ma aspect-[4/5] i grayscale', () => {
    const $ = cheerio.load(renderAboutMarqueeHtml(defaultData));
    expect($('.aspect-\\[4\\/5\\]').length).toBe(1);
    expect($('img').hasClass('grayscale')).toBe(true);
  });

  describe('marquee tory', () => {
    it('ma dokładnie 3 wiersze .ui-marquee-row', () => {
      const $ = cheerio.load(renderAboutMarqueeHtml(defaultData));
      expect($('.ui-marquee-row').length).toBe(3);
    });

    it('ma dokładnie 6 tracków (3 pary)', () => {
      const $ = cheerio.load(renderAboutMarqueeHtml(defaultData));
      expect($('.ui-marquee-track').length).toBe(6);
    });

    it('każda para ma drugi track z aria-hidden="true"', () => {
      const $ = cheerio.load(renderAboutMarqueeHtml(defaultData));
      expect($('.ui-marquee-track[aria-hidden="true"]').length).toBe(3);
      expect($('.ui-marquee-track:not([aria-hidden])').length).toBe(3);
    });

    it('tracki mają kierunek ui-marquee-ltr lub ui-marquee-rtl', () => {
      const $ = cheerio.load(renderAboutMarqueeHtml(defaultData));
      expect($('.ui-marquee-ltr').length).toBe(4);
      expect($('.ui-marquee-rtl').length).toBe(2);
    });

    it('wiersze marquee mają zmienne czasu inline', () => {
      const $ = cheerio.load(renderAboutMarqueeHtml(defaultData));
      $('.ui-marquee-row').each((_, el) => {
        const style = $(el).attr('style') || '';
        expect(style).toContain('--ui-marquee-desktop-duration');
        expect(style).toContain('--ui-marquee-mobile-duration');
      });
    });

    it('klienci renderują się jako span uppercase', () => {
      const $ = cheerio.load(renderAboutMarqueeHtml(defaultData));
      const firstTrack = $('.ui-marquee-track').first();
      expect(firstTrack.find('span').length).toBe(DEFAULT_CLIENTS.length);
      expect(firstTrack.find('span').first().hasClass('uppercase')).toBe(true);
    });
  });

  it('nie zawiera href="#"', () => {
    const html = renderAboutMarqueeHtml(defaultData);
    expect(html).not.toContain('href="#"');
  });
});
