import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';

// Why: The contract test reproduces the HTML structure generated by
// AboutSplitBlock to detect regressions in bare-metal rendering
// full build. Pattern: services-studio-contract.test.ts.

type ImageShape = 'rounded' | 'mosaic' | 'split' | 'arch' | 'collage';

interface AboutSplitData {
  sectionId?: string;
  title?: string;
  description?: string;
  quote?: string;
  signature?: string;
  role?: string;
  image?: string;
  images?: string[];
  imageShape?: ImageShape;
}

const DEFAULT_DATA: AboutSplitData = {
  sectionId: 'about-split',
  title: 'O naszej firmie',
  description: 'Akapit pierwszy.\n\nAkapit drugi.',
  quote: 'Cytat o firmie',
  signature: 'Twoja Firma',
  role: 'Kompleksowe wykończenia wnętrz',
  image: '/assets/placeholders/image-landscape.svg',
  images: [
    '/assets/placeholders/image-square.svg',
    '/assets/placeholders/image-square.svg',
    '/assets/placeholders/image-square.svg',
    '/assets/placeholders/image-square.svg',
  ],
};

function renderAboutSplitHtml(data: AboutSplitData): string {
  const {
    sectionId = 'about-split',
    title = 'O naszej firmie',
    description = '',
    quote = '',
    signature = 'Twoja Firma',
    role = 'Kompleksowe wykończenia wnętrz',
    image = '/assets/placeholders/image-landscape.svg',
    images = DEFAULT_DATA.images ?? [],
    imageShape = 'rounded',
  } = data;

  // Why: we repeat the component logic because the contract test must pass
  // exactly the same elements that Astro generates (paragraphs with \n\n, shapes).
  const paragraphs = description.split('\n\n').map((paragraph) => paragraph).join('');
  const mosaicSources = [0, 1, 2, 3].map((i) => images[i % images.length]);

  const renderImage = (shape: ImageShape): string => {
    if (shape === 'mosaic') {
      return `
        <div class="grid grid-cols-2 gap-3 sm:gap-4">
          ${mosaicSources.map((src, i) => `
            <div class="aspect-square overflow-hidden rounded-xl sm:rounded-2xl shadow-sm ${i % 2 === 1 ? 'md:translate-y-8' : ''}">
              <img src="${src}" class="block w-full h-full object-cover" alt="Realizacja wnętrza" width="400" height="400" />
            </div>`).join('')}
        </div>`;
    }
    if (shape === 'split') {
      return `
        <div class="flex items-center gap-3 sm:gap-4">
          <div class="w-1/2 aspect-[4/5] overflow-hidden rounded-2xl shadow-sm">
            <img src="${image}" class="block w-full h-full object-cover object-left" alt="Realizacja wnętrza" width="400" height="500" />
          </div>
          <div class="w-1/2 aspect-[4/5] overflow-hidden rounded-2xl shadow-sm md:translate-y-12">
            <img src="${image}" class="block w-full h-full object-cover object-right" alt="Realizacja wnętrza" width="400" height="500" />
          </div>
        </div>`;
    }
    if (shape === 'arch') {
      return `
        <div class="overflow-hidden rounded-t-[45%] rounded-b-2xl h-full min-h-[360px]">
          <img src="${image}" class="block w-full h-full object-cover object-center" alt="Realizacja wnętrza" width="800" height="600" />
        </div>`;
    }
    if (shape === 'collage') {
      return `
        <div class="relative">
          <div class="overflow-hidden rounded-2xl h-full min-h-[360px]">
            <img src="${image}" class="block w-full h-full object-cover object-center" alt="Realizacja wnętrza" width="800" height="600" />
          </div>
          <div class="absolute -bottom-6 -right-3 w-2/5 aspect-square overflow-hidden rounded-2xl border-4 border-brand-light shadow-xl">
            <img src="${image}" class="block w-full h-full object-cover object-center scale-125" alt="Realizacja wnętrza (detale)" width="300" height="300" />
          </div>
        </div>`;
    }
    // Why: rounded is the default shape, hence fallback without a condition.
    return `
      <div class="overflow-hidden rounded-2xl h-full">
        <img src="${image}" class="block w-full h-full object-cover object-center" alt="Realizacja wnętrza" width="800" height="600" />
      </div>`;
  };

  return `<section id="${sectionId}" class="ui-section ui-bg-page">
    <div class="ui-container">
      <div class="grid grid-cols-1 gap-12 lg:grid-cols-2 lg:gap-16 xl:gap-24">
        <div class="flex flex-col justify-center">
          <h2 class="font-heading font-bold ui-type-heading-section-lg text-brand-dark mb-8">${title}</h2>
          <p class="leading-relaxed ui-type-lead text-brand-dark/80 mb-6">${paragraphs}</p>
          <div class="border-t border-brand-dark/10 pt-8">
            <div class="space-y-3">
              <p class="font-heading text-base italic leading-relaxed whitespace-pre-line text-brand-dark/55 md:text-lg">&bdquo;${quote}&rdquo;</p>
              <h3 class="about-signature" aria-label="Podpis: ${signature}">${signature}</h3>
              <div>
                <p class="leading-relaxed ui-type-text-feature-sm mt-1 uppercase tracking-[0.2em] text-brand-dark/65">${role}</p>
              </div>
            </div>
          </div>
        </div>
        <div class="relative flex flex-col justify-center">
          ${renderImage(imageShape)}
        </div>
      </div>
    </div>
  </section>`;
}

describe('AboutSplitBlock, kontrakt renderowania', () => {
  it('renderuje <section> z ui-section, id i tonem page', () => {
    const $ = cheerio.load(renderAboutSplitHtml(DEFAULT_DATA));
    expect($('section').length).toBe(1);
    expect($('section').hasClass('ui-section')).toBe(true);
    expect($('section').hasClass('ui-bg-page')).toBe(true);
    expect($('section').attr('id')).toBe('about-split');
  });

  it('zawiera .ui-container', () => {
    const $ = cheerio.load(renderAboutSplitHtml(DEFAULT_DATA));
    expect($('.ui-container').length).toBe(1);
  });

  describe('grid', () => {
    it('grid jest 2 kolumnowy na lg (mobile-first)', () => {
      const $ = cheerio.load(renderAboutSplitHtml(DEFAULT_DATA));
      const grid = $('.grid').first();
      expect(grid.hasClass('grid-cols-1')).toBe(true);
      expect(grid.hasClass('lg:grid-cols-2')).toBe(true);
    });

    it('ma dokładnie 2 kolumny: tekst i obraz', () => {
      const $ = cheerio.load(renderAboutSplitHtml(DEFAULT_DATA));
      const columns = $('.grid').first().children('div');
      expect(columns.length).toBe(2);
      expect(columns.first().hasClass('flex-col')).toBe(true);
      expect(columns.last().hasClass('relative')).toBe(true);
    });
  });

  describe('kolumna tekstu', () => {
    it('renderuje h2 z tytułem', () => {
      const $ = cheerio.load(renderAboutSplitHtml(DEFAULT_DATA));
      expect($('h2').length).toBe(1);
      expect($('h2').text()).toContain('O naszej firmie');
    });

    it('dzieli opis na akapity po \\n\\n', () => {
      const $ = cheerio.load(renderAboutSplitHtml(DEFAULT_DATA));
      expect($('p.ui-type-lead').length).toBeGreaterThan(0);
      expect($('p.ui-type-lead').text()).toContain('Akapit pierwszy.');
      expect($('p.ui-type-lead').text()).toContain('Akapit drugi.');
    });
  });

  describe('blok cytatu', () => {
    it('renderuje quote w cudzysłowie', () => {
      const $ = cheerio.load(renderAboutSplitHtml(DEFAULT_DATA));
      expect($('p.italic').text()).toContain('Cytat o firmie');
    });

    it('renderuje signature jako h3 z klasą about-signature i aria-label', () => {
      const $ = cheerio.load(renderAboutSplitHtml(DEFAULT_DATA));
      expect($('h3.about-signature').length).toBe(1);
      expect($('h3.about-signature').text()).toBe('Twoja Firma');
      expect($('h3.about-signature').attr('aria-label')).toBe('Podpis: Twoja Firma');
    });

    it('renderuje role jako uppercase z trackingiem', () => {
      const $ = cheerio.load(renderAboutSplitHtml(DEFAULT_DATA));
      const role = $('p.ui-type-text-feature-sm');
      expect(role.length).toBe(1);
      expect(role.hasClass('uppercase')).toBe(true);
      expect(role.hasClass('tracking-[0.2em]')).toBe(true);
    });

    it('blok cytatu ma border-t z tokenem brand-dark/10', () => {
      const $ = cheerio.load(renderAboutSplitHtml(DEFAULT_DATA));
      const block = $('.border-t');
      expect(block.length).toBe(1);
      expect(block.hasClass('border-brand-dark/10')).toBe(true);
    });
  });

  describe('kształty obrazu', () => {
    it('domyślny shape to rounded (rounded-2xl + img)', () => {
      const $ = cheerio.load(renderAboutSplitHtml(DEFAULT_DATA));
      const frame = $('.overflow-hidden.rounded-2xl');
      expect(frame.length).toBe(1);
      expect(frame.find('img').attr('src')).toBe('/assets/placeholders/image-landscape.svg');
    });

    it('variant mosaic renderuje siatkę 2x2 z 4 obrazami', () => {
      const $ = cheerio.load(renderAboutSplitHtml({ ...DEFAULT_DATA, imageShape: 'mosaic' }));
      expect($('.grid-cols-2').length).toBe(1);
      expect($('.aspect-square').length).toBe(4);
      expect($('.aspect-square img').length).toBe(4);
    });

    it('variant mosaic przesuwa parzyste kafelki (md:translate-y-8)', () => {
      const $ = cheerio.load(renderAboutSplitHtml({ ...DEFAULT_DATA, imageShape: 'mosaic' }));
      const tiles = $('.aspect-square').toArray();
      expect($(tiles[1]).hasClass('md:translate-y-8')).toBe(true);
      expect($(tiles[0]).hasClass('md:translate-y-8')).toBe(false);
    });

    it('variant split renderuje dwa pionowe kadry 4/5', () => {
      const $ = cheerio.load(renderAboutSplitHtml({ ...DEFAULT_DATA, imageShape: 'split' }));
      expect($('.aspect-\\[4\\/5\\]').length).toBe(2);
    });

    it('variant arch renderuje łuk (rounded-t-[45%])', () => {
      const $ = cheerio.load(renderAboutSplitHtml({ ...DEFAULT_DATA, imageShape: 'arch' }));
      expect($('.rounded-t-\\[45\\%\\]').length).toBe(1);
    });

    it('variant collage renderuje 2 obrazy (główny + detal)', () => {
      const $ = cheerio.load(renderAboutSplitHtml({ ...DEFAULT_DATA, imageShape: 'collage' }));
      expect($('img').length).toBe(2);
      expect($('img').last().attr('alt')).toContain('detale');
    });
  });

  it('nie zawiera href="#"', () => {
    const html = renderAboutSplitHtml(DEFAULT_DATA);
    expect(html).not.toContain('href="#"');
  });
});
