import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';

// Why: The contract test reflects the HTML structure generated by
// FaqAccordionBlock, wariant
// "simple": accordion <details> with first open question) to detect
// regressions in rendering without running the full build. Pattern:
// services-studio-contract.test.ts.

interface FaqItem {
  q: string;
  a: string;
}

interface FaqAccordionData {
  sectionId?: string;
  lang?: 'pl' | 'en';
  title?: string;
  description?: string;
  tagline?: string;
  items?: FaqItem[];
}

const DEFAULT_ITEMS: FaqItem[] = [
  { q: 'Czy muszę mieć gotowy projekt od architekta?', a: 'Nie jest to warunek konieczny.' },
  { q: 'Jak kontroluję postęp prac?', a: 'Cotygodniowe raporty zdjęciowe.' },
  { q: 'Kto dostarcza materiały?', a: 'Przejmujemy pełną logistykę.' },
];

function renderFaqAccordionHtml(data: FaqAccordionData): string {
  const {
    sectionId = 'faq',
    lang = 'pl',
    title = 'Najczęściej Zadawane Pytania',
    description = 'Dowiedz się, jak dbamy o Twój komfort.',
    tagline = 'FAQ',
    items = DEFAULT_ITEMS,
  } = data;

  const itemsHtml = items
    .map(
      (item, idx) => `
      <details class="group ui-bg-surface ui-radius-lg overflow-hidden border border-brand-dark/5" ${idx === 0 ? 'open' : ''}>
        <summary class="flex w-full cursor-pointer list-none select-none items-center justify-between p-4 text-left">
          <h3 class="pr-8 !text-[16px] leading-snug font-medium text-brand-dark/80">${item.q}</h3>
          <div class="text-brand-primary transition-transform duration-300 group-open:-rotate-45">
            <svg xmlns="http://www.w3.org/2000/svg" class="size-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M12 4v16m8-8H4" />
            </svg>
          </div>
        </summary>
        <div class="faq-answer px-4 pb-4">
          <p class="leading-relaxed ui-type-text-feature-sm ui-text-on-light-subtle">${item.a}</p>
        </div>
      </details>`,
    )
    .join('');

  return `<section id="${sectionId}" class="ui-section ui-bg-page">
    <div class="ui-container">
      <div class="flex flex-col gap-6 text-center items-center mx-auto max-w-3xl mb-12 md:mb-16">
        <p class="leading-relaxed ui-type-accent-label text-brand-primary">${tagline}</p>
        <h2 class="font-heading font-bold text-brand-dark">${title}</h2>
        <p class="leading-relaxed max-w-2xl mx-auto text-brand-dark/70">${description}</p>
      </div>
      <div class="mx-auto mt-12 w-full max-w-2xl space-y-2">
        ${itemsHtml}
      </div>
    </div>
  </section>`;
}

describe('FaqAccordion, kontrakt renderowania', () => {
  const defaultData: FaqAccordionData = {
    title: 'Najczęściej Zadawane Pytania',
    description: 'Dowiedz się, jak dbamy o Twój komfort.',
    tagline: 'FAQ',
    items: DEFAULT_ITEMS,
  };

  it('renderuje <section> z ui-section, ui-bg-page i id', () => {
    const $ = cheerio.load(renderFaqAccordionHtml(defaultData));
    expect($('section').length).toBe(1);
    expect($('section').hasClass('ui-section')).toBe(true);
    expect($('section').hasClass('ui-bg-page')).toBe(true);
    expect($('section').attr('id')).toBe('faq');
  });

  it('renderuje nagłówek sekcji z tagline, tytułem i opisem', () => {
    const $ = cheerio.load(renderFaqAccordionHtml(defaultData));
    expect($('h2').text()).toBe('Najczęściej Zadawane Pytania');
    expect($('.ui-type-accent-label').text()).toBe('FAQ');
    expect($('p').text()).toContain('Dowiedz się, jak dbamy');
  });

  it('renderuje dokładnie 3 pytania jako <details>', () => {
    const $ = cheerio.load(renderFaqAccordionHtml(defaultData));
    expect($('details').length).toBe(3);
  });

  it('pierwsze pytanie jest domyślnie otwarte (open), pozostałe nie', () => {
    const $ = cheerio.load(renderFaqAccordionHtml(defaultData));
    expect($('details').eq(0).attr('open')).toBeDefined();
    expect($('details').eq(1).attr('open')).toBeUndefined();
    expect($('details').eq(2).attr('open')).toBeUndefined();
  });

  it('każde pytanie ma summary z h3 i ikoną plusa (SVG)', () => {
    const $ = cheerio.load(renderFaqAccordionHtml(defaultData));
    $('details').each((_, el) => {
      const summary = $(el).find('summary');
      expect(summary.length).toBe(1);
      expect(summary.find('h3').length).toBe(1);
      expect(summary.find('svg').length).toBe(1);
      expect(summary.find('svg').find('path').attr('d')).toContain('M12 4v16m8-8H4');
    });
  });

  it('pytanie h3 ma styl !text-[16px] z brand-dark/80 (wzorzec klienta)', () => {
    const $ = cheerio.load(renderFaqAccordionHtml(defaultData));
    const h3 = $('h3').first();
    expect(h3.hasClass('!text-[16px]')).toBe(true);
    expect(h3.hasClass('font-medium')).toBe(true);
    expect(h3.hasClass('text-brand-dark/80')).toBe(true);
  });

  it('odpowiedź renderuje się w .faq-answer z ui-text-on-light-subtle', () => {
    const $ = cheerio.load(renderFaqAccordionHtml(defaultData));
    const answer = $('.faq-answer').first();
    expect(answer.length).toBe(1);
    expect(answer.find('.ui-type-text-feature-sm').length).toBe(1);
    expect(answer.find('.ui-text-on-light-subtle').length).toBe(1);
    expect(answer.text()).toContain('Nie jest to warunek konieczny.');
  });

  it('accordion jest ograniczony do max-w-2xl (wzorzec klienta)', () => {
    const $ = cheerio.load(renderFaqAccordionHtml(defaultData));
    const wrap = $('.space-y-2');
    expect(wrap.length).toBe(1);
    expect(wrap.hasClass('max-w-2xl')).toBe(true);
    expect(wrap.hasClass('mx-auto')).toBe(true);
    expect(wrap.hasClass('mt-12')).toBe(true);
    expect(wrap.hasClass('w-full')).toBe(true);
  });

  it('nie zawiera klienckich klas reveal ani tokenów klienta', () => {
    const html = renderFaqAccordionHtml(defaultData);
    expect(html).not.toContain('reveal-group');
    expect(html).not.toContain('faq-accordion');
    expect(html).not.toContain('color-text-primary');
    expect(html).not.toContain('color-accent-primary');
  });

  it('nie zawiera href="#"', () => {
    const html = renderFaqAccordionHtml(defaultData);
    expect(html).not.toContain('href="#"');
  });
});
