import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';

// Why: The contract test reflects the HTML structure generated by
// FeaturesGridBlock to detect regressions in bare-metal rendering
// full build. Pattern: services-studio-contract.test.ts.

interface FeatureItem {
  icon: string;
  title: string;
  description: string;
}

interface FeaturesGridData {
  sectionId?: string;
  title?: string;
  description?: string;
  items?: FeatureItem[];
}

const DEFAULT_ITEMS: FeatureItem[] = [
  { icon: 'scroll', title: 'Przejrzyste umowy', description: 'Zero ukrytych kosztów.' },
  { icon: 'image', title: 'Raporty z postępu', description: 'Regularne zdjęcia z budowy.' },
  { icon: 'calculator', title: 'Płatności etapami', description: 'Płacisz za wykonane prace.' },
  { icon: 'clock', title: 'Termin w umowie', description: 'Szanujemy Twój czas.' },
  { icon: 'users', title: 'Stały opiekun projektu', description: 'Jedna osoba prowadzi projekt.' },
  { icon: 'briefcase', title: 'Finansowanie', description: 'Rozłożenie inwestycji w czasie.' },
];

function renderFeaturesGridHtml(data: FeaturesGridData): string {
  const {
    sectionId = 'features-grid',
    title = 'Dlaczego my?',
    description = 'Sześć korzyści, które wyróżniają nas na tle innych.',
    items = DEFAULT_ITEMS,
  } = data;

  const cardsHtml = items
    .map((item) => `
      <div class="group relative overflow-hidden border-brand-dark/10 transition-all duration-500 hover:-translate-y-1">
        <div class="absolute -right-8 -top-8 size-24 rounded-full bg-brand-primary/10 border border-brand-primary/15 transition-all duration-500 group-hover:scale-150 group-hover:bg-brand-primary/15 group-hover:border-brand-primary/25" aria-hidden="true"></div>
        <div class="relative flex h-full flex-col p-6 sm:p-8">
          <div class="mb-5 inline-flex size-12 items-center justify-center rounded-xl border border-brand-primary/15 bg-brand-primary/5 text-brand-primary transition-all duration-500 group-hover:bg-brand-primary group-hover:text-white">
            <i class="ph ph-${item.icon}" style="font-size: 24px"></i>
          </div>
          <h3 class="font-heading font-bold mb-3 text-brand-dark text-[clamp(1rem,1.6vw,1.125rem)]">${item.title}</h3>
          <p class="text-brand-dark/65 leading-relaxed">${item.description}</p>
        </div>
      </div>`)
    .join('');

  return `<section id="${sectionId}" class="ui-section ui-bg-base">
    <div class="ui-container">
      <div class="flex flex-col gap-6 text-center items-center mx-auto max-w-2xl mb-12 md:mb-16">
        <h2 class="font-heading font-bold text-brand-dark">${title}</h2>
        <p class="max-w-2xl font-normal mx-auto">${description}</p>
      </div>
      <div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
        ${cardsHtml}
      </div>
    </div>
  </section>`;
}

describe('FeaturesGrid, kontrakt renderowania', () => {
  const defaultData: FeaturesGridData = {
    title: 'Dlaczego my?',
    items: DEFAULT_ITEMS,
  };

  it('renderuje <section> z ui-section i id', () => {
    const $ = cheerio.load(renderFeaturesGridHtml(defaultData));
    expect($('section').length).toBe(1);
    expect($('section').hasClass('ui-section')).toBe(true);
    expect($('section').attr('id')).toBe('features-grid');
  });

  it('zawiera .ui-container', () => {
    const $ = cheerio.load(renderFeaturesGridHtml(defaultData));
    expect($('.ui-container').length).toBe(1);
  });

  describe('SectionHeader', () => {
    it('renderuje wycentrowany nagłówek z tytułem i opisem', () => {
      const $ = cheerio.load(renderFeaturesGridHtml(defaultData));
      const header = $('.ui-container').children().first();
      expect(header.hasClass('text-center')).toBe(true);
      expect(header.hasClass('items-center')).toBe(true);
      expect(header.hasClass('mx-auto')).toBe(true);
      expect(header.hasClass('max-w-2xl')).toBe(true);
      expect($('h2').length).toBe(1);
      expect($('h2').text()).toContain('Dlaczego my?');
      expect($('p').first().text()).toContain('Sześć korzyści');
    });
  });

  describe('grid', () => {
    it('grid jest mobile-first (grid-cols-1 sm:grid-cols-2 lg:grid-cols-3) z gap-6', () => {
      const $ = cheerio.load(renderFeaturesGridHtml(defaultData));
      const grid = $('.grid');
      expect(grid.hasClass('grid-cols-1')).toBe(true);
      expect(grid.hasClass('sm:grid-cols-2')).toBe(true);
      expect(grid.hasClass('lg:grid-cols-3')).toBe(true);
      expect(grid.hasClass('gap-6')).toBe(true);
    });

    it('renderuje dokładnie 6 kart', () => {
      const $ = cheerio.load(renderFeaturesGridHtml(defaultData));
      expect($('div.group.relative').length).toBe(6);
    });

    it('każda karta ma hover:-translate-y-1', () => {
      const $ = cheerio.load(renderFeaturesGridHtml(defaultData));
      $('div.group.relative').each((_, el) => {
        expect($(el).hasClass('hover:-translate-y-1')).toBe(true);
      });
    });
  });

  describe('kółko dekoracyjne', () => {
    it('każda karta ma kółko w rogu (absolute -right-8 -top-8 size-24)', () => {
      const $ = cheerio.load(renderFeaturesGridHtml(defaultData));
      const circles = $('div.absolute.-right-8.-top-8');
      expect(circles.length).toBe(6);
    });

    it('kółko używa tokenów brand (bg-brand-primary/10, border-brand-primary/15)', () => {
      const $ = cheerio.load(renderFeaturesGridHtml(defaultData));
      const circle = $('div.absolute.-right-8.-top-8').first();
      expect(circle.hasClass('bg-brand-primary/10')).toBe(true);
      expect(circle.hasClass('border-brand-primary/15')).toBe(true);
    });

    it('kółko jest ozdobą (aria-hidden) i rośnie na hover karty', () => {
      const $ = cheerio.load(renderFeaturesGridHtml(defaultData));
      const circle = $('div.absolute.-right-8.-top-8').first();
      expect(circle.attr('aria-hidden')).toBe('true');
      expect(circle.hasClass('group-hover:scale-150')).toBe(true);
    });
  });

  describe('ikony', () => {
    it('renderuje ikonę w każdej karcie z klasą ph-', () => {
      const $ = cheerio.load(renderFeaturesGridHtml(defaultData));
      expect($('i.ph').length).toBe(6);
      $('i.ph').each((_, el) => {
        expect($(el).attr('class')).toContain('ph-');
      });
    });

    it('ikony mają nazwy z danych (scroll, image, calculator, clock, users, briefcase)', () => {
      const $ = cheerio.load(renderFeaturesGridHtml(defaultData));
      expect($('i.ph-scroll').length).toBe(1);
      expect($('i.ph-image').length).toBe(1);
      expect($('i.ph-calculator').length).toBe(1);
      expect($('i.ph-clock').length).toBe(1);
      expect($('i.ph-users').length).toBe(1);
      expect($('i.ph-briefcase').length).toBe(1);
    });

    it('ikony mają rozmiar 24px (style font-size)', () => {
      const $ = cheerio.load(renderFeaturesGridHtml(defaultData));
      const icon = $('i.ph').first();
      expect(icon.attr('style')).toContain('font-size: 24px');
    });
  });

  describe('karta cechy', () => {
    it('ikona jest w kwadracie size-12 z hover wypełniającym kolorem brand', () => {
      const $ = cheerio.load(renderFeaturesGridHtml(defaultData));
      const box = $('div.inline-flex.size-12').first();
      expect(box.length).toBe(1);
      expect(box.hasClass('rounded-xl')).toBe(true);
      expect(box.hasClass('border-brand-primary/15')).toBe(true);
      expect(box.hasClass('bg-brand-primary/5')).toBe(true);
      expect(box.hasClass('group-hover:bg-brand-primary')).toBe(true);
      expect(box.hasClass('group-hover:text-white')).toBe(true);
    });

    it('h3 jest tytułem cechy (text-brand-dark)', () => {
      const $ = cheerio.load(renderFeaturesGridHtml(defaultData));
      const firstH3 = $('h3').first();
      expect(firstH3.hasClass('text-brand-dark')).toBe(true);
      expect(firstH3.text()).toBe('Przejrzyste umowy');
    });

    it('opis renderuje się w karcie z text-brand-dark/65', () => {
      const $ = cheerio.load(renderFeaturesGridHtml(defaultData));
      // Why: $('p').first() would catch the section description from the SectionHeader, that's why
      // we are looking for the description in the first tab (p within .grid > div).
      const firstCard = $('.grid > div').first();
      const firstP = firstCard.find('p');
      expect(firstP.hasClass('text-brand-dark/65')).toBe(true);
      expect(firstP.hasClass('leading-relaxed')).toBe(true);
      expect(firstP.text()).toContain('Zero ukrytych kosztów.');
    });
  });

  it('nie zawiera href="#"', () => {
    const html = renderFeaturesGridHtml(defaultData);
    expect(html).not.toContain('href="#"');
  });
});
