import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';

// Why: The contract test reflects the HTML structure generated by
// FeatureGridBlock, sekcja "siatka cech",
// to detect regressions in rendering without running a full build.
// Wzorzec: about-law-contract.test.ts.

interface FeatureGridItem {
  icon: string;
  title: string;
  description: string;
}

interface FeatureGridData {
  heading: string;
  intro: string;
  items: FeatureGridItem[];
}

const PL_DATA: FeatureGridData = {
  heading: 'Co oferujemy',
  intro: 'Kompleksowe wsparcie w realizacji celów, od planowania po wdrożenie i stałą poprawę.',
  items: [
    { icon: 'gear', title: 'Strategia i wykonanie', description: 'Planujemy i wdrażamy krok po kroku.' },
    { icon: 'arrow-up-right', title: 'Trwałe efekty', description: 'Wyniki utrzymują się długo po współpracy.' },
    { icon: 'check-circle', title: 'Sprawdzone metody', description: 'Powtarzalne procedury gwarantujące jakość.' },
  ],
};

const EN_DATA: FeatureGridData = {
  heading: 'What we offer',
  intro: 'End-to-end support in reaching your goals.',
  items: [
    { icon: 'gear', title: 'Strategy and execution', description: 'We plan and implement step by step.' },
    { icon: 'arrow-up-right', title: 'Lasting results', description: 'Outcomes that last long after the engagement.' },
  ],
};

function renderFeatureGridHtml(data: FeatureGridData): string {
  const cardsHtml = data.items
    .map((item) => `
      <article class="flex flex-col gap-4 p-6 ui-radius-lg ui-bg-surface ui-elevation-soft">
        <i class="ph ph-${item.icon} text-3xl text-brand-primary"></i>
        <h3 class="font-heading font-bold ui-type-feature-title ui-text-on-light">${item.title}</h3>
        <p class="leading-relaxed ui-type-text-feature-sm ui-text-on-light-subtle">${item.description}</p>
      </article>`)
    .join('');

  return `<section class="ui-section ui-bg-page">
    <div class="ui-container">
      <div class="flex flex-col gap-6 text-center items-center mb-12 md:mb-16 mx-auto max-w-2xl">
        <h2 class="font-heading font-bold ui-type-section-title text-brand-dark">${data.heading}</h2>
        <p class="leading-relaxed ui-type-lead max-w-2xl font-normal ui-text-on-light-subtle mx-auto">${data.intro}</p>
      </div>
      <div class="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
        ${cardsHtml}
      </div>
    </div>
  </section>`;
}

describe('FeatureGridBlock, kontrakt renderowania', () => {
  it('renderuje dokładnie jedną sekcję z ui-section i ui-bg-page', () => {
    const $ = cheerio.load(renderFeatureGridHtml(PL_DATA));
    expect($('section').length).toBe(1);
    expect($('section').hasClass('ui-section')).toBe(true);
    expect($('section').hasClass('ui-bg-page')).toBe(true);
  });

  it('zawiera .ui-container', () => {
    const $ = cheerio.load(renderFeatureGridHtml(PL_DATA));
    expect($('.ui-container').length).toBe(1);
  });

  describe('nagłówek sekcji', () => {
    it('renderuje dokładnie jeden h2 z tytułem', () => {
      const $ = cheerio.load(renderFeatureGridHtml(PL_DATA));
      expect($('h2').length).toBe(1);
      expect($('h2').text()).toBe('Co oferujemy');
    });

    it('nagłówek jest wyśrodkowany (text-center)', () => {
      const $ = cheerio.load(renderFeatureGridHtml(PL_DATA));
      expect($('h2').parent().hasClass('text-center')).toBe(true);
    });

    it('intro renderuje się jako .ui-type-lead', () => {
      const $ = cheerio.load(renderFeatureGridHtml(PL_DATA));
      expect($('.ui-type-lead').length).toBe(1);
      expect($('.ui-type-lead').text()).toContain('Kompleksowe wsparcie');
    });
  });

  describe('grid', () => {
    it('grid jest mobile-first z trzema kolumnami na desktopie', () => {
      const $ = cheerio.load(renderFeatureGridHtml(PL_DATA));
      const grid = $('.grid');
      expect(grid.hasClass('gap-6')).toBe(true);
      expect(grid.hasClass('md:grid-cols-2')).toBe(true);
      expect(grid.hasClass('lg:grid-cols-3')).toBe(true);
    });
  });

  describe('karty', () => {
    it('renderuje co najmniej 3 karty <article>', () => {
      const $ = cheerio.load(renderFeatureGridHtml(PL_DATA));
      expect($('article').length).toBeGreaterThanOrEqual(3);
    });

    it('każda karta ma klasy ui-radius-lg, ui-bg-surface i ui-elevation-soft', () => {
      const $ = cheerio.load(renderFeatureGridHtml(PL_DATA));
      $('article').each((_, el) => {
        expect($(el).hasClass('ui-radius-lg')).toBe(true);
        expect($(el).hasClass('ui-bg-surface')).toBe(true);
        expect($(el).hasClass('ui-elevation-soft')).toBe(true);
      });
    });

    it('każda karta ma dokładnie jeden h3 z tytułem i jeden p z opisem', () => {
      const $ = cheerio.load(renderFeatureGridHtml(PL_DATA));
      $('article').each((_, el) => {
        expect($(el).children('h3').length).toBe(1);
        expect($(el).children('p').length).toBe(1);
      });
    });

    it('tytuł karty używa ui-text-on-light, opis ui-text-on-light-subtle', () => {
      const $ = cheerio.load(renderFeatureGridHtml(PL_DATA));
      $('article').each((_, el) => {
        expect($(el).children('h3').hasClass('ui-text-on-light')).toBe(true);
        expect($(el).children('p').hasClass('ui-text-on-light-subtle')).toBe(true);
      });
    });

    it('każda karta ma ikonę Phosphor (i.ph) z klasą ph-{icon}', () => {
      const $ = cheerio.load(renderFeatureGridHtml(PL_DATA));
      const icons = $('article i.ph');
      expect(icons.length).toBe(3);
      expect(icons.eq(0).hasClass('ph-gear')).toBe(true);
      expect(icons.eq(1).hasClass('ph-arrow-up-right')).toBe(true);
      expect(icons.eq(2).hasClass('ph-check-circle')).toBe(true);
    });

    it('ikony są w kolorze brand (text-brand-primary)', () => {
      const $ = cheerio.load(renderFeatureGridHtml(PL_DATA));
      $('article i.ph').each((_, el) => {
        expect($(el).hasClass('text-brand-primary')).toBe(true);
      });
    });

    it('pierwsza karta pokazuje tytuł i opis z danych', () => {
      const $ = cheerio.load(renderFeatureGridHtml(PL_DATA));
      const first = $('article').first();
      expect(first.children('h3').text()).toBe('Strategia i wykonanie');
      expect(first.children('p').text()).toContain('Planujemy i wdrażamy');
    });
  });

  describe('i18n (pl/en)', () => {
    it('EN renderuje angielski nagłówek i karty', () => {
      const $ = cheerio.load(renderFeatureGridHtml(EN_DATA));
      expect($('h2').text()).toBe('What we offer');
      expect($('article').length).toBe(2);
      expect($('article').first().children('h3').text()).toBe('Strategy and execution');
    });
  });

  it('nie zawiera danych projektu ani klas reveal', () => {
    const html = renderFeatureGridHtml(PL_DATA);
    expect(html).not.toContain('client-specific');
    expect(html).not.toContain('VSM');
    expect(html).not.toContain('Kaizen');
    expect(html).not.toContain('reveal');
    expect(html).not.toContain('href="#"');
  });
});
