import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';
import { formatInternalLink } from '@utils/url';

// Why: The contract test reflects the HTML structure generated by
// CardsFilterableBlock, sekcja "Obszary wsparcia":
// category filters + grid/list view switcher + lazy load) to detect
// regressions in rendering without running the full build. The test does NOT check
// JavaScript (filters/observers run in the browser), static HTML only.
// Wzorzec: about-law-contract.test.ts.

interface Category {
  id: string;
  label: string;
}

interface FilterableItem {
  title: string;
  subtitle?: string;
  image?: string;
  initials?: string;
  badge?: string;
  bonus?: string;
  rate?: string;
  features?: string[];
  description?: string;
  cta?: { label: string; href: string };
  category?: string;
}

interface FilterableData {
  id?: string;
  locale?: 'pl' | 'en';
  heading: string;
  description: string;
  categories: Category[];
  items: FilterableItem[];
}

const PL_DATA: FilterableData = {
  id: 'obszary-wspolpracy',
  heading: 'Obszary współpracy',
  description: 'Każda firma mierzy się z innymi wyzwaniami. Sprawdź, który obszar najlepiej pasuje do Twoich potrzeb.',
  categories: [
    { id: 'implementacje', label: 'Wdrożenia' },
    { id: 'szkolenia', label: 'Szkolenia' },
    { id: 'audyty', label: 'Audyty' },
  ],
  items: [
    {
      title: 'Audyt procesów',
      subtitle: 'Audyt i monitoring',
      initials: 'AP',
      badge: 'Audyty',
      bonus: 'Raport z rekomendacjami',
      features: ['Audyt efektywności', 'Analiza wskaźników'],
      description: 'Przeprowadzamy audyty procesów i analizę kluczowych wskaźników.',
      cta: { label: 'Umów audyt', href: '/kontakt' },
      category: 'audyty',
    },
    {
      title: 'Szkolenia zespołów',
      subtitle: 'Wiedza w praktyce',
      initials: 'SZ',
      badge: 'Szkolenia',
      bonus: 'Certyfikat ukończenia',
      features: ['VSM', 'Kaizen'],
      description: 'Praktyczne szkolenia rozwijające kompetencje zespołów.',
      cta: { label: 'Sprawdź szkolenia', href: '/#szkolenia' },
      category: 'szkolenia',
    },
    {
      title: 'Wdrożenie zmian',
      subtitle: 'Projekty optymalizacyjne',
      initials: 'WZ',
      badge: 'Wdrożenia',
      bonus: 'Monitoring efektów',
      rate: 'nawet 30%',
      features: ['Diagnoza procesów', 'Mapowanie przepływu'],
      description: 'Realizujemy projekty usprawniające procesy od analizy po wdrożenie.',
      cta: { label: 'Dowiedz się więcej', href: '/#wdrozenia' },
      category: 'implementacje',
    },
    {
      title: 'Wsparcie eksperckie',
      subtitle: 'Outsourcing wiedzy',
      initials: 'WE',
      badge: 'Audyty',
      bonus: 'Dostęp do ekspertów',
      features: ['Analiza procesów', 'Optymalizacja'],
      description: 'Wsparcie ekspertów w analizie i optymalizacji procesów.',
      cta: { label: 'Sprawdź ofertę', href: '/#audyty' },
      category: 'audyty',
    },
  ],
};

const EN_DATA: FilterableData = {
  locale: 'en',
  id: 'areas-of-support',
  heading: 'Areas of support',
  description: 'Every company faces different challenges. Check which area of support fits your needs best.',
  categories: [
    { id: 'implementacje', label: 'Implementations' },
    { id: 'szkolenia', label: 'Training' },
    { id: 'audyty', label: 'Audits' },
  ],
  items: [
    {
      title: 'Process audit',
      subtitle: 'Audit and monitoring',
      initials: 'PA',
      badge: 'Audits',
      bonus: 'Report with recommendations',
      cta: { label: 'Book an audit', href: '/kontakt/' },
      category: 'audyty',
    },
    {
      title: 'Team training',
      subtitle: 'Knowledge in practice',
      initials: 'TT',
      badge: 'Training',
      bonus: 'Completion certificate',
      cta: { label: 'Browse training', href: '/#szkolenia' },
      category: 'szkolenia',
    },
    {
      title: 'Change implementation',
      subtitle: 'Optimization projects',
      initials: 'CI',
      badge: 'Implementations',
      bonus: 'Results monitoring',
      cta: { label: 'Learn more', href: '/#wdrozenia' },
      category: 'implementacje',
    },
  ],
};

function renderFilterableHtml(data: FilterableData): string {
  const {
    id,
    locale = 'pl',
    heading,
    description,
    categories,
    items,
  } = data;

  const isEn = locale === 'en';
  const allLabel = isEn ? 'All' : 'Wszystkie';
  const emptyLabel = isEn ? 'No items in this category' : 'Brak elementów w tej kategorii';
  const filtersLabel = isEn ? 'Category filter' : 'Filtr kategorii';
  const viewLabel = isEn ? 'View' : 'Widok';

  const filters = [{ id: 'all', label: allLabel }, ...categories];

  const pillsHtml = filters
    .map((f) => {
      const active = f.id === 'all';
      const cls = [
        'filter-pill min-h-10 shrink-0 rounded-full border px-4 py-2 text-sm backdrop-blur-md',
        'focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-primary',
        active ? 'filter-pill--active' : '',
      ].filter(Boolean).join(' ');
      return `<button type="button" class="${cls}" data-filter-id="${f.id}" aria-pressed="${active ? 'true' : 'false'}">${f.label}</button>`;
    })
    .join('');

  // Why: in the render we recreate the contract 1:1 with the component: each card is
  // wrapper div (data-filterable-item + data-category) surrounding the article
  // FilterCard that also declares these attributes.
  const cardsHtml = items
    .map((item) => {
      const href = item.cta ? formatInternalLink(item.cta.href) : '';
      return `<div class="min-w-0 filterable-item" data-filterable-item data-category="${item.category || ''}">
        <article class="offer-card" data-filterable-item data-category="${item.category || ''}">
          <h3 class="text-brand-dark">${item.bonus || item.title}</h3>
          <p class="ui-type-body text-brand-dark/70">${item.description || ''}</p>
          ${item.cta ? `<a href="${href}">${item.cta.label}</a>` : ''}
        </article>
      </div>`;
    })
    .join('');

  return `<section id="${id}" class="ui-section relative scroll-mt-[calc(var(--site-header-height,4rem)+0.75rem)]">
    <div class="ui-container">
      <div class="mx-auto mb-12 max-w-2xl text-center md:mb-16">
        <h2 class="font-heading font-bold ui-type-heading-section-lg text-balance">${heading}</h2>
        <p class="leading-relaxed ui-type-lead mt-4 text-pretty">${description}</p>
      </div>
      <div id="filterable-root" class="filterable-root group/filterable" data-view="grid" data-batch="3" data-auto-cap-desktop="9" data-auto-cap-mobile="4" data-initial-mobile="2">
        <div class="mb-6 flex flex-wrap items-center justify-center gap-2 md:mb-8 md:justify-between">
          <div class="w-full min-w-0 md:w-auto">
            <div class="filterable-filters-scroll flex flex-nowrap items-center justify-start gap-2 overflow-x-auto overscroll-x-contain pb-0.5 [-ms-overflow-style:none] [scrollbar-width:none] md:flex-wrap md:justify-center md:overflow-visible md:pb-0 [&::-webkit-scrollbar]:hidden" role="group" aria-label="${filtersLabel}">
              ${pillsHtml}
            </div>
          </div>
          <div class="flex items-center gap-1.5 max-md:hidden" role="group" aria-label="${viewLabel}">
            <button type="button" class="view-btn flex h-9 w-9 items-center justify-center rounded-lg border transition-all duration-200" data-view="grid" aria-pressed="true" title="${isEn ? 'Grid view' : 'Widok siatki'}">
              <svg width="16" height="16" viewBox="0 0 16 16" fill="none"><rect x="1" y="1" width="6" height="6" rx="1" fill="currentColor" opacity="0.4"/><rect x="9" y="1" width="6" height="6" rx="1" fill="currentColor" opacity="0.4"/><rect x="1" y="9" width="6" height="6" rx="1" fill="currentColor" opacity="0.4"/><rect x="9" y="9" width="6" height="6" rx="1" fill="currentColor" /></svg>
            </button>
            <button type="button" class="view-btn flex h-9 w-9 items-center justify-center rounded-lg border transition-all duration-200" data-view="list" aria-pressed="false" title="${isEn ? 'List view' : 'Widok listy'}">
              <svg width="16" height="16" viewBox="0 0 16 16" fill="none"><rect x="1" y="1" width="14" height="3" rx="1" fill="currentColor" opacity="0.4"/><rect x="1" y="6.5" width="14" height="3" rx="1" fill="currentColor" opacity="0.4"/><rect x="1" y="12" width="14" height="3" rx="1" fill="currentColor" /></svg>
            </button>
          </div>
        </div>
        <p class="leading-relaxed ui-type-body text-center text-sm font-medium text-brand-dark/70 hidden" data-filterable-empty aria-live="polite">${emptyLabel}</p>
        <div class="filterable-grid grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3 lg:gap-8 group-data-[view=list]/filterable:grid-cols-1 group-data-[view=list]/filterable:gap-3" data-filterable-grid>
          ${cardsHtml}
        </div>
        <div data-filterable-sentinel class="pointer-events-none h-px w-full shrink-0" aria-hidden="true" />
      </div>
    </div>
  </section>`;
}

describe('CardsFilterableBlock, kontrakt renderowania', () => {
  it('renderuje <section> z ui-section i id', () => {
    const $ = cheerio.load(renderFilterableHtml(PL_DATA));
    expect($('section').length).toBe(1);
    expect($('section').hasClass('ui-section')).toBe(true);
    expect($('section').attr('id')).toBe('obszary-wspolpracy');
  });

  it('zawiera .ui-container', () => {
    const $ = cheerio.load(renderFilterableHtml(PL_DATA));
    expect($('.ui-container').length).toBe(1);
  });

  describe('nagłówek i opis', () => {
    it('renderuje dokładnie jeden h2 (section-heading-lg) z nagłówkiem', () => {
      const $ = cheerio.load(renderFilterableHtml(PL_DATA));
      expect($('h2').length).toBe(1);
      expect($('h2').hasClass('ui-type-heading-section-lg')).toBe(true);
      expect($('h2').text()).toContain('Obszary współpracy');
    });

    it('renderuje opis jako lead', () => {
      const $ = cheerio.load(renderFilterableHtml(PL_DATA));
      expect($('.ui-type-lead').length).toBe(1);
      expect($('.ui-type-lead').text()).toContain('Każda firma');
    });
  });

  describe('korzeń filtra', () => {
    it('ma data-view="grid", data-batch i capy lazy loadu', () => {
      const $ = cheerio.load(renderFilterableHtml(PL_DATA));
      const root = $('#filterable-root');
      expect(root.length).toBe(1);
      expect(root.attr('data-view')).toBe('grid');
      expect(root.attr('data-batch')).toBe('3');
      expect(root.attr('data-auto-cap-desktop')).toBe('9');
      expect(root.attr('data-auto-cap-mobile')).toBe('4');
      expect(root.attr('data-initial-mobile')).toBe('2');
    });

    it('ma grupę group/filterable do przełączania widoku list', () => {
      const $ = cheerio.load(renderFilterableHtml(PL_DATA));
      expect($('#filterable-root').hasClass('group/filterable')).toBe(true);
    });
  });

  describe('filtry kategorii', () => {
    it('renderuje przycisk "all" plus 3+ kategorie (razem 4+ pills z data-filter-id)', () => {
      const $ = cheerio.load(renderFilterableHtml(PL_DATA));
      const pills = $('[data-filter-id]');
      expect(pills.length).toBeGreaterThanOrEqual(4);
    });

    it('pierwszy filtr to "all" z aria-pressed=true, reszta false', () => {
      const $ = cheerio.load(renderFilterableHtml(PL_DATA));
      const pills = $('[data-filter-id]');
      expect(pills.first().attr('data-filter-id')).toBe('all');
      expect(pills.first().attr('aria-pressed')).toBe('true');
      pills.slice(1).each((_, el) => {
        expect($(el).attr('aria-pressed')).toBe('false');
      });
    });

    it('filtr "all" ma klasę aktywną filter-pill--active', () => {
      const $ = cheerio.load(renderFilterableHtml(PL_DATA));
      expect($('[data-filter-id="all"]').hasClass('filter-pill--active')).toBe(true);
    });

    it('zawiera etykiety kategorii (Wdrożenia, Szkolenia, Audyty)', () => {
      const $ = cheerio.load(renderFilterableHtml(PL_DATA));
      expect($('[data-filter-id="implementacje"]').text()).toBe('Wdrożenia');
      expect($('[data-filter-id="szkolenia"]').text()).toBe('Szkolenia');
      expect($('[data-filter-id="audyty"]').text()).toBe('Audyty');
    });

    it('grupa filtrów ma role="group" i aria-label', () => {
      const $ = cheerio.load(renderFilterableHtml(PL_DATA));
      const group = $('[role="group"][aria-label="Filtr kategorii"]');
      expect(group.length).toBe(1);
    });
  });

  describe('karty', () => {
    it('renderuje 3+ kart z data-filterable-item', () => {
      const $ = cheerio.load(renderFilterableHtml(PL_DATA));
      // Why: each tab is a wrapper div + a FilterCard article, both
      // z data-filterable-item (kontrakt z JS-em filtrowania).
      expect($('.filterable-item').length).toBeGreaterThanOrEqual(3);
      expect($('[data-filterable-item]').length).toBeGreaterThanOrEqual(6);
    });

    it('każda karta deklaruje data-category', () => {
      const $ = cheerio.load(renderFilterableHtml(PL_DATA));
      $('.filterable-item').each((_, el) => {
        const cat = $(el).attr('data-category');
        expect(cat).toBeTruthy();
        expect(['audyty', 'szkolenia', 'implementacje']).toContain(cat);
      });
    });

    it('grid ma klasę przełącznika widoku list (group-data-[view=list])', () => {
      const $ = cheerio.load(renderFilterableHtml(PL_DATA));
      const grid = $('[data-filterable-grid]');
      expect(grid.hasClass('group-data-[view=list]/filterable:grid-cols-1')).toBe(true);
    });

    it('karty są w gridzie mobile-first (1 kolumna, md:2, lg:3)', () => {
      const $ = cheerio.load(renderFilterableHtml(PL_DATA));
      const grid = $('[data-filterable-grid]');
      expect(grid.hasClass('grid-cols-1')).toBe(true);
      expect(grid.hasClass('md:grid-cols-2')).toBe(true);
      expect(grid.hasClass('lg:grid-cols-3')).toBe(true);
    });
  });

  describe('przyciski widoków (grid/list)', () => {
    it('renderuje 2 przyciski .view-btn z data-view grid i list', () => {
      const $ = cheerio.load(renderFilterableHtml(PL_DATA));
      const btns = $('.view-btn');
      expect(btns.length).toBe(2);
      expect($('.view-btn[data-view="grid"]').length).toBe(1);
      expect($('.view-btn[data-view="list"]').length).toBe(1);
    });

    it('grid jest aktywny (aria-pressed=true), list nieaktywny', () => {
      const $ = cheerio.load(renderFilterableHtml(PL_DATA));
      expect($('.view-btn[data-view="grid"]').attr('aria-pressed')).toBe('true');
      expect($('.view-btn[data-view="list"]').attr('aria-pressed')).toBe('false');
    });

    it('przyciski zawierają ikony SVG (grid/list nie ma w phosphor-min.css)', () => {
      const $ = cheerio.load(renderFilterableHtml(PL_DATA));
      $('.view-btn').each((_, el) => {
        expect($(el).find('svg').length).toBe(1);
      });
    });
  });

  describe('lazy load i empty state', () => {
    it('renderuje sentinel z data-filterable-sentinel (IntersectionObserver)', () => {
      const $ = cheerio.load(renderFilterableHtml(PL_DATA));
      expect($('[data-filterable-sentinel]').length).toBe(1);
      expect($('[data-filterable-sentinel]').attr('aria-hidden')).toBe('true');
    });

    it('renderuje empty state z data-filterable-empty i aria-live="polite"', () => {
      const $ = cheerio.load(renderFilterableHtml(PL_DATA));
      const empty = $('[data-filterable-empty]');
      expect(empty.length).toBe(1);
      expect(empty.attr('aria-live')).toBe('polite');
      expect(empty.text()).toContain('Brak elementów w tej kategorii');
    });
  });

  describe('czystość biblioteki (zero danych klienta)', () => {
    it('nie zawiera nazw ani treści projektu źródłowego', () => {
      const html = renderFilterableHtml(PL_DATA);
      expect(html).not.toContain('client-specific');
      expect(html).not.toContain('Optymalizacja produkcji');
      expect(html).not.toContain('Obszary wsparcia');
    });

    it('nie zawiera klienckich klas ani tokenów CSS (text-on-surface-variant, --color-outline)', () => {
      const html = renderFilterableHtml(PL_DATA);
      expect(html).not.toContain('text-on-surface-variant');
      expect(html).not.toContain('var(--color-outline)');
      expect(html).not.toContain('var(--color-on-surface-variant)');
    });

    it('nie zawiera klienckiego systemu reveal (data-reveal, reveal-group, class="reveal)', () => {
      const html = renderFilterableHtml(PL_DATA);
      expect(html).not.toContain('data-reveal');
      expect(html).not.toContain('reveal-group');
      expect(html).not.toContain('class="reveal');
    });

    it('używa tokena text-brand-dark/70 zamiast klienckiego koloru w empty state', () => {
      const $ = cheerio.load(renderFilterableHtml(PL_DATA));
      expect($('[data-filterable-empty]').hasClass('text-brand-dark/70')).toBe(true);
    });
  });

  describe('linki (formatInternalLink)', () => {
    it('link do podstrony dostaje trailing slash (/kontakt -> /kontakt/)', () => {
      const html = renderFilterableHtml(PL_DATA);
      expect(html).toContain('href="/kontakt/"');
      expect(html).not.toContain('href="/kontakt"');
    });

    it('linki kotwicowe (/#...) zostają nietknięte', () => {
      const $ = cheerio.load(renderFilterableHtml(PL_DATA));
      expect($('a[href="/#szkolenia"]').length).toBe(1);
      expect($('a[href="/#wdrozenia"]').length).toBe(1);
      expect($('a[href="/#audyty"]').length).toBe(1);
    });
  });

  describe('i18n (pl/en)', () => {
    it('EN renderuje angielski nagłówek, opis i etykiety filtrów', () => {
      const $ = cheerio.load(renderFilterableHtml(EN_DATA));
      expect($('h2').text()).toContain('Areas of support');
      expect($('.ui-type-lead').text()).toContain('Every company');
      expect($('[data-filter-id="all"]').text()).toBe('All');
      expect($('[data-filter-id="audyty"]').text()).toBe('Audits');
    });

    it('EN ma angielski empty state i przyciski widoków', () => {
      const $ = cheerio.load(renderFilterableHtml(EN_DATA));
      expect($('[data-filterable-empty]').text()).toContain('No items in this category');
      expect($('.view-btn[data-view="grid"]').attr('title')).toBe('Grid view');
      expect($('.view-btn[data-view="list"]').attr('title')).toBe('List view');
    });

    it('liczba kart jest elastyczna (propsy nadpisują JSON)', () => {
      const custom = { ...PL_DATA, items: PL_DATA.items.slice(0, 2) };
      const $ = cheerio.load(renderFilterableHtml(custom));
      expect($('.filterable-item').length).toBe(2);
    });
  });

  it('nie zawiera href="#" ani zepsutych linków', () => {
    const html = renderFilterableHtml(PL_DATA);
    expect(html).not.toContain('href="#"');
    expect(html).not.toContain('href=""');
  });
});
