import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';

// Why: The contract test reflects the HTML structure generated by
// HeroEditorialBlock, wariant hero z dekoracyjnymi blobami,
// accented headline, trust badges and marquee) to detect regressions without
// running a full build. Pattern: hero-law-contract.test.ts.

interface Cta {
  label: string;
  href: string;
}

interface MarqueeItem {
  name: string;
  icon?: string;
  initials?: string;
}

interface TrustBadge {
  icon: string;
  label: string;
}

interface HeroEditorialData {
  id?: string;
  eyebrow: string;
  heading: string;
  headingAccent: string;
  description: string;
  primaryCTA: Cta;
  trustBadges: TrustBadge[];
  marqueeItems: MarqueeItem[];
}

// Why: The default test data is Polish content from hero-editorial.json
// (PL is the default language of the block). The content is general, without customer data.
const DEFAULT_DATA: HeroEditorialData = {
  id: 'hero-editorial',
  eyebrow: 'Studio kreatywne',
  heading: 'Kreatywność i strategia',
  headingAccent: 'w jednym miejscu.',
  description:
    'Projektujemy marki i strony internetowe, które łączą wyrazisty design z działającymi rozwiązaniami.',
  primaryCTA: { label: 'Umów rozmowę', href: '/kontakt/' },
  trustBadges: [
    { icon: 'star', label: 'Sprawdzone metody' },
    { icon: 'shield-chevron', label: 'Gwarancja jakości' },
    { icon: 'check-circle', label: 'Mierzalne efekty' },
  ],
  marqueeItems: [
    { name: 'Branding', icon: 'star' },
    { name: 'Strategia', icon: 'gear' },
    { name: 'Design', icon: 'pencil' },
    { name: 'Digital', icon: 'waveform' },
    { name: 'Wideo', icon: 'play' },
    { name: 'Content', icon: 'chat' },
  ],
};

const EN_DATA: HeroEditorialData = {
  ...DEFAULT_DATA,
  eyebrow: 'Creative studio',
  heading: 'Creativity and strategy',
  headingAccent: 'in one place.',
  description: 'We design brands and websites that combine distinctive design with solutions that actually work.',
  primaryCTA: { label: 'Book a call', href: '/kontakt/' },
  trustBadges: [
    { icon: 'star', label: 'Proven methods' },
    { icon: 'shield-chevron', label: 'Quality guarantee' },
    { icon: 'check-circle', label: 'Measurable results' },
  ],
  marqueeItems: [
    { name: 'Branding', icon: 'star' },
    { name: 'Strategy', icon: 'gear' },
    { name: 'Design', icon: 'pencil' },
  ],
};

// Why: approximate copy of Button.astro classes (primary variant, lg size),
// because the test checks the structural contract, not the full list of Tailwind classes.
const BUTTON_BASE_CLASS =
  'ui-button ui-type-cta-label group inline-flex items-center justify-center gap-1.5 rounded-md whitespace-nowrap transition-all font-semibold focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-brand-primary/50';

function renderBadge(badge: TrustBadge): string {
  return `<span class="flex shrink-0 items-center gap-1.5 text-sm text-brand-dark/70">
    <i class="ph ph-${badge.icon} text-brand-primary"></i>${badge.label}
  </span>`;
}

function renderMarqueePill(item: MarqueeItem): string {
  const iconHtml = item.icon
    ? `<i class="ph ph-${item.icon} text-brand-primary"></i>`
    : `<span class="flex size-7 items-center justify-center text-[10px] font-bold text-brand-primary">${item.initials || item.name.charAt(0)}</span>`;
  return `<span class="flex shrink-0 items-center gap-2.5 rounded-full bg-white/65 px-4 py-2 shadow-sm backdrop-blur-sm">
    ${iconHtml}
    <span class="whitespace-nowrap text-sm font-medium text-brand-dark/70">${item.name}</span>
  </span>`;
}

function renderHeroEditorialHtml(data: HeroEditorialData): string {
  const { id = 'hero-editorial' } = data;

  // Why: marquee repeats the list 3 times (like a component) to animate
  // translateX(-33.333%) closed the loop without a jump. Separators between badges
  // are rendered for all positions except the last one.
  const badgesHtml = data.trustBadges
    .map(
      (badge, i) =>
        `${renderBadge(badge)}${i < data.trustBadges.length - 1 ? '<span class="hidden h-3 w-px bg-brand-dark/10 sm:block"></span>' : ''}`
    )
    .join('');
  const pillsHtml = Array.from({ length: 3 }, () => data.marqueeItems)
    .flat()
    .map(renderMarqueePill)
    .join('');

  return `<section id="${id}" class="ui-section relative overflow-x-hidden pb-0!">
    <div class="pointer-events-none absolute inset-0 z-0" aria-hidden="true"></div>
    <div class="ui-container">
      <div class="relative z-10 flex flex-col items-center py-[clamp(3rem,12vw,8rem)] text-center">
        <div class="mb-5">
          <p class="leading-relaxed ui-type-accent-label">${data.eyebrow}</p>
        </div>
        <h1 class="font-heading font-bold ui-type-heading-hero max-w-4xl text-balance">${data.heading}<span class="text-brand-primary"> ${data.headingAccent}</span></h1>
        <p class="leading-relaxed ui-type-lead mx-auto mt-6 max-w-xl text-pretty">${data.description}</p>
        <div class="mt-8 flex flex-wrap items-center justify-center gap-4">
          <a href="${data.primaryCTA.href}" class="${BUTTON_BASE_CLASS} ui-button-primary h-11 sm:h-12 px-5 sm:px-8 text-sm sm:text-lg [&_svg]:size-5">${data.primaryCTA.label}</a>
        </div>
        <div class="mt-10 flex flex-wrap items-center justify-center gap-x-6 gap-y-2">
          ${badgesHtml}
        </div>
      </div>
    </div>
    <div class="pointer-events-none z-10 w-full shrink-0 pb-6 pt-2" aria-hidden="true">
      <div class="ui-container hero-marquee-mask">
        <div class="hero-marquee-track flex gap-5">
          ${pillsHtml}
        </div>
      </div>
    </div>
  </section>`;
}

describe('HeroEditorialBlock, kontrakt renderowania', () => {
  it('renderuje <section> z ui-section, relative i id', () => {
    const $ = cheerio.load(renderHeroEditorialHtml(DEFAULT_DATA));
    expect($('section').length).toBe(1);
    expect($('section').hasClass('ui-section')).toBe(true);
    expect($('section').hasClass('relative')).toBe(true);
    expect($('section').hasClass('overflow-x-hidden')).toBe(true);
    expect($('section').attr('id')).toBe('hero-editorial');
  });

  it('sekcja nie ma dolnego paddingu (marquee przyklejony do dołu)', () => {
    const $ = cheerio.load(renderHeroEditorialHtml(DEFAULT_DATA));
    expect($('section').hasClass('pb-0!')).toBe(true);
  });

  it('zawiera warstwę dekoracji pod treścią (pointer-events-none, z-0, aria-hidden)', () => {
    const $ = cheerio.load(renderHeroEditorialHtml(DEFAULT_DATA));
    const decor = $('.pointer-events-none.absolute.inset-0.z-0');
    expect(decor.length).toBe(1);
    expect(decor.attr('aria-hidden')).toBe('true');
  });

  it('zawiera dwa .ui-container (treść i marquee)', () => {
    const $ = cheerio.load(renderHeroEditorialHtml(DEFAULT_DATA));
    expect($('.ui-container').length).toBe(2);
  });

  describe('nagłówek', () => {
    it('renderuje dokładnie jeden h1 z wariantem hero', () => {
      const $ = cheerio.load(renderHeroEditorialHtml(DEFAULT_DATA));
      expect($('h1').length).toBe(1);
      expect($('h1').hasClass('ui-type-heading-hero')).toBe(true);
    });

    it('h1 zawiera pełny tekst z akcentem w kolorze brand', () => {
      const $ = cheerio.load(renderHeroEditorialHtml(DEFAULT_DATA));
      const h1 = $('h1');
      expect(h1.text()).toBe('Kreatywność i strategia w jednym miejscu.');
      const accent = h1.find('span');
      expect(accent.length).toBe(1);
      expect(accent.hasClass('text-brand-primary')).toBe(true);
      expect(accent.text()).toContain('w jednym miejscu.');
    });

    it('h1 jest wyśrodkowany i balansowany (text-balance, max-w-4xl)', () => {
      const $ = cheerio.load(renderHeroEditorialHtml(DEFAULT_DATA));
      const h1 = $('h1');
      expect(h1.hasClass('text-balance')).toBe(true);
      expect(h1.hasClass('max-w-4xl')).toBe(true);
    });
  });

  describe('eyebrow i opis', () => {
    it('eyebrow to ui-type-accent-label nad h1', () => {
      const $ = cheerio.load(renderHeroEditorialHtml(DEFAULT_DATA));
      const label = $('.ui-type-accent-label');
      expect(label.length).toBe(1);
      expect(label.text()).toBe('Studio kreatywne');
    });

    it('opis renderuje się jako ui-type-lead z max-w-xl', () => {
      const $ = cheerio.load(renderHeroEditorialHtml(DEFAULT_DATA));
      const lead = $('.ui-type-lead');
      expect(lead.length).toBe(1);
      expect(lead.hasClass('max-w-xl')).toBe(true);
      expect(lead.text()).toContain('Projektujemy marki i strony');
    });
  });

  describe('przycisk CTA', () => {
    it('renderuje dokładnie jeden a.ui-button z wariantem primary', () => {
      const $ = cheerio.load(renderHeroEditorialHtml(DEFAULT_DATA));
      expect($('a.ui-button').length).toBe(1);
      expect($('a.ui-button').hasClass('ui-button-primary')).toBe(true);
    });

    it('przycisk prowadzi na /kontakt/ z trailing slash i ma label', () => {
      const $ = cheerio.load(renderHeroEditorialHtml(DEFAULT_DATA));
      const button = $('a.ui-button');
      expect(button.attr('href')).toBe('/kontakt/');
      expect(button.text()).toBe('Umów rozmowę');
    });
  });

  describe('trust badges', () => {
    it('renderuje dokładnie N pozycji trust badges z danych', () => {
      const $ = cheerio.load(renderHeroEditorialHtml(DEFAULT_DATA));
      expect($('span.gap-1\\.5').length).toBe(3);
    });

    it('każdy badge ma ikonę Phosphor w kolorze brand i label', () => {
      const $ = cheerio.load(renderHeroEditorialHtml(DEFAULT_DATA));
      const badges = $('span.gap-1\\.5');
      expect(badges.eq(0).find('i.ph.ph-star').length).toBe(1);
      expect(badges.eq(0).text()).toContain('Sprawdzone metody');
      expect(badges.eq(1).find('i.ph.ph-shield-chevron').length).toBe(1);
      expect(badges.eq(2).find('i.ph.ph-check-circle').length).toBe(1);
    });

    it('separatory między badgeami używają tokena bg-brand-dark/10', () => {
      const $ = cheerio.load(renderHeroEditorialHtml(DEFAULT_DATA));
      expect($('span.bg-brand-dark\\/10').length).toBe(2);
    });
  });

  describe('marquee', () => {
    it('zawiera maskę i track z animacją', () => {
      const $ = cheerio.load(renderHeroEditorialHtml(DEFAULT_DATA));
      expect($('.hero-marquee-mask').length).toBe(1);
      expect($('.hero-marquee-track').length).toBe(1);
    });

    it('renderuje pille jako 3 kopie listy (6 pozycji x 3 = 18)', () => {
      const $ = cheerio.load(renderHeroEditorialHtml(DEFAULT_DATA));
      expect($('span.rounded-full.bg-white\\/65').length).toBe(18);
    });

    it('pierwsza pilla ma ikonę ph-star i nazwę', () => {
      const $ = cheerio.load(renderHeroEditorialHtml(DEFAULT_DATA));
      const pill = $('span.rounded-full.bg-white\\/65').first();
      expect(pill.find('i.ph.ph-star').length).toBe(1);
      expect(pill.text()).toContain('Branding');
    });

    it('marquee jest aria-hidden (dekoracja)', () => {
      const $ = cheerio.load(renderHeroEditorialHtml(DEFAULT_DATA));
      const wrap = $('.hero-marquee-mask').parent();
      expect(wrap.attr('aria-hidden')).toBe('true');
    });
  });

  describe('i18n (pl/en)', () => {
    it('EN renderuje angielski nagłówek, opis i CTA', () => {
      const $ = cheerio.load(renderHeroEditorialHtml(EN_DATA));
      expect($('h1').text()).toBe('Creativity and strategy in one place.');
      expect($('.ui-type-lead').text()).toContain('We design brands');
      expect($('a.ui-button').text()).toBe('Book a call');
      expect($('.ui-type-accent-label').text()).toBe('Creative studio');
    });

    it('liczba elementów jest elastyczna (propsy nadpisują JSON)', () => {
      const custom = {
        ...DEFAULT_DATA,
        trustBadges: [{ icon: 'star', label: 'Tylko jeden' }],
        marqueeItems: [{ name: 'Tylko jedna pozycja', icon: 'star' }],
      };
      const $ = cheerio.load(renderHeroEditorialHtml(custom));
      expect($('span.gap-1\\.5').length).toBe(1);
      expect($('span.rounded-full.bg-white\\/65').length).toBe(3);
      expect($('span.bg-brand-dark\\/10').length).toBe(0);
    });
  });

  it('nie zawiera klienckiego systemu reveal (usunięty na rzecz motion starter-kita)', () => {
    const html = renderHeroEditorialHtml(DEFAULT_DATA);
    expect(html).not.toContain('reveal');
    expect(html).not.toContain('data-reveal');
    expect(html).not.toContain('auto-reveal');
  });

  it('nie zawiera ikon spoza phosphor-min.css ani klienckich tokenów CSS', () => {
    const html = renderHeroEditorialHtml(DEFAULT_DATA);
    expect(html).not.toContain('ph-shield-check');
    expect(html).not.toContain('ph-chart-line');
    expect(html).not.toContain('ph-heart');
    expect(html).not.toContain('text-on-surface-variant');
    expect(html).not.toContain('bg-on-surface-variant');
    expect(html).not.toContain('--color-');
    expect(html).not.toContain('href="#"');
  });
});
