import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';

// Why: The contract test reflects the HTML structure generated by
// HeroPhotoBlock, a copy of the fullscreen hero from a reference layout:
// background photo + gradient + logo marquee) to detect regressions
// in rendering without running the full build. Pattern:
// about-law-contract.test.ts. Note: the tests in this repo build HTML manually,
// a nie przez renderToString z astro, bo vitest nie ma pluginu Astro.

interface Cta {
  label: string;
  href: string;
}

interface Brand {
  name: string;
  src: string;
  alt: string;
}

interface HeroPhotoData {
  sectionId?: string;
  locale?: 'pl' | 'en';
  eyebrow: string;
  heading: string;
  headingAccent: string;
  lead: string;
  ctaPrimary: Cta;
  ctaSecondary: Cta;
  footnote: string[];
  trustCount: string;
  background: { src: string; alt: string };
  brands: Brand[];
}

const DEFAULT_BACKGROUND = {
  src: '/assets/placeholders/image-landscape.svg',
  alt: 'Placeholder zdjęcia panoramicznego w tle sekcji',
};

// Why: 8 general logos (company-1..8), zero customer data.
const DEFAULT_BRANDS: Brand[] = Array.from({ length: 8 }, (_, index) => ({
  name: `firma-${index + 1}.png`,
  src: '/assets/placeholders/logo-placeholder.svg',
  alt: `Logo firmy ${index + 1}`,
}));

const PL_DATA: HeroPhotoData = {
  eyebrow: 'Dla średnich i dużych zakładów produkcyjnych',
  heading: 'Przestoje, straty, gaszenie pożarów?',
  headingAccent: 'Czas to zmienić.',
  lead: 'Pomagamy firmom produkcyjnym znaleźć źródła strat i wdrożyć zmiany, które działają na co dzień, nie tylko na papierze.',
  ctaPrimary: { label: 'Umów 30-minutową rozmowę', href: '/#kontakt' },
  ctaSecondary: { label: 'Zobacz, jak pracujemy', href: '/#proces' },
  footnote: ['Ponad 20 lat w produkcji', 'projekty od diagnozy po wdrożenie'],
  trustCount: 'Zaufało nam 8 firm',
  background: DEFAULT_BACKGROUND,
  brands: DEFAULT_BRANDS,
};

const EN_DATA: HeroPhotoData = {
  ...PL_DATA,
  locale: 'en',
  heading: 'Downtime, waste, constant firefighting?',
  headingAccent: 'Time to change that.',
  lead: 'We help manufacturing companies find the sources of waste and implement changes that work day in, day out, not just on paper.',
  ctaPrimary: { label: 'Book a 30-minute call', href: '/#kontakt' },
  ctaSecondary: { label: 'See how we work', href: '/#proces' },
  footnote: ['Over 20 years in manufacturing', 'projects from diagnosis to rollout'],
  trustCount: 'Trusted by 8 companies',
};

function renderBrands(brands: Brand[]): string {
  return brands
    .map(
      (brand) =>
        `<img src="${brand.src}" alt="${brand.alt}" class="h-7 w-auto object-contain opacity-70" loading="lazy" decoding="async">`
    )
    .join('');
}

function renderHeroPhotoHtml(data: HeroPhotoData): string {
  const {
    sectionId = 'hero',
    eyebrow,
    heading,
    headingAccent,
    lead,
    ctaPrimary,
    ctaSecondary,
    footnote,
    trustCount,
    background,
    brands,
  } = data;

  // Why: marquee content is a 3x repeated list of brands (animation loop).
  const marqueeContent = [0, 1, 2].map(() => renderBrands(brands)).join('');

  const footnoteHtml = footnote
    .map(
      (part, index) =>
        `${index > 0 ? '<span class="mx-3 text-white/20">|</span>' : ''}${part}`
    )
    .join('');

  return `<section id="${sectionId}" class="ui-section ui-bg-page relative flex min-h-screen max-h-[1080px] flex-col overflow-hidden !pt-0 !pb-0" data-motion-section>
    <div class="absolute inset-0 z-0">
      <img src="${background.src}" alt="${background.alt}" class="h-full w-full object-cover brightness-[0.5] saturate-[1.05]" style="object-position: 80% center;" loading="eager" fetchpriority="high">
      <div class="absolute inset-0" style="background: linear-gradient(100deg, color-mix(in oklab, var(--color-brand-dark) 88%, transparent) 0%, color-mix(in oklab, var(--color-brand-dark) 52%, transparent) 35%, transparent 62%);"></div>
    </div>
    <div class="relative z-10 mx-auto flex w-[calc(100%-2rem)] max-w-[1280px] flex-1 items-center pb-12 pt-32 lg:pb-14 lg:pt-36" style="max-height:1080px">
      <div class="w-full">
        <div class="mx-auto max-w-[700px] text-center lg:mx-0 lg:text-left">
          <p class="leading-relaxed ui-type-accent-label mb-6 block !text-[0.75rem] !font-extrabold !tracking-[0.26em] !text-white/70">${eyebrow}</p>
          <h1 class="font-heading font-bold text-balance !font-extrabold !text-white leading-[1.08] text-[clamp(1.75rem,5vw,3.2rem)]">
            ${heading} <span class="underline decoration-brand-accent decoration-[5px] underline-offset-[10px]">${headingAccent}</span>
          </h1>
          <p class="leading-relaxed ui-type-lead mt-6 !font-semibold leading-[1.7]" style="color:color-mix(in oklab, var(--color-brand-light) 85%, transparent)">${lead}</p>
          <div class="mt-8 flex flex-wrap items-center justify-center gap-4 lg:justify-start">
            <a href="${ctaPrimary.href}" class="ui-button ui-button-accent ...">${ctaPrimary.label}</a>
            <a href="${ctaSecondary.href}" class="ui-button ui-button-outline ...">${ctaSecondary.label}</a>
          </div>
          <div class="mt-6 border-t border-white/10 pt-4 text-center text-sm font-semibold tracking-wide text-white/50 lg:text-left">
            ${footnoteHtml}
          </div>
        </div>
      </div>
    </div>
    <div class="relative z-10 mt-auto w-full px-4 pb-4 pt-10 lg:pb-6 lg:pt-14">
      <p class="leading-relaxed mb-8 text-center !text-xs !font-extrabold !tracking-[0.22em]" style="color:rgba(255,255,255,0.6)">${trustCount}</p>
      <div class="lc-marquee-mask overflow-hidden">
        <div class="lc-marquee-track flex w-max items-center gap-12">
          ${marqueeContent}
        </div>
      </div>
    </div>
  </section>`;
}

describe('HeroPhotoBlock, kontrakt renderowania', () => {
  it('renderuje <section> z ui-section, tone page i id', () => {
    const $ = cheerio.load(renderHeroPhotoHtml(PL_DATA));
    expect($('section').length).toBe(1);
    expect($('section').hasClass('ui-section')).toBe(true);
    expect($('section').hasClass('ui-bg-page')).toBe(true);
    expect($('section').attr('id')).toBe('hero');
  });

  it('sekcja jest pełnoekranowa i bez pionowych paddingów', () => {
    const $ = cheerio.load(renderHeroPhotoHtml(PL_DATA));
    expect($('section').hasClass('min-h-screen')).toBe(true);
    expect($('section').hasClass('!pt-0')).toBe(true);
    expect($('section').hasClass('!pb-0')).toBe(true);
  });

  describe('tło', () => {
    it('renderuje obraz tła z placeholderem i przyciemnieniem', () => {
      const $ = cheerio.load(renderHeroPhotoHtml(PL_DATA));
      const bgImg = $('.absolute.inset-0 img');
      expect(bgImg.length).toBe(1);
      expect(bgImg.attr('src')).toBe('/assets/placeholders/image-landscape.svg');
      expect(bgImg.hasClass('brightness-[0.5]')).toBe(true);
      expect(bgImg.attr('fetchpriority')).toBe('high');
    });

    it('gradient overlay używa tokena brand-dark, nie klienckiego koloru', () => {
      const html = renderHeroPhotoHtml(PL_DATA);
      expect(html).toContain('var(--color-brand-dark)');
      expect(html).not.toContain('#005862');
    });
  });

  describe('treść hero', () => {
    it('renderuje dokładnie jeden h1 z nagłówkiem i akcentem', () => {
      const $ = cheerio.load(renderHeroPhotoHtml(PL_DATA));
      expect($('h1').length).toBe(1);
      expect($('h1').text()).toContain('Przestoje, straty, gaszenie pożarów?');
      expect($('h1').text()).toContain('Czas to zmienić.');
      const accent = $('h1 span.underline');
      expect(accent.hasClass('decoration-brand-accent')).toBe(true);
    });

    it('eyebrow używa wariantu accent-label i białego tekstu', () => {
      const $ = cheerio.load(renderHeroPhotoHtml(PL_DATA));
      const eyebrow = $('p.ui-type-accent-label');
      expect(eyebrow.length).toBe(1);
      expect(eyebrow.text()).toContain('Dla średnich i dużych zakładów produkcyjnych');
      expect(eyebrow.hasClass('!text-white/70')).toBe(true);
    });

    it('lead używa color-mix na brand-light', () => {
      const $ = cheerio.load(renderHeroPhotoHtml(PL_DATA));
      expect($('p.ui-type-lead').length).toBe(1);
      expect($('p.ui-type-lead').attr('style')).toContain('color-mix(in oklab, var(--color-brand-light) 85%, transparent)');
    });
  });

  describe('przyciski CTA', () => {
    it('renderuje dokładnie 2 przyciski-linki z href', () => {
      const $ = cheerio.load(renderHeroPhotoHtml(PL_DATA));
      const buttons = $('a.ui-button');
      expect(buttons.length).toBe(2);
      expect(buttons.eq(0).attr('href')).toBe('/#kontakt');
      expect(buttons.eq(1).attr('href')).toBe('/#proces');
    });

    it('primary CTA ma wariant accent (text swap z systemu ui-button, bez legacy btn-slide)', () => {
      const $ = cheerio.load(renderHeroPhotoHtml(PL_DATA));
      const primary = $('a.ui-button').first();
      expect(primary.hasClass('ui-button-accent')).toBe(true);
      expect(primary.hasClass('btn-slide')).toBe(false);
      expect(primary.text()).toContain('Umów 30-minutową rozmowę');
    });

    it('secondary CTA używa wariantu outline', () => {
      const $ = cheerio.load(renderHeroPhotoHtml(PL_DATA));
      const secondary = $('a.ui-button').last();
      expect(secondary.hasClass('ui-button-outline')).toBe(true);
      expect(secondary.text()).toContain('Zobacz, jak pracujemy');
    });

    it('nie ma gołych kotwic href="#"', () => {
      const html = renderHeroPhotoHtml(PL_DATA);
      expect(html).not.toContain('href="#"');
    });
  });

  describe('footnote', () => {
    it('renderuje obie części z separatorem |', () => {
      const $ = cheerio.load(renderHeroPhotoHtml(PL_DATA));
      const footnote = $('.border-t');
      expect(footnote.text()).toContain('Ponad 20 lat w produkcji');
      expect(footnote.text()).toContain('projekty od diagnozy po wdrożenie');
      expect(footnote.find('span').text()).toBe('|');
    });
  });

  describe('marquee logotypów', () => {
    it('renderuje pasek z klasami maski i animacji', () => {
      const $ = cheerio.load(renderHeroPhotoHtml(PL_DATA));
      expect($('.lc-marquee-mask').length).toBe(1);
      expect($('.lc-marquee-track').length).toBe(1);
    });

    it('lista brandów jest powtórzona 3x (8 x 3 = 24 img)', () => {
      const $ = cheerio.load(renderHeroPhotoHtml(PL_DATA));
      expect($('.lc-marquee-track img').length).toBe(24);
      expect($('.lc-marquee-track img[alt="Logo firmy 1"]').length).toBe(3);
      expect($('.lc-marquee-track img[alt="Logo firmy 8"]').length).toBe(3);
    });

    it('logotypy używają placeholderów biblioteki, nie plików klienta', () => {
      const $ = cheerio.load(renderHeroPhotoHtml(PL_DATA));
      $('.lc-marquee-track img').each((_, el) => {
        expect($(el).attr('src')).toBe('/assets/placeholders/logo-placeholder.svg');
      });
    });

    it('etykieta zaufania pokazuje liczbę firm z danych', () => {
      const $ = cheerio.load(renderHeroPhotoHtml(PL_DATA));
      expect($('p.mb-8.text-center').text()).toContain('Zaufało nam 8 firm');
    });
  });

  describe('brak danych i mechanizmów klienta', () => {
    it('nie zawiera nazw logotypów klienta (Budvar, Toyota itd.)', () => {
      const html = renderHeroPhotoHtml(PL_DATA);
      expect(html).not.toContain('budvar');
      expect(html).not.toContain('toyota');
      expect(html).not.toContain('mokate');
      expect(html).not.toContain('oknoplast');
      expect(html).not.toContain('scanfil');
    });

    it('nie zawiera ścieżek ani nazwy klienta', () => {
      const html = renderHeroPhotoHtml(PL_DATA);
      expect(html).not.toContain('client-specific');
      expect(html).not.toContain('/client-specific/');
    });

    it('nie ma klienckich klas reveal ani atrybutów data-reveal', () => {
      const html = renderHeroPhotoHtml(PL_DATA);
      expect(html).not.toContain('data-reveal');
      expect(html).not.toContain('data-reveal-group');
    });

    it('nie ma klienckich tokenów kolorów', () => {
      const html = renderHeroPhotoHtml(PL_DATA);
      expect(html).not.toContain('text-on-surface-variant');
      expect(html).not.toContain('border-outline');
      expect(html).not.toContain('bg-brand-cream');
    });
  });

  describe('i18n (pl/en)', () => {
    it('EN renderuje angielski nagłówek i etykietę zaufania', () => {
      const $ = cheerio.load(renderHeroPhotoHtml(EN_DATA));
      expect($('h1').text()).toContain('Downtime, waste, constant firefighting?');
      expect($('p.mb-8.text-center').text()).toContain('Trusted by 8 companies');
    });

    it('EN zachowuje te same placeholdery i liczbę brandów', () => {
      const $ = cheerio.load(renderHeroPhotoHtml(EN_DATA));
      expect($('.lc-marquee-track img').length).toBe(24);
      expect($('img').first().attr('src')).toBe('/assets/placeholders/image-landscape.svg');
    });
  });
});
