import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';

// Why: The contract test reflects the HTML structure generated by
// HeroSplitBlock to detect regressions in rendering without running full render
// builda. Wzorzec: hero-law-contract.test.ts.

interface Cta {
  label: string;
  href: string;
  hoverText?: string;
}

interface Stat {
  value: string;
  label: string;
}

interface GoogleRating {
  rating: number;
  count: number;
  label: string;
}

interface HeroSplitData {
  sectionId?: string;
  label?: string;
  title: string;
  description: string;
  primaryCTA: Cta;
  secondaryCTA: Cta;
  stats?: Stat[];
  trustBar?: string[];
  trustBarVariant?: 'split' | 'mid' | 'pills';
  images?: string[];
  googleRating?: GoogleRating;
  theme?: 'light' | 'dark';
}

// Why: the default test data is Polish content from hero-split.json (PL is
// default block language).
const DEFAULT_DATA: HeroSplitData = {
  sectionId: 'hero-split',
  label: 'Wykończenia wnętrz',
  title: 'Kompleksowe wykończenia wnętrz',
  description:
    'Prowadzimy cały proces wykończenia mieszkania lub domu, od projektu po przekazanie gotowych wnętrz. Ty oszczędzasz czas, a my dbamy o każdy detal.',
  primaryCTA: {
    label: 'Bezpłatna wycena',
    href: '#kontakt',
    hoverText: 'Umów termin',
  },
  secondaryCTA: {
    label: 'Zobacz realizacje',
    href: '#realizacje',
    hoverText: 'Zobacz naszą pracę',
  },
  stats: [
    { value: '150+', label: 'zrealizowanych\nprojektów' },
    { value: '10 lat', label: 'doświadczenie\nw branży' },
  ],
  trustBar: ['Umowa na piśmie', 'Przejrzyste koszty', 'Gwarancja wykonania'],
  images: ['/assets/placeholders/image-landscape.svg'],
  googleRating: { rating: 5.0, count: 120, label: 'opinii' },
  theme: 'light',
};

// Why: approximate copy of Button.astro classes (size md), because the test checks
// structured contract (presence of buttons, variants and hoverText) and not
// the full list of Tailwind classes from Atom. Full class compatibility is verified by the Astro build.
const BUTTON_BASE_CLASS =
  'ui-button ui-type-cta-label group inline-flex items-center justify-center gap-1.5 rounded-md whitespace-nowrap transition-all font-semibold focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-brand-primary/50';

function renderButton(cta: Cta, variantClass: string): string {
  return `<a href="${cta.href}" class="${BUTTON_BASE_CLASS} ${variantClass} h-10 sm:h-11 px-4 sm:px-5 text-sm sm:text-base [&_svg]:size-4.5">
    <span class="ui-button-text-wrap">
      <span class="ui-button-text-default">${cta.label}</span>
      <span class="ui-button-text-hover">${cta.hoverText ?? ''}</span>
    </span>
  </a>`;
}

function renderTrustItem(item: string, index: number, total: number, mutedClass: string): string {
  const divider =
    index < total - 1
      ? `<span class="ml-2 hidden md:inline lg:ml-3 text-brand-dark/20">•</span>`
      : '';
  return `<li class="inline-flex items-center gap-1 text-[11px] font-medium tracking-wide lg:gap-1.5 lg:text-xs ${mutedClass}">
    <svg class="size-3 shrink-0 text-success/70 lg:size-3.5 lg:text-success" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" aria-hidden="true">
      <path d="M20 6L9 17l-5-5" stroke-linecap="round" stroke-linejoin="round"/>
    </svg>
    ${item}
    ${divider}
  </li>`;
}

function renderStats(stats: Stat[]): string {
  const textClass = 'text-brand-dark';
  const mutedClass = 'text-brand-dark/60';
  return stats
    .map((stat, i) => {
      const labels = stat.label
        .split('\n')
        .map(
          (word) =>
            `<span class="hero-stat-label text-xs uppercase tracking-[0.15em] leading-tight ${mutedClass}">${word}</span>`
        )
        .join('');
      const separator =
        i < stats.length - 1 ? `<span class="ml-1 text-2xl font-light text-brand-dark/20">|</span>` : '';
      return `<div class="hero-stat flex items-center gap-3">
      <svg class="size-9 shrink-0 ${textClass}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true">
        <path d="M9 12.7498L11.25 14.9998L15 9.74985M12 2.71411C9.8495 4.75073 6.94563 5.99986 3.75 5.99986C3.69922 5.99986 3.64852 5.99955 3.59789 5.99892C3.2099 7.17903 3 8.43995 3 9.74991C3 15.3414 6.82432 20.0397 12 21.3719C17.1757 20.0397 21 15.3414 21 9.74991C21 8.43995 20.7901 7.17903 20.4021 5.99892C20.3515 5.99955 20.3008 5.99986 20.25 5.99986C17.0544 5.99986 14.1505 4.75073 12 2.71411Z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
      <div class="flex flex-col gap-1">
        <span class="hero-stat-value font-heading text-2xl font-bold leading-none ${textClass}">${stat.value}</span>
        ${labels}
      </div>
      ${separator}
    </div>`;
    })
    .join('');
}

function renderHeroSplitHtml(data: HeroSplitData): string {
  const {
    sectionId = 'hero-split',
    label = '',
    title,
    description,
    primaryCTA,
    secondaryCTA,
    stats = [],
    trustBar = [],
    trustBarVariant = 'split',
    images = [],
    googleRating,
    theme = 'light',
  } = data;

  const textClass = theme === 'dark' ? 'text-brand-light' : 'text-brand-dark';
  const mutedClass = theme === 'dark' ? 'text-brand-light/70' : 'text-brand-dark/70';

  const ratingHtml = googleRating
    ? `<div class="mb-4 inline-flex items-center gap-2 lg:mb-5 lg:gap-3">
      <svg class="size-5 shrink-0 lg:size-6" viewBox="0 0 24 24" fill="none" aria-hidden="true">
        <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92a5.06 5.06 0 01-2.2 3.32v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.1z" fill="#4285F4"/>
        <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853"/>
        <path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" fill="#FBBC05"/>
        <path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" fill="#EA4335"/>
      </svg>
      <div class="flex items-center gap-0.5 lg:gap-1">
        ${Array.from({ length: 5 }, () => '<svg class="size-3 lg:size-4" viewBox="0 0 24 24" fill="#F59E0B" aria-hidden="true"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg>').join('')}
      </div>
      <span class="text-sm font-bold lg:text-base ${textClass}">${googleRating.rating.toFixed(1)}</span>
      <span class="hidden text-xs font-medium sm:inline lg:text-sm ${mutedClass}">(${googleRating.count}+ ${googleRating.label})</span>
    </div>`
    : '';

  const midTrustHtml =
    trustBarVariant === 'mid' && trustBar.length > 0
      ? `<ul class="mb-6 flex list-none flex-col items-start gap-2">
      ${trustBar
        .map(
          (item) => `<li class="inline-flex items-center gap-1.5 text-xs font-medium tracking-wide ${mutedClass}">
        <svg class="size-3.5 shrink-0 text-success" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" aria-hidden="true">
          <path d="M20 6L9 17l-5-5" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
        ${item}
      </li>`
        )
        .join('')}
    </ul>`
      : '';

  const splitTrustHtml =
    trustBarVariant === 'split' && trustBar.length > 0
      ? `<ul class="mb-6 flex list-none flex-wrap items-center justify-center gap-x-3 gap-y-1 lg:mb-10 lg:gap-x-5 md:justify-start">
      ${trustBar.map((item, i) => renderTrustItem(item, i, trustBar.length, mutedClass)).join('')}
    </ul>`
      : '';

  const dotsHtml =
    images.length > 1
      ? `<div id="hero-dots" class="absolute bottom-5 left-1/2 -translate-x-1/2 z-20 flex items-center gap-1">
      ${images
        .map(
          (_, i) =>
            `<button type="button" data-hero-dot="${i}" style="min-height:0;min-width:0" class="rounded-full transition-all duration-500 cursor-pointer ${i === 0 ? 'bg-white w-2.5 h-2.5' : 'bg-white/50 hover:bg-white/70 w-2 h-2'}" aria-label="Zdjęcie ${i + 1}"></button>`
        )
        .join('')}
    </div>`
      : '';

  return `<section id="${sectionId}" class="ui-section ui-bg-base relative overflow-hidden rounded-t-[1.5rem] pt-0 pb-0">
    <div class="relative flex min-h-[70vh] lg:min-h-[calc(100dvh-var(--site-header-height))] items-center overflow-hidden rounded-t-[1.5rem]">
      <div class="absolute inset-0 overflow-hidden rounded-t-[1.5rem]">
        ${images.length > 0 ? `<img id="hero-slideshow" src="${images[0]}" alt="" class="absolute inset-0 size-full object-cover" loading="eager" decoding="async" fetchpriority="high" data-hero-images="${images.join(',')}">` : ''}
        <div class="absolute inset-0 ${theme === 'dark' ? 'hero-image-overlay-dark' : 'hero-image-overlay'}" aria-hidden="true"></div>
        ${dotsHtml}
      </div>
      <div class="relative z-10 w-full">
        <div class="ui-container">
          <div class="py-10 flex flex-col items-center gap-1 text-center md:items-start md:py-16 md:text-left">
            <span class="block text-[10px] uppercase tracking-[0.25em] text-brand-primary">${label}</span>
            ${ratingHtml}
            <h1 class="font-heading font-bold ui-type-heading-hero mb-6 max-w-2xl ${textClass}">${title.replace(/\n/g, ' ')}</h1>
            <p class="leading-relaxed ui-type-lead mb-6 max-w-lg ${mutedClass}">${description}</p>
            ${midTrustHtml}
            <div class="mb-6 flex flex-wrap justify-center gap-4 md:justify-start">
              ${renderButton(primaryCTA, 'ui-button-primary')}
              ${renderButton(secondaryCTA, 'ui-button-outline')}
            </div>
            ${splitTrustHtml}
            ${stats.length > 0 ? `<div class="hero-stats mb-10 hidden flex-wrap items-center justify-center gap-x-6 gap-y-3 lg:flex md:justify-start">
              ${renderStats(stats)}
            </div>` : ''}
          </div>
        </div>
      </div>
    </div>
  </section>`;
}

describe('HeroSplitBlock, kontrakt renderowania', () => {
  it('renderuje <section> z ui-section, ui-bg-base i id', () => {
    const $ = cheerio.load(renderHeroSplitHtml(DEFAULT_DATA));
    expect($('section').length).toBe(1);
    expect($('section').hasClass('ui-section')).toBe(true);
    expect($('section').hasClass('ui-bg-base')).toBe(true);
    expect($('section').hasClass('relative')).toBe(true);
    expect($('section').hasClass('overflow-hidden')).toBe(true);
    expect($('section').attr('id')).toBe('hero-split');
  });

  it('zawiera .ui-container z treścią nad tłem (z-10)', () => {
    const $ = cheerio.load(renderHeroSplitHtml(DEFAULT_DATA));
    expect($('.ui-container').length).toBe(1);
    expect($('.ui-container').parent().hasClass('z-10')).toBe(true);
  });

  describe('tytuł i etykieta', () => {
    it('renderuje dokładnie jeden h1', () => {
      const $ = cheerio.load(renderHeroSplitHtml(DEFAULT_DATA));
      expect($('h1').length).toBe(1);
    });

    it('h1 ma klasę ui-type-heading-hero i text-brand-dark', () => {
      const $ = cheerio.load(renderHeroSplitHtml(DEFAULT_DATA));
      const h1 = $('h1');
      expect(h1.hasClass('ui-type-heading-hero')).toBe(true);
      expect(h1.hasClass('text-brand-dark')).toBe(true);
      expect(h1.hasClass('max-w-2xl')).toBe(true);
    });

    it('h1 zawiera pełny tekst tytułu', () => {
      const $ = cheerio.load(renderHeroSplitHtml(DEFAULT_DATA));
      expect($('h1').text()).toBe('Kompleksowe wykończenia wnętrz');
    });

    it('label/eyebrow to span z text-brand-primary i uppercase', () => {
      const $ = cheerio.load(renderHeroSplitHtml(DEFAULT_DATA));
      const labelSpan = $('span.text-brand-primary');
      expect(labelSpan.length).toBe(1);
      expect(labelSpan.hasClass('uppercase')).toBe(true);
      expect(labelSpan.text()).toBe('Wykończenia wnętrz');
    });

    it('opis renderuje się z text-brand-dark/70', () => {
      const $ = cheerio.load(renderHeroSplitHtml(DEFAULT_DATA));
      const desc = $('p');
      expect(desc.hasClass('text-brand-dark/70')).toBe(true);
      expect(desc.text()).toContain('Prowadzimy cały proces wykończenia');
    });
  });

  describe('przyciski CTA', () => {
    it('renderuje dokładnie 2 przyciski a.ui-button', () => {
      const $ = cheerio.load(renderHeroSplitHtml(DEFAULT_DATA));
      expect($('a.ui-button').length).toBe(2);
    });

    it('pierwszy przycisk jest primary, drugi outline', () => {
      const $ = cheerio.load(renderHeroSplitHtml(DEFAULT_DATA));
      const buttons = $('a.ui-button');
      expect(buttons.eq(0).hasClass('ui-button-primary')).toBe(true);
      expect(buttons.eq(1).hasClass('ui-button-outline')).toBe(true);
    });

    it('przyciski wskazują na kotwice z danych', () => {
      const $ = cheerio.load(renderHeroSplitHtml(DEFAULT_DATA));
      expect($('a.ui-button').eq(0).attr('href')).toBe('#kontakt');
      expect($('a.ui-button').eq(1).attr('href')).toBe('#realizacje');
    });

    it('przyciski mają hoverText w .ui-button-text-hover', () => {
      const $ = cheerio.load(renderHeroSplitHtml(DEFAULT_DATA));
      const hovers = $('.ui-button-text-hover');
      expect(hovers.length).toBe(2);
      expect(hovers.eq(0).text()).toBe('Umów termin');
      expect(hovers.eq(1).text()).toBe('Zobacz naszą pracę');
    });
  });

  describe('statystyki', () => {
    it('renderuje dokładnie 2 bloki .hero-stat', () => {
      const $ = cheerio.load(renderHeroSplitHtml(DEFAULT_DATA));
      expect($('.hero-stat').length).toBe(2);
    });

    it('kontener statystyk jest ukryty na mobile (hidden lg:flex)', () => {
      const $ = cheerio.load(renderHeroSplitHtml(DEFAULT_DATA));
      expect($('.hero-stats').hasClass('hidden')).toBe(true);
      expect($('.hero-stats').hasClass('lg:flex')).toBe(true);
    });

    it('pierwsza statystyka ma wartość 150+ i dwie etykiety (łamanie nowej linii)', () => {
      const $ = cheerio.load(renderHeroSplitHtml(DEFAULT_DATA));
      const firstStat = $('.hero-stat').first();
      expect(firstStat.find('.hero-stat-value').text()).toBe('150+');
      const labels = firstStat.find('.hero-stat-label');
      expect(labels.length).toBe(2);
      expect(labels.eq(0).text()).toBe('zrealizowanych');
      expect(labels.eq(1).text()).toBe('projektów');
      expect(labels.eq(0).hasClass('uppercase')).toBe(true);
    });

    it('druga statystyka ma wartość 10 lat', () => {
      const $ = cheerio.load(renderHeroSplitHtml(DEFAULT_DATA));
      expect($('.hero-stat').eq(1).find('.hero-stat-value').text()).toBe('10 lat');
    });

    it('między statystykami jest separator |', () => {
      const $ = cheerio.load(renderHeroSplitHtml(DEFAULT_DATA));
      expect($('.hero-stat').eq(0).find('span').filter((_, el) => $(el).text() === '|').length).toBe(1);
    });
  });

  describe('trust bar (wariant split)', () => {
    it('renderuje ul z 3 pozycjami li', () => {
      const $ = cheerio.load(renderHeroSplitHtml(DEFAULT_DATA));
      const ul = $('ul.list-none');
      expect(ul.length).toBe(1);
      expect(ul.find('li').length).toBe(3);
    });

    it('każda pozycja ma zielony znacznik (svg checkmark)', () => {
      const $ = cheerio.load(renderHeroSplitHtml(DEFAULT_DATA));
      $('ul.list-none li').each((_, el) => {
        expect($(el).find('svg').length).toBe(1);
      });
    });

    it('pozycje mają tekst z danych', () => {
      const $ = cheerio.load(renderHeroSplitHtml(DEFAULT_DATA));
      const lis = $('ul.list-none li');
      expect(lis.eq(0).text()).toContain('Umowa na piśmie');
      expect(lis.eq(1).text()).toContain('Przejrzyste koszty');
      expect(lis.eq(2).text()).toContain('Gwarancja wykonania');
    });

    it('między pozycjami jest separator kropki •', () => {
      const $ = cheerio.load(renderHeroSplitHtml(DEFAULT_DATA));
      expect($('ul.list-none li span').filter((_, el) => $(el).text() === '•').length).toBe(2);
    });
  });

  describe('tło i slideshow', () => {
    it('renderuje img tła z id hero-slideshow i placeholderem', () => {
      const $ = cheerio.load(renderHeroSplitHtml(DEFAULT_DATA));
      const img = $('#hero-slideshow');
      expect(img.length).toBe(1);
      expect(img.attr('src')).toBe('/assets/placeholders/image-landscape.svg');
      expect(img.attr('alt')).toBe('');
    });

    it('img tła ma loading="eager" i fetchpriority="high" (LCP)', () => {
      const $ = cheerio.load(renderHeroSplitHtml(DEFAULT_DATA));
      const img = $('#hero-slideshow');
      expect(img.attr('loading')).toBe('eager');
      expect(img.attr('fetchpriority')).toBe('high');
    });

    it('img tła ma data-hero-images z listą slajdów', () => {
      const $ = cheerio.load(renderHeroSplitHtml(DEFAULT_DATA));
      expect($('#hero-slideshow').attr('data-hero-images')).toBe('/assets/placeholders/image-landscape.svg');
    });

    it('zawiera overlay gradient (hero-image-overlay) z aria-hidden', () => {
      const $ = cheerio.load(renderHeroSplitHtml(DEFAULT_DATA));
      const overlay = $('.hero-image-overlay');
      expect(overlay.length).toBe(1);
      expect(overlay.attr('aria-hidden')).toBe('true');
    });

    it('przy jednym zdjęciu nie ma kropek slideshow', () => {
      const $ = cheerio.load(renderHeroSplitHtml(DEFAULT_DATA));
      expect($('#hero-dots').length).toBe(0);
    });

    it('przy dwóch zdjęciach pojawia się #hero-dots z 2 kropkami', () => {
      const multiData: HeroSplitData = {
        ...DEFAULT_DATA,
        images: [
          '/assets/placeholders/image-landscape.svg',
          '/assets/placeholders/image-square.svg',
        ],
      };
      const $ = cheerio.load(renderHeroSplitHtml(multiData));
      const dots = $('#hero-dots');
      expect(dots.length).toBe(1);
      expect(dots.find('button[data-hero-dot]').length).toBe(2);
    });
  });

  describe('Google rating', () => {
    it('renderuje 5 gwiazdek (inline SVG, nie ikony Phosphor)', () => {
      const $ = cheerio.load(renderHeroSplitHtml(DEFAULT_DATA));
      expect($('svg[fill="#F59E0B"]').length).toBe(5);
      expect($('.ph').length).toBe(0);
    });

    it('pokazuje ocenę 5.0 i liczbę opinii', () => {
      const $ = cheerio.load(renderHeroSplitHtml(DEFAULT_DATA));
      expect($('span').filter((_, el) => $(el).text() === '5.0').length).toBe(1);
      expect($('span').filter((_, el) => $(el).text() === '(120+ opinii)').length).toBe(1);
    });
  });

  it('nie zawiera href="#"', () => {
    const html = renderHeroSplitHtml(DEFAULT_DATA);
    expect(html).not.toContain('href="#"');
  });
});
