import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';

// Why: The contract test reflects the HTML structure generated by
// MarqueeImageWallBlock to detect regressions in bare-metal rendering
// full build. Pattern: hero-contract.test.ts.

interface MarqueeWallImage {
  src?: string;
  thumb?: string;
  alt?: string;
}

interface MarqueeWallData {
  sectionId?: string;
  title?: string;
  description?: string;
  images?: MarqueeWallImage[];
  wallLabel?: string;
  wallEmptyState?: string;
  headingTag?: string;
}

const DEFAULT_IMAGES: MarqueeWallImage[] = [
  { src: '/assets/images/realizacja-1.webp', thumb: '/assets/images/realizacja-1@220.webp', alt: 'Realizacja pierwsza' },
  { src: '/assets/images/realizacja-2.webp', thumb: '/assets/images/realizacja-2@220.webp', alt: 'Realizacja druga' },
  { src: '/assets/images/realizacja-3.webp', thumb: '/assets/images/realizacja-3@220.webp', alt: 'Realizacja trzecia' },
];

// Dlaczego: renderujemy statyczny HTML 1:1 z komponentu, bez importowania Astro
// in vitest, because .astro components require the Astro compiler.
function renderMarqueeWallHtml(data: MarqueeWallData): string {
  const {
    sectionId = 'galeria',
    title = '',
    description = '',
    images: rawImages = [],
    wallLabel = 'Nasze realizacje',
    wallEmptyState = 'Brak zdjęć do wyświetlenia.',
    headingTag = 'h2',
  } = data;

  const images = Array.isArray(rawImages) ? rawImages.filter((image) => image?.src) : [];

  const preloadHtml = images
    .slice(0, 6)
    .map((image) => `<link rel="preload" as="image" href="${image.thumb || image.src}" />`)
    .join('');

  const headerHtml = `
    <div class="space-y-4">
      <span class="ui-type-accent-label block">${wallLabel}</span>
      <${headingTag} class="font-heading font-bold ui-type-section-title">${title}</${headingTag}>
      <p class="ui-type-body">${description}</p>
    </div>`;

  const cardHtml = (image: MarqueeWallImage, width: string, aspect: string) => `
    <div class="group relative ${width} shrink-0 cursor-zoom-in overflow-hidden border border-outline-variant bg-surface-dim transition-colors duration-300 hover:border-primary ${aspect}" data-lightbox data-href="${image.src}" data-title="${image.alt || ''}">
      <img src="${image.src}" alt="${image.alt || ''}" class="absolute inset-0 h-full w-full object-cover transition-transform duration-700 ease-out group-hover:scale-105" />
      <span class="absolute bottom-3 left-3 font-heading text-sm font-bold uppercase tracking-[0.2em] text-white">#${images.indexOf(image) + 1}</span>
    </div>`;

  const rowHtml = (width: string, aspect: string) => `
    <div class="relative z-10 overflow-hidden py-1">
      <div style="mask-image: linear-gradient(to right, transparent 0%, black 8%, black 92%, transparent 100%);">
        <div class="flex gap-3 md:gap-4">
          ${images.map((image) => cardHtml(image, width, aspect)).join('')}
        </div>
      </div>
    </div>`;

  const wallHtml = images.length > 0
    ? `<div class="relative isolate mt-10 space-y-4 md:space-y-5">
        <div class="md:hidden">
          ${rowHtml('w-[150px]', 'aspect-[3/4]')}
          ${rowHtml('w-[170px]', 'aspect-[4/5]')}
          ${rowHtml('w-[140px]', 'aspect-[3/4]')}
        </div>
        <div class="hidden md:block">
          ${rowHtml('w-[200px] md:w-[260px]', 'aspect-[3/4]')}
          ${rowHtml('w-[220px] md:w-[300px]', 'aspect-[4/5]')}
          ${rowHtml('w-[180px] md:w-[240px]', 'aspect-[3/4]')}
        </div>
      </div>`
    : `<div class="mt-10 rounded-md border border-outline-variant bg-surface-dim py-20 text-center">
        <p class="ui-type-body">${wallEmptyState}</p>
      </div>`;

  return `<section id="${sectionId}" class="ui-section ui-bg-page">
    ${preloadHtml}
    <div class="ui-container">
      ${headerHtml}
    </div>
    ${wallHtml}
  </section>`;
}

describe('MarqueeImageWall, kontrakt renderowania', () => {
  const defaultData: MarqueeWallData = {
    title: 'Nasze realizacje',
    description: 'Zobacz efekty naszej pracy.',
    images: DEFAULT_IMAGES,
    wallLabel: 'Zobacz efekty',
  };

  it('renderuje <section> z ui-section i id', () => {
    const $ = cheerio.load(renderMarqueeWallHtml(defaultData));
    expect($('section').length).toBe(1);
    expect($('section').hasClass('ui-section')).toBe(true);
    expect($('section').attr('id')).toBe('galeria');
  });

  it('renderuje wallLabel jako .ui-type-accent-label', () => {
    const $ = cheerio.load(renderMarqueeWallHtml(defaultData));
    expect($('.ui-type-accent-label').length).toBe(1);
    expect($('.ui-type-accent-label').text()).toBe('Zobacz efekty');
  });

  it('renderuje tytuł w nagłówku', () => {
    const $ = cheerio.load(renderMarqueeWallHtml(defaultData));
    expect($('h2').text()).toContain('Nasze realizacje');
  });

  it('renderuje opis', () => {
    const $ = cheerio.load(renderMarqueeWallHtml(defaultData));
    expect($('p').first().text()).toContain('Zobacz efekty naszej pracy.');
  });

  it('renderuje karty z data-lightbox i src', () => {
    const $ = cheerio.load(renderMarqueeWallHtml(defaultData));
    expect($('[data-lightbox]').length).toBeGreaterThan(0);
    expect($('[data-lightbox]').first().attr('data-href')).toBe('/assets/images/realizacja-1.webp');
  });

  it('nie dodaje starej klasy marquee-wall ani inline animation', () => {
    const $ = cheerio.load(renderMarqueeWallHtml(defaultData));
    expect($('.marquee-wall').length).toBe(0);
    const hasAnimationStyle = $('[style]').toArray().some((el) => (el.attribs.style || '').includes('animation'));
    expect(hasAnimationStyle).toBe(false);
  });

  it('renderuje preload linki dla pierwszych zdjęć', () => {
    const $ = cheerio.load(renderMarqueeWallHtml(defaultData));
    expect($('link[rel="preload"][as="image"]').length).toBe(3);
  });

  describe('stan pusty', () => {
    it('renderuje wallEmptyState gdy brak images', () => {
      const $ = cheerio.load(renderMarqueeWallHtml({ ...defaultData, images: [] }));
      expect($('p').text()).toContain('Brak zdjęć do wyświetlenia.');
    });

    it('nie renderuje wallEmptyState gdy są obrazy', () => {
      const $ = cheerio.load(renderMarqueeWallHtml(defaultData));
      expect($('p').text()).not.toContain('Brak zdjęć do wyświetlenia.');
    });
  });

  describe('hierarchia nagłówków', () => {
    it('domyślnie używa h2', () => {
      const $ = cheerio.load(renderMarqueeWallHtml(defaultData));
      expect($('h2').length).toBe(1);
      expect($('h1').length).toBe(0);
    });

    it('używa h1 gdy headingTag = h1 (podstrony)', () => {
      const $ = cheerio.load(renderMarqueeWallHtml({ ...defaultData, headingTag: 'h1' }));
      expect($('h1').length).toBe(1);
      expect($('h2').length).toBe(0);
    });
  });
});
