import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';

// Why: The contract test reflects the HTML structure generated by
// OnlineAdviceBlock to detect regressions in bare-metal rendering
// full build. Pattern: cross-border-contract.test.ts.

interface StepItem {
  title: string;
  description: string;
}

interface OnlineAdviceData {
  sectionId?: string;
  lang?: 'pl' | 'en';
  title?: string;
  lead?: string;
  steps?: StepItem[];
}

// Why: Test data reflects the default JSON section (pl) to test
// they covered the real content of the library, not artificial plugs.
const DEFAULT_STEPS: StepItem[] = [
  { title: 'Opisz sprawę', description: 'Opisz dokładnie swoją sprawę w formularzu.' },
  { title: 'Wycena', description: 'Na podstawie opisu przygotowujemy bezpłatną wycenę.' },
  { title: 'Realizacja', description: 'Realizujemy usługę zdalnie, telefonicznie lub przez wideokonferencję.' },
];

// Dlaczego: ikony Phosphor przypisane krokom, jak w komponencie (pencil,
// calculator, check-circle). Missing icons have been added to phosphor-min.css
// with codepoints from selection.json, so the block is a faithful copy of the original.
const STEP_ICONS = ['pencil', 'calculator', 'check-circle'];

// Dlaczego: renderOnlineAdviceHtml odtwarza HTML wygenerowany przez blok wraz
// with form wrapper (form-card + form). ContactForm is a molecule with its own
// logic, so the contract test only checks the presence of the form container, not its fields.
function renderOnlineAdviceHtml(data: OnlineAdviceData): string {
  const {
    sectionId = 'porady-online',
    title = 'Porady online',
    lead = 'Opisz swoją sprawę w formularzu poniżej.',
    steps = DEFAULT_STEPS,
  } = data;

  const stepsHtml = steps
    .map(
      (step, i) => `
      <div class="step-card rounded-2xl border border-brand-dark/10 bg-white p-6 transition-all duration-300 hover:border-brand-primary/60 hover:shadow-[0_0_30px_color-mix(in_oklab,var(--color-brand-primary)_20%,transparent)]">
        <div class="mb-5 flex size-14 items-center justify-center rounded-xl bg-brand-primary text-2xl text-brand-dark">
          <i class="ph ph-${STEP_ICONS[i % STEP_ICONS.length]}"></i>
        </div>
        <h3 class="font-heading font-bold ui-type-feature-title mb-2 text-xl text-brand-dark">${step.title}</h3>
        <p class="leading-relaxed ui-type-text-feature-sm text-brand-dark/70">${step.description}</p>
      </div>`
    )
    .join('');

  return `<section id="${sectionId}" class="ui-section ui-bg-page relative overflow-hidden" style="padding-top:clamp(7rem,12vw,10rem)">
    <div class="pointer-events-none absolute top-0 right-0 h-96 w-96 max-w-full" style="background:radial-gradient(ellipse 60% 60% at 100% 0%, color-mix(in oklab, var(--color-brand-primary) 12%, transparent) 0%, transparent 60%)"></div>
    <div class="ui-container">
      <div class="mx-auto mb-16 max-w-3xl text-center">
        <h2 class="font-heading font-bold ui-type-section-title mb-4 text-brand-dark" data-motion="fade">${title}</h2>
        <p class="leading-relaxed ui-type-lead mx-auto max-w-2xl text-brand-dark/70" data-motion="fade">${lead}</p>
      </div>
      <div class="mb-12">
        <div class="mx-auto mb-12 w-3/4 border-t border-brand-dark/10"></div>
        <div class="grid gap-6 md:grid-cols-3">
          ${stepsHtml}
        </div>
      </div>
      <div class="mx-auto mb-14 w-3/4 border-t border-brand-dark/10"></div>
      <div class="form-card mx-auto max-w-2xl rounded-2xl border border-brand-dark/10 bg-white p-6 sm:p-8" data-motion="fade">
        <form id="oa" data-contact-form></form>
      </div>
    </div>
  </section>`;
}

describe('OnlineAdvice, kontrakt renderowania', () => {
  const defaultData: OnlineAdviceData = {
    lang: 'pl',
    title: 'Porady online',
    lead: 'Opisz swoją sprawę w formularzu poniżej.',
    steps: DEFAULT_STEPS,
  };

  it('renderuje <section> z ui-section, ui-bg-page i id', () => {
    const $ = cheerio.load(renderOnlineAdviceHtml(defaultData));
    expect($('section').length).toBe(1);
    expect($('section').hasClass('ui-section')).toBe(true);
    expect($('section').hasClass('ui-bg-page')).toBe(true);
    expect($('section').attr('id')).toBe('porady-online');
  });

  it('section ma padding-top clamp z oryginału', () => {
    const $ = cheerio.load(renderOnlineAdviceHtml(defaultData));
    expect($('section').attr('style')).toContain('padding-top:clamp(7rem,12vw,10rem)');
  });

  it('zawiera .ui-container i gradient orb z brand-primary', () => {
    const $ = cheerio.load(renderOnlineAdviceHtml(defaultData));
    expect($('.ui-container').length).toBe(1);
    const orb = $('[style*="radial-gradient"]');
    expect(orb.length).toBe(1);
    expect(orb.attr('style')).toContain('var(--color-brand-primary)');
  });

  it('nie zawiera klienckich klas reveal (auto-reveal-item, reveal-group, data-reveal-on-load)', () => {
    const html = renderOnlineAdviceHtml(defaultData);
    expect(html).not.toContain('auto-reveal-item');
    expect(html).not.toContain('reveal-group');
    expect(html).not.toContain('data-reveal-on-load');
  });

  it('używa data-motion="fade" zamiast klienckiego reveal', () => {
    const $ = cheerio.load(renderOnlineAdviceHtml(defaultData));
    expect($('[data-motion="fade"]').length).toBe(3);
    expect($('h2').attr('data-motion')).toBe('fade');
  });

  describe('nagłówek sekcji', () => {
    it('renderuje h2 z tytułem, ui-type-section-title i kolorem brand-dark', () => {
      const $ = cheerio.load(renderOnlineAdviceHtml(defaultData));
      const h2 = $('h2');
      expect(h2.text()).toBe('Porady online');
      expect(h2.hasClass('text-brand-dark')).toBe(true);
      expect(h2.hasClass('ui-type-section-title')).toBe(true);
    });

    it('renderuje lead w kolorze brand-dark/70', () => {
      const $ = cheerio.load(renderOnlineAdviceHtml(defaultData));
      const lead = $('.ui-type-lead');
      expect(lead.length).toBe(1);
      expect(lead.hasClass('text-brand-dark/70')).toBe(true);
    });

    it('dla lang=en renderuje angielski tytuł', () => {
      const $ = cheerio.load(renderOnlineAdviceHtml({ ...defaultData, lang: 'en', title: 'Online Advice' }));
      expect($('h2').text()).toBe('Online Advice');
    });
  });

  describe('kroki', () => {
    it('renderuje dokładnie 3 karty kroków (step-card)', () => {
      const $ = cheerio.load(renderOnlineAdviceHtml(defaultData));
      expect($('.step-card').length).toBe(3);
    });

    it('karty kroków mają tło bg-white i ramkę border-brand-dark/10', () => {
      const $ = cheerio.load(renderOnlineAdviceHtml(defaultData));
      $('.step-card').each((_, el) => {
        expect($(el).hasClass('bg-white')).toBe(true);
        expect($(el).hasClass('border-brand-dark/10')).toBe(true);
      });
    });

    it('karty kroków mają hover glow z brand-primary', () => {
      const $ = cheerio.load(renderOnlineAdviceHtml(defaultData));
      $('.step-card').each((_, el) => {
        expect($(el).hasClass('hover:border-brand-primary/60')).toBe(true);
        expect($(el).attr('class')).toContain('hover:shadow-[0_0_30px_color-mix');
      });
    });

    it('każdy krok ma ikonę w kwadracie size-14 bg-brand-primary', () => {
      const $ = cheerio.load(renderOnlineAdviceHtml(defaultData));
      $('.step-card').each((_, el) => {
        const box = $(el).find('.size-14');
        expect(box.length).toBe(1);
        expect(box.hasClass('bg-brand-primary')).toBe(true);
        expect($(box).find('i.ph').length).toBe(1);
      });
    });

    it('kroki używają ikon pencil, calculator, check-circle', () => {
      const $ = cheerio.load(renderOnlineAdviceHtml(defaultData));
      expect($('i.ph-pencil').length).toBe(1);
      expect($('i.ph-calculator').length).toBe(1);
      expect($('i.ph-check-circle').length).toBe(1);
    });

    it('grid kroków jest mobile-first (grid gap-6 md:grid-cols-3)', () => {
      const $ = cheerio.load(renderOnlineAdviceHtml(defaultData));
      const grid = $('.md\\:grid-cols-3');
      expect(grid.length).toBe(1);
      expect(grid.hasClass('grid')).toBe(true);
      expect(grid.hasClass('gap-6')).toBe(true);
    });

    it('każdy krok ma h3 z tytułem i p z opisem', () => {
      const $ = cheerio.load(renderOnlineAdviceHtml(defaultData));
      $('.step-card').each((_, el) => {
        expect($(el).find('h3').length).toBe(1);
        expect($(el).find('p').length).toBe(1);
      });
      expect($('.step-card').first().find('h3').text()).toBe('Opisz sprawę');
    });
  });

  describe('linie oddzielające', () => {
    it('renderuje 2 linie border-t (przed krokami i przed formularzem)', () => {
      const $ = cheerio.load(renderOnlineAdviceHtml(defaultData));
      expect($('.border-t').length).toBe(2);
      $('.border-t').each((_, el) => {
        expect($(el).hasClass('border-brand-dark/10')).toBe(true);
        expect($(el).hasClass('w-3/4')).toBe(true);
      });
    });
  });

  describe('formularz', () => {
    it('renderuje kartę formularza .form-card z max-w-2xl', () => {
      const $ = cheerio.load(renderOnlineAdviceHtml(defaultData));
      const card = $('.form-card');
      expect(card.length).toBe(1);
      expect(card.hasClass('max-w-2xl')).toBe(true);
      expect(card.hasClass('mx-auto')).toBe(true);
    });

    it('form-card ma tło bg-white, ramkę brand-dark/10 i padding', () => {
      const $ = cheerio.load(renderOnlineAdviceHtml(defaultData));
      const card = $('.form-card');
      expect(card.hasClass('bg-white')).toBe(true);
      expect(card.hasClass('border-brand-dark/10')).toBe(true);
      expect(card.hasClass('p-6')).toBe(true);
    });

    it('wrapper formularza zawiera form z id "oa"', () => {
      const $ = cheerio.load(renderOnlineAdviceHtml(defaultData));
      expect($('.form-card form#oa').length).toBe(1);
    });

    it('form ma atrybut data-contact-form (kontrakt ContactForm)', () => {
      const $ = cheerio.load(renderOnlineAdviceHtml(defaultData));
      expect($('form[data-contact-form]').length).toBe(1);
    });
  });

  it('nie zawiera href="#"', () => {
    const html = renderOnlineAdviceHtml(defaultData);
    expect(html).not.toContain('href="#"');
  });
});
