import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';

// Why: The contract test reflects the HTML structure generated by
// ProcessIconStepsBlock, sekcja "PROCES":
// heading "How we work" + grid of 4 steps with icons and dashed arrows),
// to detect regressions in rendering without running a full build.
// Wzorzec: about-law-contract.test.ts.
//
// Technical note: we don't use renderToString with astro/container because vitest
// w starter-kicie nie ma zainstalowanego vite-plugin-astro (konfiguracja
// test only defines aliases) and therefore does not parse .astro files.
// So all contract tests in the repo build the expected HTML manually.

type Step = {
  num: number;
  title: string;
  description: string;
  icon: 'diagnose' | 'plan' | 'implement' | 'monitor';
};

interface ProcessData {
  sectionId?: string;
  heading?: string;
  steps?: Step[];
}

// Why: icon pathy 1:1 with ICON_PATHS in the component so that the test controls
// also what goes into set:html (security: closed const only).
const ICON_PATHS: Record<Step['icon'], string> = {
  diagnose:
    '<path d="M3 7V5a2 2 0 0 1 2-2h2"/><path d="M17 3h2a2 2 0 0 1 2 2v2"/><path d="M21 17v2a2 2 0 0 1-2 2h-2"/><path d="M7 21H5a2 2 0 0 1-2-2v-2"/><circle cx="12" cy="12" r="3"/><path d="m16 16-1.9-1.9"/>',
  plan: '<circle cx="6" cy="19" r="3"/><path d="M9 19h8.5a3.5 3.5 0 0 0 0-7h-11a3.5 3.5 0 0 1 0-7H15"/><circle cx="18" cy="5" r="3"/>',
  implement:
    '<path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"/><circle cx="12" cy="12" r="3"/>',
  monitor: '<path d="M3 3v18h18"/><path d="M18 17V9"/><path d="M13 17V5"/><path d="M8 17v-3"/>',
};

const DEFAULT_STEPS: Step[] = [
  { num: 1, title: 'Diagnoza', description: 'Analizujemy aktualny stan i identyfikujemy obszary wymagające poprawy.', icon: 'diagnose' },
  { num: 2, title: 'Plan', description: 'Przygotowujemy konkretny plan działania z priorytetami i celami.', icon: 'plan' },
  { num: 3, title: 'Wdrożenie', description: 'Realizujemy plan krok po kroku, angażując zespół.', icon: 'implement' },
  { num: 4, title: 'Monitoring', description: 'Śledzimy wyniki i korygujemy działania.', icon: 'monitor' },
];

const DEFAULT_DATA: ProcessData = {
  sectionId: 'proces',
  heading: 'Jak pracujemy',
  steps: DEFAULT_STEPS,
};

// Dlaczego: budujemy HTML identycznie jak komponent: sekcja tone="page"
// z border-t (token border-brand-dark/10 zamiast klienckiego border-outline/70),
// header + dash brand, grid 4 columns, arrows only for steps 1-3,
// ikony inline SVG (stroke-width 1.65 jak kliencki LcIcon + .lc-icon),
// step number with leading zero (01.) in brand-accent color.
function renderProcessHtml(data: ProcessData): string {
  const { sectionId = 'proces', heading = 'Jak pracujemy', steps = DEFAULT_STEPS } = data;

  const stepsHtml = steps
    .map((step, i) => {
      const arrow = i < steps.length - 1
        ? `
          <div class="pointer-events-none absolute right-0 top-8 z-10 hidden w-8 -translate-y-1/2 items-center lg:flex">
            <span class="h-0 w-full border-t-2 border-dashed border-brand-primary/40"></span>
            <svg class="absolute -right-1 top-1/2 h-4 w-4 -translate-y-1/2 text-brand-primary" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m9 18 6-6-6-6"></path></svg>
          </div>`
        : '';
      const num = String(step.num).padStart(2, '0');
      return `
        <article class="relative text-center">
          ${arrow}
          <svg class="mx-auto block h-16 w-16 text-brand-primary" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${ICON_PATHS[step.icon]}</svg>
          <h3 class="font-heading font-bold ui-type-feature-title mt-6 !font-extrabold"><span class="text-brand-accent">${num}.</span> ${step.title}</h3>
          <p class="leading-relaxed ui-type-text-feature-sm mt-3 !font-semibold leading-7">${step.description}</p>
        </article>`;
    })
    .join('');

  return `<section id="${sectionId}" class="ui-section ui-bg-page border-t border-brand-dark/10">
    <div class="ui-container">
      <div class="mx-auto max-w-4xl text-center">
        <h2 class="font-heading font-bold ui-type-heading-section-lg !font-extrabold">${heading}</h2>
        <div class="mx-auto mt-5 h-0.5 w-14 bg-brand-primary" aria-hidden="true"></div>
      </div>
      <div class="mt-14 grid gap-10 lg:grid-cols-4 lg:gap-8">
        ${stepsHtml}
      </div>
    </div>
  </section>`;
}

describe('ProcessIconStepsBlock, kontrakt renderowania', () => {
  it('renderuje <section> z ui-section, tone page, id i border-t', () => {
    const $ = cheerio.load(renderProcessHtml(DEFAULT_DATA));
    expect($('section').length).toBe(1);
    expect($('section').hasClass('ui-section')).toBe(true);
    expect($('section').hasClass('ui-bg-page')).toBe(true);
    expect($('section').attr('id')).toBe('proces');
    expect($('section').hasClass('border-t')).toBe(true);
    expect($('section').hasClass('border-brand-dark/10')).toBe(true);
  });

  it('zawiera .ui-container', () => {
    const $ = cheerio.load(renderProcessHtml(DEFAULT_DATA));
    expect($('.ui-container').length).toBe(1);
  });

  describe('nagłówek', () => {
    it('renderuje wycentrowany h2 z tytułem sekcji', () => {
      const $ = cheerio.load(renderProcessHtml(DEFAULT_DATA));
      expect($('h2').length).toBe(1);
      expect($('h2').text()).toContain('Jak pracujemy');
      expect($('h2').hasClass('ui-type-heading-section-lg')).toBe(true);
      expect($('h2').parent().hasClass('text-center')).toBe(true);
    });

    it('renderuje widoczną kreskę brand pod nagłówkiem (bez hidden)', () => {
      const $ = cheerio.load(renderProcessHtml(DEFAULT_DATA));
      // Why: class h-0.5 contains a dot, so you need it in the selector
      // escape (h-0\.5), otherwise css-select parses ".5" as a number.
      const rule = $('.mx-auto.mt-5.h-0\\.5.w-14');
      expect(rule.length).toBe(1);
      expect(rule.hasClass('bg-brand-primary')).toBe(true);
      expect(rule.hasClass('hidden')).toBe(false);
    });
  });

  describe('grid kroków', () => {
    it('grid jest mobile-first z 4 kolumnami na desktopie', () => {
      const $ = cheerio.load(renderProcessHtml(DEFAULT_DATA));
      const grid = $('.mt-14.grid');
      expect(grid.hasClass('gap-10')).toBe(true);
      expect(grid.hasClass('lg:grid-cols-4')).toBe(true);
      expect(grid.hasClass('lg:gap-8')).toBe(true);
    });

    it('renderuje dokładnie 4 artykuły kroków', () => {
      const $ = cheerio.load(renderProcessHtml(DEFAULT_DATA));
      expect($('article.relative.text-center').length).toBe(4);
    });

    it('renderuje numery kroków 01., 02., 03., 04. z tokenem brand-accent', () => {
      const $ = cheerio.load(renderProcessHtml(DEFAULT_DATA));
      const nums = $('article h3 span.text-brand-accent');
      expect(nums.length).toBe(4);
      expect(nums.eq(0).text()).toBe('01.');
      expect(nums.eq(1).text()).toBe('02.');
      expect(nums.eq(2).text()).toBe('03.');
      expect(nums.eq(3).text()).toBe('04.');
    });

    it('każdy krok ma tytuł h3 (feature-title, extrabold) i opis (feature-body-sm)', () => {
      const $ = cheerio.load(renderProcessHtml(DEFAULT_DATA));
      const titles = $('article h3');
      expect(titles.length).toBe(4);
      titles.each((_, el) => {
        expect($(el).hasClass('ui-type-feature-title')).toBe(true);
        expect($(el).hasClass('!font-extrabold')).toBe(true);
      });
      const bodies = $('article p');
      expect(bodies.length).toBe(4);
      bodies.each((_, el) => {
        expect($(el).hasClass('ui-type-text-feature-sm')).toBe(true);
        expect($(el).hasClass('!font-semibold')).toBe(true);
      });
      expect(titles.eq(0).text()).toContain('Diagnoza');
      expect(bodies.eq(0).text()).toContain('Analizujemy aktualny stan');
    });
  });

  describe('ikony SVG', () => {
    it('renderuje co najmniej 4 svg (ikony kroków + strzałki)', () => {
      const $ = cheerio.load(renderProcessHtml(DEFAULT_DATA));
      expect($('svg').length).toBeGreaterThanOrEqual(4);
    });

    it('dokładnie 4 ikony kroków ze stroke-width 1.65 (wzorowane na LcIcon .lc-icon)', () => {
      const $ = cheerio.load(renderProcessHtml(DEFAULT_DATA));
      const icons = $('svg[stroke-width="1.65"]');
      expect(icons.length).toBe(4);
      icons.each((_, el) => {
        expect($(el).hasClass('text-brand-primary')).toBe(true);
        expect($(el).hasClass('h-16')).toBe(true);
        expect($(el).hasClass('w-16')).toBe(true);
        expect($(el).attr('aria-hidden')).toBe('true');
      });
    });

    it('każda ikona zawiera pathy z zamkniętej mapy ICON_PATHS', () => {
      const $ = cheerio.load(renderProcessHtml(DEFAULT_DATA));
      const icons = $('svg[stroke-width="1.65"]');
      expect(icons.eq(0).find('path').length).toBeGreaterThan(0);
      expect(icons.eq(1).find('circle').length).toBeGreaterThan(0);
      expect(icons.eq(3).find('path').length).toBe(4);
    });
  });

  describe('dashed strzałki między krokami', () => {
    it('renderuje 3 strzałki (kroki 1-3), nigdy po ostatnim kroku', () => {
      const $ = cheerio.load(renderProcessHtml(DEFAULT_DATA));
      expect($('[class*="border-dashed"]').length).toBe(3);
      const articles = $('article.relative.text-center');
      expect(articles.eq(0).find('[class*="border-dashed"]').length).toBe(1);
      expect(articles.eq(1).find('[class*="border-dashed"]').length).toBe(1);
      expect(articles.eq(2).find('[class*="border-dashed"]').length).toBe(1);
      expect(articles.eq(3).find('[class*="border-dashed"]').length).toBe(0);
    });

    it('strzałka używa tokena border-brand-primary/40 i jest ukryta na mobile (hidden, lg:flex)', () => {
      const $ = cheerio.load(renderProcessHtml(DEFAULT_DATA));
      const line = $('[class*="border-dashed"]');
      expect(line.hasClass('border-brand-primary/40')).toBe(true);
      const arrowWrap = line.first().parent();
      expect(arrowWrap.hasClass('hidden')).toBe(true);
      expect(arrowWrap.hasClass('lg:flex')).toBe(true);
      expect(arrowWrap.hasClass('pointer-events-none')).toBe(true);
    });

    it('strzałka zawiera svg ze ścieżką m9 18 6-6-6-6', () => {
      const $ = cheerio.load(renderProcessHtml(DEFAULT_DATA));
      const arrowSvg = $('svg[stroke-width="3"]');
      expect(arrowSvg.length).toBe(3);
      expect(arrowSvg.first().find('path').attr('d')).toBe('m9 18 6-6-6-6');
    });
  });

  describe('i18n (pl/en)', () => {
    it('EN renderuje angielski nagłówek i tytuły kroków', () => {
      const enData: ProcessData = {
        heading: 'How we work',
        steps: [
          { num: 1, title: 'Diagnosis', description: 'We analyze the current state.', icon: 'diagnose' },
          { num: 2, title: 'Plan', description: 'We prepare a concrete action plan.', icon: 'plan' },
          { num: 3, title: 'Implementation', description: 'We execute the plan step by step.', icon: 'implement' },
          { num: 4, title: 'Monitoring', description: 'We track results and adjust actions.', icon: 'monitor' },
        ],
      };
      const $ = cheerio.load(renderProcessHtml(enData));
      expect($('h2').text()).toBe('How we work');
      expect($('article h3').first().text()).toContain('Diagnosis');
    });

    it('liczba kroków jest elastyczna (propsy nadpisują JSON)', () => {
      const custom = {
        ...DEFAULT_DATA,
        steps: DEFAULT_STEPS.slice(0, 2),
      };
      const $ = cheerio.load(renderProcessHtml(custom));
      expect($('article.relative.text-center').length).toBe(2);
      expect($('[class*="border-dashed"]').length).toBe(1);
      expect($('svg[stroke-width="1.65"]').length).toBe(2);
    });
  });

  it('nie zawiera danych klienta ani klienckich tokenów CSS', () => {
    const html = renderProcessHtml(DEFAULT_DATA);
    expect(html).not.toContain('client-specific');
    expect(html).not.toContain('lc-icon');
    expect(html).not.toContain('data-reveal');
    expect(html).not.toContain('border-outline');
  });
});
