import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';

// Why: The contract test reflects the HTML structure generated by
// ProcessTimelineScrollBlock, wariant sekcji procesu,
// "timeline" variant with scroll progress bar) to detect regressions without
// running a full build. Pattern: services-studio-contract.test.ts.

interface ProcessStep {
  icon?: string;
  title: string;
  description: string;
}

interface ProcessTimelineScrollData {
  sectionId?: string;
  lang?: 'pl' | 'en';
  title?: string;
  description?: string;
  items?: ProcessStep[];
}

const DEFAULT_ITEMS: ProcessStep[] = [
  { title: 'Konsultacja i analiza potrzeb', description: 'Rozmawiamy o Twoich oczekiwaniach i budżecie.' },
  { title: 'Pomiary i wizja lokalna', description: 'Weryfikujemy stan techniczny.' },
  { title: 'Precyzyjny kosztorys', description: 'Przygotowujemy wycenę i harmonogram.' },
  { title: 'Przejrzysta umowa', description: 'Płatności rozłożone na etapy.' },
  { title: 'Realizacja i raporty', description: 'Cotygodniowe raporty zdjęciowe.' },
  { title: 'Odbiór pod klucz', description: 'Oddajemy gotowe wnętrze z gwarancją.' },
];

function renderProcessTimelineScrollHtml(data: ProcessTimelineScrollData): string {
  const {
    sectionId = 'proces',
    lang = 'pl',
    title = 'Jak pracujemy?',
    description = 'Poznaj nasz sprawdzony proces współpracy.',
    items = DEFAULT_ITEMS,
  } = data;

  const isPl = lang === 'pl';
  const stepLabel = isPl ? 'Krok' : 'Step';

  const stepsHtml = items
    .map((item, index) => {
      const isEven = index % 2 === 0;
      const stepNum = (index + 1).toString().padStart(2, '0');
      return `
      <li class="timeline-step relative flex gap-5 lg:items-start ${isEven ? 'lg:flex-row' : 'lg:flex-row-reverse'}" data-step="${index}">
        <div class="relative z-10 flex shrink-0 items-start justify-center lg:absolute lg:left-1/2 lg:-translate-x-1/2">
          <div class="timeline-dot relative flex size-11 items-center justify-center rounded-full border-2 border-brand-primary/20 bg-brand-light text-brand-primary transition-all duration-500">
            <span class="relative text-sm font-bold tabular-nums">${stepNum}</span>
          </div>
        </div>
        <div class="timeline-content flex-1 pt-0.5 lg:pt-1 ${isEven ? 'lg:pr-14 lg:text-right' : 'lg:pl-14 lg:text-left'}">
          <div class="mb-1 lg:mb-2">
            <span class="text-xs font-semibold uppercase tracking-widest text-brand-primary/60">${stepLabel} ${stepNum}</span>
          </div>
          <h3 class="font-heading font-bold ui-type-feature-title mb-2 text-brand-dark">${item.title}</h3>
          <p class="leading-relaxed ui-type-body text-brand-dark/65">${item.description}</p>
        </div>
        <div class="hidden flex-1 lg:block" aria-hidden="true"></div>
      </li>`;
    })
    .join('');

  return `<section id="${sectionId}" class="ui-section ui-bg-base">
    <div class="ui-container">
      <div class="flex flex-col gap-6 text-center items-center mx-auto max-w-2xl mb-12 md:mb-16">
        <h2 class="font-heading font-bold text-brand-dark">${title}</h2>
        <p class="leading-relaxed max-w-2xl mx-auto text-brand-dark/70">${description}</p>
      </div>
      <div id="process-timeline" class="relative mx-auto mt-16 max-w-4xl">
        <div class="absolute left-6 top-3 h-[calc(100%-1.5rem)] w-0.5 rounded-full bg-brand-primary/10 lg:left-1/2 lg:-translate-x-1/2" aria-hidden="true"></div>
        <div id="timeline-progress" class="absolute left-6 top-3 w-0.5 origin-top rounded-full bg-brand-primary transition-all duration-700 ease-out lg:left-1/2 lg:-translate-x-1/2" aria-hidden="true" style="height: 0"></div>
        <ol class="space-y-8 lg:space-y-20" id="timeline-steps">
          ${stepsHtml}
        </ol>
      </div>
    </div>
  </section>`;
}

describe('ProcessTimelineScroll, kontrakt renderowania', () => {
  const defaultData: ProcessTimelineScrollData = {
    title: 'Jak pracujemy?',
    description: 'Poznaj nasz sprawdzony proces współpracy.',
    items: DEFAULT_ITEMS,
  };

  it('renderuje <section> z ui-section, ui-bg-base i id', () => {
    const $ = cheerio.load(renderProcessTimelineScrollHtml(defaultData));
    expect($('section').length).toBe(1);
    expect($('section').hasClass('ui-section')).toBe(true);
    expect($('section').hasClass('ui-bg-base')).toBe(true);
    expect($('section').attr('id')).toBe('proces');
  });

  it('renderuje nagłówek z tytułem i opisem', () => {
    const $ = cheerio.load(renderProcessTimelineScrollHtml(defaultData));
    expect($('h2').text()).toBe('Jak pracujemy?');
    expect($('p').text()).toContain('Poznaj nasz sprawdzony proces');
  });

  it('renderuje dokładnie 6 kroków .timeline-step', () => {
    const $ = cheerio.load(renderProcessTimelineScrollHtml(defaultData));
    expect($('.timeline-step').length).toBe(6);
  });

  it('każdy krok ma data-step z indeksem i naprzemienny układ lg:flex-row / lg:flex-row-reverse', () => {
    const $ = cheerio.load(renderProcessTimelineScrollHtml(defaultData));
    $('.timeline-step').each((index, el) => {
      expect($(el).attr('data-step')).toBe(String(index));
      const expected = index % 2 === 0 ? 'lg:flex-row' : 'lg:flex-row-reverse';
      expect($(el).hasClass(expected)).toBe(true);
    });
  });

  it('kółka kroków zawierają numery 01-06 (nie ikony)', () => {
    const $ = cheerio.load(renderProcessTimelineScrollHtml(defaultData));
    const dots = $('.timeline-dot');
    expect(dots.length).toBe(6);
    dots.each((index, el) => {
      const expected = (index + 1).toString().padStart(2, '0');
      expect($(el).find('span').text()).toBe(expected);
      // Wierna kopia klienta: numer, nie <i class="ph-...">
      expect($(el).find('i.ph').length).toBe(0);
    });
  });

  it('etykieta "Krok XX" nad tytułem kroku', () => {
    const $ = cheerio.load(renderProcessTimelineScrollHtml(defaultData));
    const label = $('.timeline-content span').first();
    expect(label.text()).toBe('Krok 01');
    expect(label.hasClass('text-brand-primary/60')).toBe(true);
  });

  it('renderuje linię tła (bg-brand-primary/10) i pasek postępu (timeline-progress)', () => {
    const $ = cheerio.load(renderProcessTimelineScrollHtml(defaultData));
    const bgLine = $('.bg-brand-primary\\/10');
    expect(bgLine.length).toBe(1);
    const progress = $('#timeline-progress');
    expect(progress.length).toBe(1);
    expect(progress.hasClass('bg-brand-primary')).toBe(true);
    expect(progress.attr('style')).toContain('height: 0');
  });

  it('nie zawiera klienckich klas reveal ani danych klienta', () => {
    const html = renderProcessTimelineScrollHtml(defaultData);
    expect(html).not.toContain('reveal-group');
    expect(html).not.toContain('auto-reveal-item');
    expect(html).not.toContain('data-reveal-on-load');
    expect(html).not.toContain('color-text-primary');
    expect(html).not.toContain('color-accent-primary');
    expect(html).not.toContain('Marek');
    expect(html).not.toContain('Jodłowski');
  });

  it('nie zawiera href="#"', () => {
    const html = renderProcessTimelineScrollHtml(defaultData);
    expect(html).not.toContain('href="#"');
  });
});
