import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';
import zigzagData from '@data/sections/services-zigzag.json';

// Why: The contract test reflects the HTML structure generated by
// ServicesZigzagBlock to detect regressions in bare metal rendering
// full build. Pattern: services-studio-contract.test.ts. The data comes
// from the actual JSON block (services-zigzag.json), so the test keeps an eye on it too
// consistency of pl/data content with the component.

interface ServiceItem {
  image: string;
  icon: string;
  title: string;
  description: string;
  href?: string;
  linkLabel?: string;
}

interface ZigzagSection {
  title: string;
  description: string;
  items: ServiceItem[];
}

// Why: same link format as in the component (InternalLink
// only simplifies internal paths; anchors and outer ones stay).
function formatHref(href: string): string {
  return href;
}

function renderZigzagItem(item: ServiceItem, index: number): string {
  const isReversed = index % 2 === 1;
  const reversedClass = isReversed ? ' md:[&>:first-child]:order-2' : '';
  const href = formatHref(item.href || '/kontakt/');
  const linkLabel = item.linkLabel || 'Umów konsultację';
  return `
    <div class="grid grid-cols-1 md:grid-cols-2 gap-8 md:gap-12 items-center${reversedClass}">
      <div class="aspect-[4/3] overflow-hidden rounded-2xl shadow-md">
        <img src="${item.image}" alt="${item.title}" class="h-full w-full object-cover" width="800" height="600" />
      </div>
      <div class="flex flex-col gap-4">
        <div class="inline-flex size-12 items-center justify-center rounded-xl border border-brand-primary/15 bg-brand-primary/10 text-brand-primary">
          <i class="ph ph-${item.icon}"></i>
        </div>
        <h3 class="text-brand-dark text-2xl font-bold font-heading">${item.title}</h3>
        <p class="text-brand-dark/70 leading-relaxed text-base">${item.description}</p>
        <a href="${href}" class="inline-flex items-center gap-2 mt-2 font-semibold text-brand-primary transition-colors hover:underline underline-offset-4">
          ${linkLabel}
          <span aria-hidden="true"><i class="ph ph-arrow-right"></i></span>
        </a>
      </div>
    </div>`;
}

function renderServicesZigzagHtml(data: ZigzagSection, sectionId = 'services-zigzag'): string {
  const itemsHtml = data.items.map(renderZigzagItem).join('');
  return `<section id="${sectionId}" class="ui-section">
    <div class="ui-container">
      <div class="flex flex-col gap-6 text-center items-center mx-auto max-w-2xl mb-12 md:mb-16">
        <h2 class="text-brand-dark">${data.title}</h2>
        <p class="max-w-2xl font-normal mx-auto">${data.description}</p>
      </div>
      <div class="space-y-16 md:space-y-20">
        ${itemsHtml}
      </div>
    </div>
  </section>`;
}

describe('ServicesZigzag, kontrakt renderowania', () => {
  const defaultData: ZigzagSection = zigzagData.pl;

  it('renderuje <section> z id i ui-section', () => {
    const $ = cheerio.load(renderServicesZigzagHtml(defaultData));
    expect($('section').length).toBe(1);
    expect($('section').hasClass('ui-section')).toBe(true);
    expect($('section').attr('id')).toBe('services-zigzag');
  });

  it('zawiera .ui-container', () => {
    const $ = cheerio.load(renderServicesZigzagHtml(defaultData));
    expect($('.ui-container').length).toBe(1);
  });

  it('renderuje h2 z tytułem sekcji (SectionHeader)', () => {
    const $ = cheerio.load(renderServicesZigzagHtml(defaultData));
    expect($('h2').length).toBe(1);
    expect($('h2').text()).toContain('Nasze usługi');
  });

  describe('dane JSON', () => {
    it('JSON ma sekcje pl i en z taką samą liczbą usług', () => {
      expect(zigzagData.pl.items.length).toBeGreaterThanOrEqual(4);
      expect(zigzagData.pl.items.length).toBeLessThanOrEqual(6);
      expect(zigzagData.en.items.length).toBe(zigzagData.pl.items.length);
    });

    it('wszystkie obrazki wskazują placeholdery starter-kita', () => {
      zigzagData.pl.items.forEach((item) => {
        expect(item.image).toMatch(/^\/assets\/placeholders\//);
      });
    });
  });

  describe('grid zygzak', () => {
    it('grid jest mobile-first (grid-cols-1 md:grid-cols-2)', () => {
      const $ = cheerio.load(renderServicesZigzagHtml(defaultData));
      const grid = $('.grid').first();
      expect(grid.hasClass('grid-cols-1')).toBe(true);
      expect(grid.hasClass('md:grid-cols-2')).toBe(true);
    });

    it('renderuje dokładnie tyle kart, ile usług w danych', () => {
      const $ = cheerio.load(renderServicesZigzagHtml(defaultData));
      expect($('.grid .aspect-\\[4\\/3\\]').length).toBe(defaultData.items.length);
    });

    it('parzyste elementy mają naprzemienny order (md:[&>:first-child]:order-2)', () => {
      const $ = cheerio.load(renderServicesZigzagHtml(defaultData));
      $('.grid').each((index, el) => {
        const reversed = index % 2 === 1;
        expect($(el).hasClass('md:[&>:first-child]:order-2')).toBe(reversed);
      });
    });

    it('zdjęcie ma aspect-[4/3] i rounded-2xl', () => {
      const $ = cheerio.load(renderServicesZigzagHtml(defaultData));
      const frame = $('.grid .aspect-\\[4\\/3\\]').first();
      expect(frame.hasClass('aspect-[4/3]')).toBe(true);
      expect(frame.hasClass('overflow-hidden')).toBe(true);
      expect(frame.hasClass('rounded-2xl')).toBe(true);
    });
  });

  describe('ikony', () => {
    it('każda karta ma ikonę w kwadracie z brandowymi klasami', () => {
      const $ = cheerio.load(renderServicesZigzagHtml(defaultData));
      const boxes = $('.border-brand-primary\\/15');
      expect(boxes.length).toBe(defaultData.items.length);
      boxes.each((_, el) => {
        expect($(el).hasClass('bg-brand-primary/10')).toBe(true);
        expect($(el).hasClass('text-brand-primary')).toBe(true);
      });
    });

    it('ikony mają nazwy z danych JSON (house, wrench, pencil, check-circle, users)', () => {
      const $ = cheerio.load(renderServicesZigzagHtml(defaultData));
      const iconNames = defaultData.items.map((item) => item.icon);
      const uniqueIcons = Array.from(new Set(iconNames));
      uniqueIcons.forEach((icon) => {
        expect($(`i.ph-${icon}`).length).toBeGreaterThanOrEqual(1);
      });
    });

    it('ikony z danych istnieją w phosphor-min.css starter-kita', () => {
      // Why: list of icons from src/styles/phosphor-min.css (as of today
      // adding a block). When you add a new icon to the JSON, add it in CSS as well
      // albo test przypomni o braku wpisu.
      const availableIcons = [
        'house', 'wrench', 'pencil', 'check-circle', 'users',
      ];
      defaultData.items.forEach((item) => {
        expect(availableIcons).toContain(item.icon);
      });
    });
  });

  describe('linki', () => {
    it('każdy link ma trailing slash dla ścieżek wewnętrznych', () => {
      const $ = cheerio.load(renderServicesZigzagHtml(defaultData));
      $('a[href]').each((_, el) => {
        const href = $(el).attr('href') || '';
        if (href.startsWith('/') && !href.startsWith('/#')) {
          expect(href.endsWith('/')).toBe(true);
        }
      });
    });

    it('nie zawiera niepoprawnych kotwic (href="#kontakt")', () => {
      const html = renderServicesZigzagHtml(defaultData);
      expect(html).not.toContain('href="#kontakt"');
    });

    it('link ma strzałkę w prawo w span aria-hidden', () => {
      const $ = cheerio.load(renderServicesZigzagHtml(defaultData));
      const arrow = $('a[href] span[aria-hidden="true"] i.ph-arrow-right').first();
      expect(arrow.length).toBe(1);
    });
  });

  it('wersja en ma tę samą strukturę co pl', () => {
    const $ = cheerio.load(renderServicesZigzagHtml(zigzagData.en));
    expect($('.grid').length).toBe(zigzagData.en.items.length);
    expect($('h2').text()).toContain('Our services');
  });
});
