import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';

// Why: The contract test reflects the HTML structure generated by
// ServicesGridBlock + ServiceCard to detect regressions in rendering without
// running a full build. Pattern: services-studio-contract.test.ts.

interface ServiceItem {
  image: string;
  icon: string;
  title: string;
  description: string;
  href?: string;
  linkLabel?: string;
}

interface ServicesGridData {
  sectionId?: string;
  title?: string;
  description?: string;
  items?: ServiceItem[];
}

// Why: The test data matches the default general content from
// src/data/sections/services-grid.json (5 services, icons existing in phosphor-min.css).
const DEFAULT_ITEMS: ServiceItem[] = [
  { image: '/assets/placeholders/image-landscape.svg', icon: 'house', title: 'Remonty i wykończenia', description: 'Kompleksowe remonty mieszkań i domów.', href: '/kontakt/', linkLabel: 'Skontaktuj się' },
  { image: '/assets/placeholders/image-landscape.svg', icon: 'wrench', title: 'Naprawy i konserwacja', description: 'Szybka reakcja na awarie.', href: '/kontakt/', linkLabel: 'Skontaktuj się' },
  { image: '/assets/placeholders/image-landscape.svg', icon: 'shapes', title: 'Projektowanie i aranżacja', description: 'Funkcjonalna i estetyczna przestrzeń.', href: '/kontakt/', linkLabel: 'Skontaktuj się' },
  { image: '/assets/placeholders/image-landscape.svg', icon: 'hammer', title: 'Odbiory i przeglądy', description: 'Raport usterek przed zakupem.', href: '/kontakt/', linkLabel: 'Skontaktuj się' },
  { image: '/assets/placeholders/image-landscape.svg', icon: 'users', title: 'Doradztwo i koordynacja', description: 'Wsparcie w wyborze wykonawców.', href: '/kontakt/', linkLabel: 'Skontaktuj się' },
];

// Why: class constants reproduce Card.astro output (variant surface,
// padding none, radius xl, elevation none) plus klasy karty i clip-path.
const CARD_BASE_CLASSES =
  'overflow-hidden ui-bg-surface border border-brand-border/50 p-0 rounded-xl shadow-none ' +
  'group flex h-full flex-col overflow-hidden service-card ' +
  '[clip-path:polygon(4.5rem_0,100%_0,100%_100%,0_100%,0_4.5rem)]';

function renderServiceCardHtml(item: ServiceItem): string {
  return `
    <div class="${CARD_BASE_CLASSES}">
      <div class="relative">
        <div class="aspect-[16/9] overflow-hidden bg-brand-dark/5">
          <img
            src="${item.image}"
            alt="${item.title}"
            class="w-full h-full object-cover object-center origin-bottom transition-transform duration-700 group-hover:scale-105"
            width="800"
            height="600"
            loading="lazy"
          />
          <div class="pointer-events-none absolute inset-x-0 bottom-0 h-12 bg-gradient-to-t from-brand-light/90 via-brand-light/40 to-transparent"></div>
        </div>
        <div class="absolute -bottom-5 left-6 inline-flex size-14 items-center justify-center rounded-[1.1rem] border border-brand-dark/15 bg-brand-light text-brand-dark shadow-[0_18px_36px_-18px_color-mix(in_oklab,var(--color-brand-dark)_28%,transparent)] transition-colors duration-300">
          <span class="inline-flex size-11 items-center justify-center rounded-[0.8rem] bg-brand-dark/10 text-brand-dark transition-colors duration-300 group-hover:bg-brand-dark group-hover:text-brand-light">
            <i class="ph ph-${item.icon}"></i>
          </span>
        </div>
      </div>
      <div class="flex h-full flex-col px-6 pb-6 pt-10 sm:px-7 sm:pb-7 sm:pt-11">
        <h3 class="font-heading font-bold ui-type-feature-title text-brand-dark mb-3 text-lg font-bold font-heading sm:text-xl">${item.title}</h3>
        <p class="leading-relaxed ui-type-text-feature-sm text-brand-dark/70 leading-relaxed">${item.description}</p>
        <div class="mt-auto pt-4">
          <a href="${item.href || '/kontakt/'}" class="group/cta leading-relaxed ui-type-text-feature-sm inline-flex items-center gap-2 font-semibold text-brand-primary transition-colors duration-300 hover:text-brand-dark">
            <span class="relative">
              ${item.linkLabel || 'Umów konsultację'}
              <span class="absolute -bottom-0.5 left-0 h-px w-full origin-left scale-x-0 bg-brand-primary transition-transform duration-300 ease-out group-hover/cta:scale-x-100"></span>
            </span>
            <span aria-hidden="true" class="transition-transform duration-300 ease-out group-hover/cta:translate-x-1">→</span>
          </a>
        </div>
      </div>
    </div>`;
}

function renderServicesGridHtml(data: ServicesGridData): string {
  const {
    sectionId = 'uslugi',
    title = 'Nasze usługi',
    description = 'Kompleksowa pomoc w realizacji projektów.',
    items = DEFAULT_ITEMS,
  } = data;

  const firstRow = items.slice(0, 3).map((item) => renderServiceCardHtml(item)).join('');
  const secondRow = items.slice(3, 5).map((item) => renderServiceCardHtml(item)).join('');

  return `<section id="${sectionId}" class="ui-section ui-bg-page">
    <div class="ui-container">
      <div class="flex flex-col gap-6 text-center items-center mx-auto max-w-2xl mb-12 md:mb-16">
        <h2 class="font-heading font-bold ui-type-section-title text-brand-dark">${title}</h2>
        <p class="leading-relaxed ui-type-lead max-w-2xl font-normal ui-text-on-light-subtle mx-auto">${description}</p>
      </div>
      <div class="services-grid">
        <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
          ${firstRow}
        </div>
      </div>
      <div class="mx-auto mt-8 max-w-full lg:max-w-[66%]">
        <div class="services-grid">
          <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
            ${secondRow}
          </div>
        </div>
      </div>
    </div>
  </section>`;
}

describe('ServiceCard, kontrakt renderowania', () => {
  const item = DEFAULT_ITEMS[0];

  it('ma klasę service-card i clip-path polygon (ucięty róg)', () => {
    const $ = cheerio.load(renderServiceCardHtml(item));
    const card = $('.service-card');
    expect(card.length).toBe(1);
    expect(card.attr('class')).toContain('[clip-path:polygon(4.5rem_0,100%_0,100%_100%,0_100%,0_4.5rem)]');
  });

  it('renderuje zdjęcie z alt (tytuł) i src placeholder', () => {
    const $ = cheerio.load(renderServiceCardHtml(item));
    const img = $('img');
    expect(img.length).toBe(1);
    expect(img.attr('src')).toBe('/assets/placeholders/image-landscape.svg');
    expect(img.attr('alt')).toBe('Remonty i wykończenia');
  });

  it('ma gradientowy overlay na dole zdjęcia (bg-gradient-to-t from-brand-light/90)', () => {
    const $ = cheerio.load(renderServiceCardHtml(item));
    const overlay = $('.bg-gradient-to-t');
    expect(overlay.length).toBe(1);
    expect(overlay.hasClass('pointer-events-none')).toBe(true);
    expect(overlay.hasClass('from-brand-light/90')).toBe(true);
  });

  it('renderuje ikonę Phosphor (i.ph.ph-house) w podwójnym kwadracie', () => {
    const $ = cheerio.load(renderServiceCardHtml(item));
    const icon = $('i.ph');
    expect(icon.length).toBe(1);
    expect(icon.hasClass('ph-house')).toBe(true);
    const outer = icon.closest('.size-11');
    expect(outer.length).toBe(1);
    expect(outer.hasClass('bg-brand-dark/10')).toBe(true);
    expect(outer.hasClass('group-hover:bg-brand-dark')).toBe(true);
    expect(icon.closest('.size-14').hasClass('bg-brand-light')).toBe(true);
  });

  it('renderuje tytuł jako h3 z tekstem', () => {
    const $ = cheerio.load(renderServiceCardHtml(item));
    const heading = $('h3');
    expect(heading.length).toBe(1);
    expect(heading.text()).toBe('Remonty i wykończenia');
  });

  it('renderuje opis usługi', () => {
    const $ = cheerio.load(renderServiceCardHtml(item));
    expect($('p').first().text()).toContain('Kompleksowe remonty mieszkań i domów.');
  });

  it('link ma trailing slash i animowane podkreślenie na hover', () => {
    const $ = cheerio.load(renderServiceCardHtml(item));
    const link = $('a[href="/kontakt/"]');
    expect(link.length).toBe(1);
    expect(link.text()).toContain('Skontaktuj się');
    const underline = link.find('.scale-x-0');
    expect(underline.length).toBe(1);
    expect(underline.hasClass('group-hover/cta:scale-x-100')).toBe(true);
    expect(link.find('[aria-hidden="true"]').text()).toBe('→');
  });

  it('nie dodaje lokalnego stylu wejścia do karty', () => {
    const $ = cheerio.load(renderServiceCardHtml(item));
    const card = $('.service-card');
    expect(card.attr('style')).toBeUndefined();
  });
});

describe('ServicesGrid, kontrakt renderowania', () => {
  const defaultData: ServicesGridData = {
    title: 'Nasze usługi',
    items: DEFAULT_ITEMS,
  };

  it('renderuje <section> z ui-section i id', () => {
    const $ = cheerio.load(renderServicesGridHtml(defaultData));
    expect($('section').length).toBe(1);
    expect($('section').hasClass('ui-section')).toBe(true);
    expect($('section').attr('id')).toBe('uslugi');
  });

  it('zawiera .ui-container', () => {
    const $ = cheerio.load(renderServicesGridHtml(defaultData));
    expect($('.ui-container').length).toBe(1);
  });

  it('SectionHeader renderuje h2 z tytułem i p z opisem (align center)', () => {
    const $ = cheerio.load(renderServicesGridHtml(defaultData));
    expect($('h2').text()).toBe('Nasze usługi');
    expect($('p').first().text()).toContain('Kompleksowa pomoc w realizacji projektów.');
    const header = $('h2').parent();
    expect(header.hasClass('text-center')).toBe(true);
    expect(header.hasClass('items-center')).toBe(true);
    expect(header.hasClass('mx-auto')).toBe(true);
  });

  it('pierwszy grid ma 3 kolumny na lg (grid-cols-1 lg:grid-cols-3) i 3 karty', () => {
    const $ = cheerio.load(renderServicesGridHtml(defaultData));
    const grid = $('.grid').first();
    expect(grid.hasClass('grid-cols-1')).toBe(true);
    expect(grid.hasClass('lg:grid-cols-3')).toBe(true);
    expect(grid.find('.service-card').length).toBe(3);
  });

  it('drugi grid ma 2 kolumny (lg:grid-cols-2) w max-w-[66%] i 2 karty', () => {
    const $ = cheerio.load(renderServicesGridHtml(defaultData));
    const wrapper = $('.lg\\:max-w-\\[66\\%\\]');
    expect(wrapper.length).toBe(1);
    const grid = wrapper.find('.grid');
    expect(grid.hasClass('lg:grid-cols-2')).toBe(true);
    expect(grid.find('.service-card').length).toBe(2);
  });

  it('renderuje dokładnie 5 kart .service-card (3 + 2)', () => {
    const $ = cheerio.load(renderServicesGridHtml(defaultData));
    expect($('.service-card').length).toBe(5);
  });

  it('każda karta ma unikalną ikonę z danych (house, wrench, shapes, hammer, users)', () => {
    const $ = cheerio.load(renderServicesGridHtml(defaultData));
    expect($('i.ph-house').length).toBe(1);
    expect($('i.ph-wrench').length).toBe(1);
    expect($('i.ph-shapes').length).toBe(1);
    expect($('i.ph-hammer').length).toBe(1);
    expect($('i.ph-users').length).toBe(1);
  });

  it('nie zawiera href="#"', () => {
    const html = renderServicesGridHtml(defaultData);
    expect(html).not.toContain('href="#"');
  });
});
