import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';
import { formatInternalLink } from '../../utils/url';

// Why: The contract test reflects the HTML structure generated by
// ServicesCardsBlock to detect regressions in bare-metal rendering
// full build. Pattern: services-studio-contract.test.ts.

interface ServiceItem {
  icon: string;
  title: string;
  description: string;
  href?: string;
  linkLabel?: string;
}

interface ServicesCardsData {
  sectionId?: string;
  title?: string;
  description?: string;
  items?: ServiceItem[];
}

// Why: four generic starter kit services, content responds
// src/data/sections/services-cards.json (sekcja "pl").
const DEFAULT_ITEMS: ServiceItem[] = [
  { icon: 'paint-roller', title: 'Wykończenia pod klucz', description: 'Realizujemy wnętrza w całości.', href: '/kontakt/', linkLabel: 'Bezpłatna wycena' },
  { icon: 'wrench', title: 'Remonty', description: 'Generalne remonty mieszkań i domów.', href: '/kontakt/', linkLabel: 'Bezpłatna wycena' },
  { icon: 'pencil', title: 'Projektowanie', description: 'Projekty wnętrz z wizualizacjami.', href: '/kontakt/', linkLabel: 'Bezpłatna wycena' },
  { icon: 'chat', title: 'Doradztwo', description: 'Praktyczne porady przy remoncie.', href: '/kontakt/', linkLabel: 'Bezpłatna wycena' },
];

// Why: render maps the block structure (Section + Container +
// SectionHeader + Grid + Card), tak jak w services-studio-contract.test.ts.
function renderServicesCardsHtml(data: ServicesCardsData): string {
  const {
    sectionId = 'uslugi',
    title = 'Nasze usługi',
    description = 'Kompleksowa obsługa wnętrz.',
    items = DEFAULT_ITEMS,
  } = data;

  const cardsHtml = items
    .map((item) => `
      <div class="group ui-bg-surface border border-brand-border/50 border-brand-dark/10 ui-elevation-soft rounded-xl overflow-hidden flex h-full flex-col p-8 transition-transform duration-300 hover:-translate-y-1">
        <div class="mb-6 inline-flex size-14 items-center justify-center rounded-2xl border border-brand-dark/15 bg-brand-dark/10 text-brand-dark transition-colors duration-300 group-hover:border-brand-dark group-hover:bg-brand-dark group-hover:text-brand-light">
          <i class="ph ph-${item.icon}" style="font-size: 28px"></i>
        </div>
        <h3 class="font-heading font-bold ui-type-feature-title mb-3 text-xl font-bold text-brand-dark">${item.title}</h3>
        <p class="ui-type-text-feature-sm mb-6 leading-relaxed text-brand-dark/70">${item.description}</p>
        <div class="mt-auto">
          <a href="${formatInternalLink(item.href || '/kontakt/')}" class="inline-flex items-center justify-center gap-2 rounded-xl bg-brand-primary px-5 py-2.5 text-sm font-semibold text-white transition-all duration-300 ease-out hover:-translate-y-0.5 hover:bg-brand-primary/90 hover:shadow-lg active:scale-[0.97]">
            ${item.linkLabel || 'Umów konsultację'}
            <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="size-4 transition-transform duration-300 ease-out group-hover:translate-x-1">
              <path d="M5 12h14"></path>
              <path d="m12 5 7 7-7 7"></path>
            </svg>
          </a>
        </div>
      </div>`)
    .join('');

  return `<section id="${sectionId}" class="ui-section ui-bg-page">
    <div class="ui-container">
      <div class="mx-auto max-w-2xl text-center">
        <h2 class="font-heading font-bold ui-type-section-title text-brand-dark">${title}</h2>
        <p class="ui-type-text-lead text-brand-dark/70">${description}</p>
      </div>
      <div class="mt-16 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
        ${cardsHtml}
      </div>
    </div>
  </section>`;
}

describe('ServicesCardsBlock, kontrakt renderowania', () => {
  const defaultData: ServicesCardsData = {
    title: 'Nasze usługi',
    items: DEFAULT_ITEMS,
  };

  describe('sekcja', () => {
    it('renderuje <section> z ui-section, ui-bg-page i id', () => {
      const $ = cheerio.load(renderServicesCardsHtml(defaultData));
      expect($('section').length).toBe(1);
      expect($('section').hasClass('ui-section')).toBe(true);
      expect($('section').hasClass('ui-bg-page')).toBe(true);
      expect($('section').attr('id')).toBe('uslugi');
    });

    it('zawiera .ui-container', () => {
      const $ = cheerio.load(renderServicesCardsHtml(defaultData));
      expect($('.ui-container').length).toBe(1);
    });
  });

  describe('SectionHeader', () => {
    it('renderuje h2 z tytułem', () => {
      const $ = cheerio.load(renderServicesCardsHtml(defaultData));
      expect($('h2').length).toBe(1);
      expect($('h2').text()).toContain('Nasze usługi');
      expect($('h2').hasClass('ui-type-section-title')).toBe(true);
    });

    it('nagłówek jest wycentrowany (mx-auto max-w-2xl text-center)', () => {
      const $ = cheerio.load(renderServicesCardsHtml(defaultData));
      const header = $('.mx-auto.max-w-2xl');
      expect(header.length).toBe(1);
      expect(header.hasClass('text-center')).toBe(true);
    });

    it('renderuje opis sekcji', () => {
      const $ = cheerio.load(renderServicesCardsHtml(defaultData));
      expect($('p').first().text()).toContain('Kompleksowa obsługa wnętrz.');
    });
  });

  describe('grid', () => {
    it('grid jest mobile-first (grid-cols-1 md:grid-cols-2 lg:grid-cols-4)', () => {
      const $ = cheerio.load(renderServicesCardsHtml(defaultData));
      const grid = $('.grid');
      expect(grid.hasClass('grid-cols-1')).toBe(true);
      expect(grid.hasClass('md:grid-cols-2')).toBe(true);
      expect(grid.hasClass('lg:grid-cols-4')).toBe(true);
    });

    it('renderuje dokładnie 4 karty', () => {
      const $ = cheerio.load(renderServicesCardsHtml(defaultData));
      expect($('div.group').length).toBe(4);
    });
  });

  describe('karta usługi', () => {
    it('karta ma variant surface, radius xl, elevation soft i p-8', () => {
      const $ = cheerio.load(renderServicesCardsHtml(defaultData));
      const card = $('div.group').first();
      expect(card.hasClass('ui-bg-surface')).toBe(true);
      expect(card.hasClass('rounded-xl')).toBe(true);
      expect(card.hasClass('ui-elevation-soft')).toBe(true);
      expect(card.hasClass('p-8')).toBe(true);
    });

    it('karta unosi się na hover (hover:-translate-y-1)', () => {
      const $ = cheerio.load(renderServicesCardsHtml(defaultData));
      $('div.group').each((_, el) => {
        expect($(el).hasClass('hover:-translate-y-1')).toBe(true);
      });
    });

    it('tytuł to h3 z font-heading i text-brand-dark', () => {
      const $ = cheerio.load(renderServicesCardsHtml(defaultData));
      const h3 = $('h3').first();
      expect(h3.hasClass('font-heading')).toBe(true);
      expect(h3.hasClass('text-brand-dark')).toBe(true);
      expect(h3.text()).toBe('Wykończenia pod klucz');
    });

    it('opis renderuje się w karcie', () => {
      const $ = cheerio.load(renderServicesCardsHtml(defaultData));
      expect($('p').last().text()).toContain('Praktyczne porady przy remoncie.');
    });
  });

  describe('ikony', () => {
    it('renderuje ikonę w każdej karcie z klasą ph-', () => {
      const $ = cheerio.load(renderServicesCardsHtml(defaultData));
      expect($('i.ph').length).toBe(4);
      $('i.ph').each((_, el) => {
        expect($(el).attr('class')).toContain('ph-');
      });
    });

    it('ikony mają nazwy z danych (paint-roller, wrench, pencil, chat)', () => {
      const $ = cheerio.load(renderServicesCardsHtml(defaultData));
      expect($('i.ph-paint-roller').length).toBe(1);
      expect($('i.ph-wrench').length).toBe(1);
      expect($('i.ph-pencil').length).toBe(1);
      expect($('i.ph-chat').length).toBe(1);
    });

    it('ikona siedzi w ciemnym kwadracie (bg-brand-dark/10, hover na ciemny)', () => {
      const $ = cheerio.load(renderServicesCardsHtml(defaultData));
      const box = $('div.group').first().find('div').first();
      expect(box.hasClass('bg-brand-dark/10')).toBe(true);
      expect(box.hasClass('group-hover:bg-brand-dark')).toBe(true);
      expect(box.hasClass('group-hover:text-brand-light')).toBe(true);
    });
  });

  describe('przyciski CTA', () => {
    it('każda karta ma przycisk w kontenerze mt-auto', () => {
      const $ = cheerio.load(renderServicesCardsHtml(defaultData));
      $('div.group').each((_, el) => {
        const wrapper = $(el).find('div.mt-auto');
        expect(wrapper.length).toBe(1);
        expect(wrapper.find('a').length).toBe(1);
      });
    });

    it('przycisk jest pełny (bg-brand-primary, text-white) i unosi się na hover', () => {
      const $ = cheerio.load(renderServicesCardsHtml(defaultData));
      $('div.group a').each((_, el) => {
        expect($(el).hasClass('bg-brand-primary')).toBe(true);
        expect($(el).hasClass('text-white')).toBe(true);
        expect($(el).hasClass('hover:-translate-y-0.5')).toBe(true);
      });
    });

    it('etykieta CTA pochodzi z danych', () => {
      const $ = cheerio.load(renderServicesCardsHtml(defaultData));
      expect($('div.group a').first().text()).toContain('Bezpłatna wycena');
    });

    it('href przechodzi przez formatInternalLink (trailing slash)', () => {
      const $ = cheerio.load(renderServicesCardsHtml(defaultData));
      $('div.group a').each((_, el) => {
        const href = $(el).attr('href') || '';
        expect(href.endsWith('/')).toBe(true);
        expect(href).not.toBe('#');
      });
    });

    it('strzałka to inline SVG z stroke currentColor', () => {
      const $ = cheerio.load(renderServicesCardsHtml(defaultData));
      const svg = $('div.group a svg').first();
      expect(svg.length).toBe(1);
      expect(svg.attr('aria-hidden')).toBe('true');
      expect(svg.attr('stroke')).toBe('currentColor');
      expect(svg.attr('viewBox')).toBe('0 0 24 24');
      expect(svg.find('path').length).toBe(2);
    });
  });

  it('nie zawiera href="#"', () => {
    const html = renderServicesCardsHtml(defaultData);
    expect(html).not.toContain('href="#"');
  });
});
