import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';
import { formatInternalLink } from '@utils/url';

// Why: The contract test reflects the HTML structure generated by
// SpecializationsGridBlock (kopia wizualna sekcji specjalizacji z projektu
// to detect regressions in bare-metal rendering
// full build. Pattern: services-studio-contract.test.ts.
//
// Note: the block uses global starter kit tokens (brand-dark,
// brand-primary, ui-bg-page) and not from client tokens (text-primary,
// accent-primary), therefore there are no text-brand-* classes in the test.

interface Cta {
  label: string;
  hoverText?: string;
  href: string;
}

interface FeaturedItem {
  title: string;
  description: string;
  image?: string;
  icon?: string;
  href?: string;
  cta?: Cta;
}

interface GridItem {
  icon?: string;
  title: string;
  description: string;
  href?: string;
}

interface SpecializationsData {
  lang?: 'pl' | 'en';
  sectionId?: string;
  eyebrow?: string;
  heading?: string;
  description?: string;
  ctaLabel?: string;
  ctaHref?: string;
  featured?: FeaturedItem[];
  items?: GridItem[];
}

const DEFAULT_FEATURED: FeaturedItem[] = [
  {
    title: 'Obsługa kompleksowa',
    description: 'Jeden partner prawny dla całej działalności.',
    image: '/assets/placeholders/image-landscape.svg',
    icon: 'briefcase',
    href: '/specjalizacje/',
    cta: { label: 'Poznaj szczegóły', hoverText: 'Zobacz więcej', href: '/kontakt/' },
  },
];

const DEFAULT_ITEMS: GridItem[] = [
  { icon: 'scales', title: 'Prawo cywilne', description: 'Umowy i roszczenia.', href: '/specjalizacje/prawo-cywilne/' },
  { icon: 'briefcase', title: 'Prawo gospodarcze', description: 'Obsługa firm.', href: '/specjalizacje/prawo-gospodarcze/' },
  { icon: 'users', title: 'Prawo rodzinne', description: 'Rozwody i alimenty.', href: '/specjalizacje/prawo-rodzinne/' },
  { icon: 'house', title: 'Nieruchomości', description: 'Umowy sprzedaży.', href: '/specjalizacje/prawo-nieruchomosci/' },
  { icon: 'scroll', title: 'Prawo spadkowe', description: 'Testamenty i spadki.', href: '/specjalizacje/prawo-spadkowe/' },
  { icon: 'gavel', title: 'Prawo karne', description: 'Obrona w sprawach karnych.', href: '/specjalizacje/prawo-karne/' },
];

const PLACEHOLDER_IMAGE = '/assets/placeholders/image-landscape.svg';

// Why: hint dictionary, consistent with the component (no de version, because block
// starter-kit only supports pl and en).
const HINTS: Record<string, { poznajZakres: string; poznajSzczegoly: string }> = {
  pl: { poznajZakres: 'Poznaj zakres usług', poznajSzczegoly: 'Poznaj szczegóły' },
  en: { poznajZakres: 'Explore services', poznajSzczegoly: 'View details' },
};

function renderSpecializationsHtml(data: SpecializationsData): string {
  const {
    lang = 'pl',
    sectionId = 'specjalizacje',
    eyebrow = 'Specjalizacje',
    heading = 'Obsługa prawna w pełnym zakresie',
    description = 'Wspieramy w sprawach cywilnych, gospodarczych i rodzinnych.',
    ctaLabel = 'Wszystkie specjalizacje',
    ctaHref = '/specjalizacje/',
    featured = DEFAULT_FEATURED,
    items = DEFAULT_ITEMS,
  } = data;

  const hints = HINTS[lang];

  const featuredHtml = featured
    .map((item) => {
      const cardHref = formatInternalLink(item.href ?? item.cta?.href ?? ctaHref);
      const ctaHtml = item.cta?.href
        ? `<a href="${formatInternalLink(item.cta.href)}" class="ui-button ui-button-primary h-9 px-4 text-xs sm:text-sm [&_svg]:size-3.5">${item.cta.label}</a>`
        : '';
      return `
      <div class="cross-border-card group relative overflow-hidden rounded-2xl border border-brand-dark/10 bg-white" style="border-color: color-mix(in oklch, var(--color-brand-primary) 45%, transparent)">
        <a class="card-hit-area" href="${cardHref}" aria-label="${hints.poznajZakres}: ${item.title}"></a>
        <div class="cross-border-card__media" aria-hidden="true">
          <img src="${item.image || PLACEHOLDER_IMAGE}" alt="" width="1824" height="862" loading="lazy" decoding="async" />
          <div class="cross-border-card__mask"></div>
        </div>
        <div class="cross-border-card__content pointer-events-none p-5 md:p-6">
          <div class="max-w-2xl">
            <h3 class="font-heading font-bold ui-type-feature-title mb-4 text-brand-dark">${item.title}</h3>
            <p class="leading-relaxed ui-type-body mb-4 text-brand-dark/70">${item.description}</p>
            <div class="flex flex-wrap items-center gap-x-4 gap-y-3">
              ${ctaHtml}
              <span class="card-link-hint inline-flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.16em] sm:text-xs" aria-hidden="true">
                ${hints.poznajZakres} <i class="ph ph-arrow-up-right" style="font-size: 14px"></i>
              </span>
            </div>
          </div>
        </div>
      </div>`;
    })
    .join('');

  const gridHtml = items
    .map((item) => `
      <a href="${formatInternalLink(item.href)}" class="spec-grid-card group relative flex cursor-pointer flex-col rounded-2xl border border-brand-dark/10 bg-white p-6 no-underline transition-all duration-300 hover:-translate-y-1 hover:border-brand-primary/40 sm:p-8">
        <div class="spec-icon" aria-hidden="true">
          <i class="ph ph-${item.icon || 'scales'}" style="font-size: 24px"></i>
        </div>
        <h3 class="font-heading font-bold ui-type-feature-title mb-2 text-brand-dark">${item.title}</h3>
        <p class="leading-relaxed ui-type-body text-brand-dark/70">${item.description}</p>
        <span class="card-link-hint mt-auto inline-flex items-center gap-2 pt-6 text-xs font-semibold uppercase tracking-[0.16em]" aria-hidden="true">
          ${hints.poznajSzczegoly} <i class="ph ph-arrow-up-right" style="font-size: 14px"></i>
        </span>
      </a>`)
    .join('');

  const bottomCta = ctaHref
    ? `<div class="mt-12 text-center"><a href="${formatInternalLink(ctaHref)}" class="ui-button ui-button-outline h-11 sm:h-12 px-5 sm:px-8 text-sm sm:text-lg [&_svg]:size-5"><span>${ctaLabel}</span></a></div>`
    : '';

  return `<section id="${sectionId}" class="ui-section ui-bg-page relative overflow-hidden scroll-mt-28">
    <div class="ui-container">
      <div class="mx-auto mb-14 max-w-2xl text-center md:mb-18">
        <p class="leading-relaxed ui-type-accent-label mb-4 text-brand-dark">${eyebrow}</p>
        <h2 class="font-heading font-bold ui-type-section-title mb-5 text-brand-dark">${heading}</h2>
        <p class="leading-relaxed ui-type-lead text-brand-dark/70">${description}</p>
      </div>
      <div class="mb-4 flex flex-col gap-4">${featuredHtml}</div>
      <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">${gridHtml}</div>
      ${bottomCta}
    </div>
  </section>`;
}

describe('SpecializationsGrid, kontrakt renderowania', () => {
  const defaultData: SpecializationsData = {
    heading: 'Obsługa prawna w pełnym zakresie',
    eyebrow: 'Specjalizacje',
    description: 'Wspieramy w sprawach cywilnych, gospodarczych i rodzinnych.',
    ctaLabel: 'Wszystkie specjalizacje',
    ctaHref: '/specjalizacje/',
    featured: DEFAULT_FEATURED,
    items: DEFAULT_ITEMS,
  };

  it('renderuje <section> z ui-section, ui-bg-page i id', () => {
    const $ = cheerio.load(renderSpecializationsHtml(defaultData));
    expect($('section').length).toBe(1);
    expect($('section').hasClass('ui-section')).toBe(true);
    expect($('section').hasClass('ui-bg-page')).toBe(true);
    expect($('section').attr('id')).toBe('specjalizacje');
  });

  it('zawiera .ui-container', () => {
    const $ = cheerio.load(renderSpecializationsHtml(defaultData));
    expect($('.ui-container').length).toBe(1);
  });

  it('renderuje h2 z headingiem', () => {
    const $ = cheerio.load(renderSpecializationsHtml(defaultData));
    expect($('h2').length).toBe(1);
    expect($('h2').text()).toContain('Obsługa prawna w pełnym zakresie');
  });

  it('renderuje eyebrow (accent-label) i description (lead)', () => {
    const $ = cheerio.load(renderSpecializationsHtml(defaultData));
    expect($('p.ui-type-accent-label').text()).toBe('Specjalizacje');
    expect($('p.ui-type-lead').text()).toContain('Wspieramy w sprawach');
  });

  describe('karta featured (cross-border)', () => {
    it('renderuje dokładnie 1 kartę .cross-border-card', () => {
      const $ = cheerio.load(renderSpecializationsHtml(defaultData));
      expect($('.cross-border-card').length).toBe(1);
    });

    it('karta ma obwódkę w kolorze brand-primary (style inline)', () => {
      const $ = cheerio.load(renderSpecializationsHtml(defaultData));
      const card = $('.cross-border-card').first();
      expect(card.attr('style')).toContain('color-mix(in oklch, var(--color-brand-primary) 45%, transparent)');
    });

    it('ma obszar klikalny .card-hit-area z linkiem', () => {
      const $ = cheerio.load(renderSpecializationsHtml(defaultData));
      expect($('.card-hit-area').length).toBe(1);
      expect($('.card-hit-area').attr('href')).toBe('/specjalizacje/');
    });

    it('ma obraz z placeholderem starter-kita i maską gradientową', () => {
      const $ = cheerio.load(renderSpecializationsHtml(defaultData));
      const img = $('.cross-border-card__media img');
      expect(img.length).toBe(1);
      expect(img.attr('src')).toBe('/assets/placeholders/image-landscape.svg');
      expect(img.attr('alt')).toBe('');
      expect($('.cross-border-card__mask').length).toBe(1);
    });

    it('renderuje tytuł (h3) i opis', () => {
      const $ = cheerio.load(renderSpecializationsHtml(defaultData));
      expect($('.cross-border-card h3').text()).toBe('Obsługa kompleksowa');
      expect($('.cross-border-card p.ui-type-body').text()).toContain('Jeden partner prawny');
    });

    it('renderuje CTA jako Button primary i hint "Poznaj zakres usług" ze strzałką', () => {
      const $ = cheerio.load(renderSpecializationsHtml(defaultData));
      const button = $('.cross-border-card a.ui-button.ui-button-primary');
      expect(button.length).toBe(1);
      expect(button.attr('href')).toBe('/kontakt/');
      expect($('.cross-border-card .card-link-hint').text()).toContain('Poznaj zakres usług');
      expect($('.cross-border-card .card-link-hint i.ph-arrow-up-right').length).toBe(1);
    });
  });

  describe('grid specjalizacji', () => {
    it('grid jest mobile-first (grid-cols-1 sm:grid-cols-2 lg:grid-cols-3)', () => {
      const $ = cheerio.load(renderSpecializationsHtml(defaultData));
      const grid = $('.grid');
      expect(grid.hasClass('sm:grid-cols-2')).toBe(true);
      expect(grid.hasClass('lg:grid-cols-3')).toBe(true);
    });

    it('renderuje dokładnie 6 kart .spec-grid-card', () => {
      const $ = cheerio.load(renderSpecializationsHtml(defaultData));
      expect($('a.spec-grid-card').length).toBe(6);
    });

    it('każda karta jest linkiem z trailing slash i ma hover: -translate-y-1', () => {
      const $ = cheerio.load(renderSpecializationsHtml(defaultData));
      $('a.spec-grid-card').each((_, el) => {
        const href = $(el).attr('href');
        expect(href?.endsWith('/')).toBe(true);
        expect($(el).hasClass('hover:-translate-y-1')).toBe(true);
      });
    });
  });

  describe('ikony', () => {
    it('każda karta grid ma ikonę z nazwą z danych', () => {
      const $ = cheerio.load(renderSpecializationsHtml(defaultData));
      expect($('a.spec-grid-card .spec-icon i.ph').length).toBe(6);
    });

    it('ikony mają nazwy z danych (scales, briefcase, users, house, scroll, gavel)', () => {
      const $ = cheerio.load(renderSpecializationsHtml(defaultData));
      expect($('i.ph-scales').length).toBe(1);
      expect($('i.ph-briefcase').length).toBe(1);
      expect($('i.ph-users').length).toBe(1);
      expect($('i.ph-house').length).toBe(1);
      expect($('i.ph-scroll').length).toBe(1);
      expect($('i.ph-gavel').length).toBe(1);
    });

    it('hint w każdej karcie ma strzałkę ph-arrow-up-right', () => {
      const $ = cheerio.load(renderSpecializationsHtml(defaultData));
      expect($('a.spec-grid-card i.ph-arrow-up-right').length).toBe(6);
    });
  });

  describe('tytuły i hinty kart', () => {
    it('karty mają tytuły z danych (h3)', () => {
      const $ = cheerio.load(renderSpecializationsHtml(defaultData));
      const titles = $('a.spec-grid-card h3').toArray().map((el) => $(el).text());
      expect(titles).toEqual([
        'Prawo cywilne',
        'Prawo gospodarcze',
        'Prawo rodzinne',
        'Nieruchomości',
        'Prawo spadkowe',
        'Prawo karne',
      ]);
    });

    it('hint "Poznaj szczegóły" jest w każdej karcie grid', () => {
      const $ = cheerio.load(renderSpecializationsHtml(defaultData));
      $('a.spec-grid-card .card-link-hint').each((_, el) => {
        expect($(el).text()).toContain('Poznaj szczegóły');
      });
    });
  });

  describe('CTA na dole', () => {
    it('renderuje Button outline z ctaHref i ctaLabel', () => {
      const $ = cheerio.load(renderSpecializationsHtml(defaultData));
      const cta = $('.mt-12.text-center a.ui-button-outline');
      expect(cta.length).toBe(1);
      expect(cta.attr('href')).toBe('/specjalizacje/');
      expect(cta.text()).toContain('Wszystkie specjalizacje');
    });

    it('nie renderuje dolnego CTA, gdy brak ctaHref', () => {
      const $ = cheerio.load(renderSpecializationsHtml({ ...defaultData, ctaHref: '' }));
      expect($('.mt-12.text-center').length).toBe(0);
    });
  });

  describe('wariant en', () => {
    it('używa angielskich hintów i treści', () => {
      const $ = cheerio.load(
        renderSpecializationsHtml({
          ...defaultData,
          lang: 'en',
          heading: 'Full-scope legal support',
          ctaLabel: 'All specializations',
          ctaHref: '/en/specializations/',
        })
      );
      expect($('h2').text()).toContain('Full-scope legal support');
      expect($('a.spec-grid-card .card-link-hint').first().text()).toContain('View details');
      expect($('.mt-12.text-center a').attr('href')).toBe('/en/specializations/');
    });
  });

  it('nie zawiera klienckich klas reveal (auto-reveal-item, reveal-group, data-reveal-on-load)', () => {
    const html = renderSpecializationsHtml(defaultData);
    expect(html).not.toContain('auto-reveal-item');
    expect(html).not.toContain('reveal-group');
    expect(html).not.toContain('data-reveal-on-load');
  });

  it('nie zawiera href="#"', () => {
    const html = renderSpecializationsHtml(defaultData);
    expect(html).not.toContain('href="#"');
  });

  it('nie zawiera klienckich tokenów kolorów (text-primary, accent-primary)', () => {
    const html = renderSpecializationsHtml(defaultData);
    expect(html).not.toContain('text-primary');
    expect(html).not.toContain('accent-primary');
  });
});
