import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';
import jsonData from '@data/sections/timeline-alternate.json';

// Why: The contract test reflects the HTML structure generated by
// TimelineAlternateBlock (a copy of the project's alternating timeline of issues
// reference section, to detect regressions
// in rendering without running the full build. Pattern: lc-navbar-contract.test.ts.
// Note: Astro 7 does not export the Vite plugin for testing, and AstroContainer requires it
// full Astro environment, so we build the HTML manually faithfully to the component.

type Locale = 'pl' | 'en';
type TimelineItem = { num: string; title: string; description: string };
interface TimelineData {
  eyebrow: string;
  heading: string;
  description: string;
  items: TimelineItem[];
}

const PL_DATA: TimelineData = jsonData.pl;
const EN_DATA: TimelineData = jsonData.en;

// Why: single item timeline, faithful to TimelineAlternateBlock.
// isLeft = tekst po lewej na desktop (index parzysty: 01, 03).
function renderItem(item: TimelineItem, index: number): string {
  const isLeft = index % 2 === 0;
  const dot = `<div class="timeline-dot relative z-10 flex h-7 w-7 shrink-0 items-center justify-center rounded-full border-2 border-brand-accent bg-white text-[10px] font-extrabold text-brand-accent transition-all duration-500 sm:mx-auto sm:h-11 sm:w-11 sm:text-sm" data-timeline-dot>${item.num}</div>`;
  const content = `<h3 class="font-heading font-bold !text-lg !font-extrabold">${item.title}</h3>
        <p class="leading-relaxed ui-type-text-feature-sm mt-2 !font-semibold !leading-7">${item.description}</p>`;

  if (isLeft) {
    return `<div class="timeline-item relative grid grid-cols-[auto_1fr] gap-3 sm:grid-cols-[1fr_auto_1fr] sm:items-start sm:gap-0" data-timeline-item data-timeline-index="${index}">
        <div class="hidden sm:block sm:pr-10 sm:text-right lg:pr-14">
          ${content}
        </div>
        ${dot}
        <div class="sm:hidden">
          ${content}
        </div>
        <div class="hidden sm:block sm:pl-10 lg:pl-14" aria-hidden="true"></div>
      </div>`;
  }
  return `<div class="timeline-item relative grid grid-cols-[auto_1fr] gap-3 sm:grid-cols-[1fr_auto_1fr] sm:items-start sm:gap-0" data-timeline-item data-timeline-index="${index}">
        <div class="hidden sm:block sm:pr-10 sm:text-right lg:pr-14" aria-hidden="true"></div>
        ${dot}
        <div class="sm:pl-10 lg:pl-14">
          ${content}
        </div>
      </div>`;
}

function renderTimelineAlternateHtml(locale: Locale = 'pl'): string {
  const t = locale === 'en' ? EN_DATA : PL_DATA;
  const itemsHtml = t.items.map(renderItem).join('\n      ');

  return `<section class="ui-section ui-bg-page border-t border-brand-dark/10" data-motion-section>
    <div class="ui-container">
      <div class="mx-auto max-w-4xl text-center">
        <p class="leading-relaxed ui-type-accent-label !font-extrabold !tracking-[0.24em] !text-brand-primary">${t.eyebrow}</p>
        <h2 class="font-heading font-bold ui-type-heading-section-lg mt-5 !font-extrabold">${t.heading}</h2>
        <p class="leading-relaxed ui-type-lead mx-auto mt-5 max-w-2xl !font-semibold !leading-8">${t.description}</p>
      </div>
      <div class="relative mx-auto mt-14 max-w-5xl" data-timeline-root>
        <div class="absolute left-[14px] top-3 h-[calc(100%-2rem)] w-px bg-brand-dark/10 sm:left-1/2 sm:-translate-x-1/2" aria-hidden="true">
          <div class="timeline-line-fill absolute left-0 top-0 h-0 w-full bg-brand-accent transition-all duration-1000" data-timeline-line></div>
        </div>
        <div class="flex flex-col gap-16 sm:gap-24">
          ${itemsHtml}
        </div>
      </div>
    </div>
  </section>`;
}

describe('TimelineAlternateBlock, kontrakt renderowania', () => {
  it('renderuje <section> z ui-section, tone page i border-top', () => {
    const $ = cheerio.load(renderTimelineAlternateHtml());
    expect($('section').length).toBe(1);
    expect($('section').hasClass('ui-section')).toBe(true);
    expect($('section').hasClass('ui-bg-page')).toBe(true);
    expect($('section').hasClass('border-t')).toBe(true);
    expect($('section').hasClass('border-brand-dark/10')).toBe(true);
  });

  it('zawiera .ui-container', () => {
    const $ = cheerio.load(renderTimelineAlternateHtml());
    expect($('.ui-container').length).toBe(1);
  });

  describe('nagłówek', () => {
    it('renderuje eyebrow jako accent-label z tokenem brand-primary', () => {
      const $ = cheerio.load(renderTimelineAlternateHtml());
      const eyebrow = $('.ui-type-accent-label');
      expect(eyebrow.length).toBe(1);
      expect(eyebrow.text()).toBe(PL_DATA.eyebrow);
      expect(eyebrow.hasClass('!text-brand-primary')).toBe(true);
    });

    it('renderuje dokładnie jeden h2 z nagłówkiem', () => {
      const $ = cheerio.load(renderTimelineAlternateHtml());
      expect($('h2').length).toBe(1);
      expect($('h2').text()).toBe(PL_DATA.heading);
      expect($('h2').hasClass('ui-type-heading-section-lg')).toBe(true);
    });

    it('renderuje opis lead wycentrowany (mx-auto max-w-2xl)', () => {
      const $ = cheerio.load(renderTimelineAlternateHtml());
      const lead = $('.ui-type-lead');
      expect(lead.length).toBe(1);
      expect(lead.text()).toBe(PL_DATA.description);
      expect(lead.hasClass('mx-auto')).toBe(true);
      expect(lead.hasClass('max-w-2xl')).toBe(true);
    });
  });

  describe('struktura timeline', () => {
    it('renderuje dokładnie 4 .timeline-item z data-timeline-item', () => {
      const $ = cheerio.load(renderTimelineAlternateHtml());
      const items = $('.timeline-item');
      expect(items.length).toBe(4);
      expect($('[data-timeline-item]').length).toBe(4);
    });

    it('renderuje linię tła (bg-brand-dark/10) z wypełnieniem data-timeline-line', () => {
      const $ = cheerio.load(renderTimelineAlternateHtml());
      expect($('.w-px.bg-brand-dark\\/10').length).toBe(1);
      const line = $('[data-timeline-line]');
      expect(line.length).toBe(1);
      expect(line.hasClass('bg-brand-accent')).toBe(true);
      expect(line.hasClass('timeline-line-fill')).toBe(true);
      expect(line.hasClass('h-0')).toBe(true);
    });

    it('kropki: 4x data-timeline-dot z border-brand-accent i bg-white', () => {
      const $ = cheerio.load(renderTimelineAlternateHtml());
      const dots = $('[data-timeline-dot]');
      expect(dots.length).toBe(4);
      dots.each((_, el) => {
        expect($(el).hasClass('border-brand-accent')).toBe(true);
        expect($(el).hasClass('bg-white')).toBe(true);
        expect($(el).hasClass('timeline-dot')).toBe(true);
      });
    });

    it('kropki zawierają numery 01-04 w kolejności', () => {
      const $ = cheerio.load(renderTimelineAlternateHtml());
      $('[data-timeline-dot]').each((index, el) => {
        const expected = (index + 1).toString().padStart(2, '0');
        expect($(el).text()).toBe(expected);
      });
    });

    it('tytuły i opisy itemów pochodzą z JSON', () => {
      const $ = cheerio.load(renderTimelineAlternateHtml());
      const titles = $('h3').text();
      expect(titles).toContain(PL_DATA.items[0].title);
      expect(titles).toContain(PL_DATA.items[3].title);
      const descriptions = $('.ui-type-text-feature-sm').text();
      expect(descriptions).toContain(PL_DATA.items[0].description);
    });
  });

  describe('naprzemienność układu', () => {
    it('item 01 (index 0) ma tekst w lewej kolumnie (sm:text-right)', () => {
      const $ = cheerio.load(renderTimelineAlternateHtml());
      const item = $('[data-timeline-item]').eq(0);
      const leftCol = item.find('.sm\\:text-right');
      expect(leftCol.length).toBe(1);
      expect(leftCol.hasClass('hidden')).toBe(true);
      expect(leftCol.hasClass('sm:block')).toBe(true);
      expect(leftCol.text()).toContain(PL_DATA.items[0].title);
    });

    it('item 02 (index 1) ma tekst w prawej kolumnie (sm:pl-10), lewa jest pusta', () => {
      const $ = cheerio.load(renderTimelineAlternateHtml());
      const item = $('[data-timeline-item]').eq(1);
      const leftCol = item.find('.sm\\:text-right');
      expect(leftCol.length).toBe(1);
      expect(leftCol.hasClass('aria-hidden') === false).toBe(true);
      expect(leftCol.attr('aria-hidden')).toBe('true');
      expect(leftCol.text().trim()).toBe('');
      const rightCol = item.find('.sm\\:pl-10');
      expect(rightCol.length).toBe(1);
      expect(rightCol.text()).toContain(PL_DATA.items[1].title);
    });

    it('układ naprzemienny: 01, 03 z lewej; 02, 04 z prawej', () => {
      const $ = cheerio.load(renderTimelineAlternateHtml());
      [0, 2].forEach((index) => {
        const item = $('[data-timeline-item]').eq(index);
        expect(item.find('.sm\\:text-right').text()).toContain(PL_DATA.items[index].title);
        expect(item.find('.sm\\:pl-10').text().trim()).toBe('');
      });
      [1, 3].forEach((index) => {
        const item = $('[data-timeline-item]').eq(index);
        expect(item.find('.sm\\:text-right').attr('aria-hidden')).toBe('true');
        expect(item.find('.sm\\:pl-10').text()).toContain(PL_DATA.items[index].title);
      });
    });

    it('itemy z lewej mają duplikat treści dla mobile (sm:hidden)', () => {
      const $ = cheerio.load(renderTimelineAlternateHtml());
      const item = $('[data-timeline-item]').eq(0);
      const mobileCopy = item.find('.sm\\:hidden');
      expect(mobileCopy.length).toBe(1);
      expect(mobileCopy.text()).toContain(PL_DATA.items[0].title);
    });
  });

  describe('i18n (pl/en)', () => {
    it('EN renderuje angielski eyebrow, heading, opis i tytuły itemów', () => {
      const $ = cheerio.load(renderTimelineAlternateHtml('en'));
      expect($('.ui-type-accent-label').text()).toBe(EN_DATA.eyebrow);
      expect($('h2').text()).toBe(EN_DATA.heading);
      expect($('.ui-type-lead').text()).toBe(EN_DATA.description);
      expect($('h3').text()).toContain(EN_DATA.items[0].title);
    });

    it('liczba itemów jest taka sama w obu językach', () => {
      const $ = cheerio.load(renderTimelineAlternateHtml('en'));
      expect($('[data-timeline-item]').length).toBe(4);
    });
  });

  it('nie zawiera klienckich tokenów ani danych klienta', () => {
    const html = renderTimelineAlternateHtml();
    expect(html).not.toContain('bg-brand-cream');
    expect(html).not.toContain('border-outline');
    expect(html).not.toContain('bg-outline');
    expect(html).not.toContain('data-reveal');
    expect(html).not.toContain('on-surface-variant');
    expect(html).not.toContain('pożar');
    expect(html).not.toContain('Gasimy');
    expect(html).not.toContain('href="#"');
  });
});
