import { describe, it, expect } from 'vitest';
import * as cheerio from 'cheerio';

// Why: The contract test reflects the HTML structure generated by
// UspPremiumBlock, wariant sekcji USP ze statystykami,
// benefits cards and CTA) to detect regressions in rendering without
// running a full build. Pattern: about-law-contract.test.ts
// i hero-law-contract.test.ts.

interface Stat {
  value: string;
  label: string;
}

interface Benefit {
  icon: string;
  title: string;
  description: string;
}

interface UspPremiumData {
  id?: string;
  eyebrow?: string;
  heading?: string;
  description?: string;
  description2?: string;
  cta?: { label: string; href: string };
  stats?: Stat[];
  benefits?: Benefit[];
}

// Synthetic fixtures keep content assertions independent from template copy.
const PL_DATA: UspPremiumData = {
  id: 'usp',
  eyebrow: 'Sample section label',
  heading: 'Sample section heading',
  description: 'Example supporting copy for the section.',
  description2: 'Additional example copy for layout checks.',
  cta: { label: 'Sample call to action', href: '/sample-page/' },
  stats: [
    { value: 'A', label: 'Sample metric label one' },
    { value: 'B', label: 'Sample metric label two' },
    { value: 'C', label: 'Sample metric label three' },
  ],
  benefits: [
    { icon: 'magnifying-glass', title: 'Sample benefit one', description: 'Example description for the first benefit.' },
    { icon: 'path', title: 'Sample benefit two', description: 'Example description for the second benefit.' },
    { icon: 'users', title: 'Sample benefit three', description: 'Example description for the third benefit.' },
    { icon: 'chart-bar', title: 'Sample benefit four', description: 'Example description for the fourth benefit.' },
  ],
};

const EN_DATA: UspPremiumData = {
  eyebrow: 'Example English label',
  heading: 'Example English heading',
  description: 'Example English supporting copy.',
  cta: { label: 'Example English action', href: '/sample-page/' },
  stats: [
    { value: 'A', label: 'Example English metric' },
    { value: 'B', label: 'Another English metric' },
  ],
  benefits: [
    { icon: 'magnifying-glass', title: 'Example English benefit', description: 'Example English benefit description.' },
  ],
};

// Why: approximate copy of atom classes (Heading, Text, Button, Icon),
// because the test checks the structural contract, not the full list of Tailwind classes.
// Full class compatibility is verified by the Astro build.
const SECTION_CLASS = 'ui-section ui-bg-page relative';
const BUTTON_BASE_CLASS =
  'ui-button ui-type-cta-label group inline-flex items-center justify-center gap-1.5 rounded-md whitespace-nowrap transition-all font-semibold focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-brand-primary/50 ui-button-primary h-10 sm:h-11 px-4 sm:px-5 text-sm sm:text-base [&_svg]:size-4.5';

function renderStats(stats: Stat[]): string {
  if (!stats.length) return '';
  const items = stats
    .map((stat, i) => `
      <div class="relative text-center">
        ${i > 0 ? '<div class="absolute inset-y-0 left-0 hidden w-px bg-gradient-to-b from-transparent via-brand-dark/10 to-transparent md:block"></div>' : ''}
        <p class="font-heading font-bold ui-type-heading-section-xl text-brand-primary">${stat.value}</p>
        <p class="leading-relaxed ui-type-body mt-1 text-xs font-medium uppercase tracking-wide text-brand-dark/70 md:mt-2 md:text-sm">${stat.label}</p>
      </div>`)
    .join('');
  return `<div class="mb-16 grid grid-cols-3 gap-4 md:mb-20 md:gap-8">${items}</div>`;
}

function renderBenefits(benefits: Benefit[]): string {
  if (!benefits.length) return '';
  const items = benefits
    .map((item) => `
      <article class="group relative overflow-hidden rounded-2xl border border-brand-primary/10 bg-white p-6 shadow-[0_4px_20px_-4px_rgba(0,0,0,0.06)] transition-all duration-300 hover:-translate-y-1 hover:border-brand-primary/25 hover:shadow-[0_12px_32px_-8px_rgba(0,0,0,0.1)]">
        <div class="pointer-events-none absolute inset-0 opacity-0 transition-opacity duration-300 group-hover:opacity-100" style="background: radial-gradient(ellipse 80% 60% at 50% 0%, color-mix(in oklab, var(--color-brand-primary) 8%, transparent) 0%, transparent 70%)"></div>
        <div class="relative flex flex-col items-center text-center sm:items-start sm:text-left">
          <div class="mb-4 flex size-12 items-center justify-center rounded-xl bg-brand-primary/10 text-brand-primary">
            <i class="ph ph-${item.icon} text-xl"></i>
          </div>
          <h3 class="font-heading font-bold ui-type-feature-title mb-2 leading-snug tracking-tight text-brand-dark">${item.title}</h3>
          <p class="leading-relaxed ui-type-text-feature-sm text-brand-dark/70">${item.description}</p>
        </div>
      </article>`)
    .join('');
  return `<div class="flex-1"><div class="grid grid-cols-1 gap-5 sm:grid-cols-2">${items}</div></div>`;
}

// Dlaczego: ta sama logika co formatInternalLink z @utils/url (trailing slash
// for internal links) so that the tested HTML renders faithfully
// block where Button passes through this helper.
function formatHref(href: string): string {
  if (/^(http|mailto:|tel:|javascript:)/.test(href)) return href;
  if (href.startsWith('#')) return href;
  const [base, ...rest] = href.split(/([#?])/);
  const suffix = rest.join('');
  let formattedBase = base.replace(/\/+/g, '/');
  if (!formattedBase.startsWith('/')) formattedBase = '/' + formattedBase;
  if (!formattedBase.endsWith('/')) formattedBase = formattedBase + '/';
  if (formattedBase === '//') formattedBase = '/';
  return formattedBase + suffix;
}

function renderCta(cta: { label: string; href: string } | undefined): string {
  if (!cta?.href) return '';
  return `<div class="mt-8"><a href="${formatHref(cta.href)}" class="${BUTTON_BASE_CLASS}"><span>${cta.label}</span></a></div>`;
}

function renderUspPremiumHtml(data: UspPremiumData): string {
  const { id = 'usp' } = data;
  return `<section id="${id}" class="${SECTION_CLASS}">
    <div class="ui-container">
      ${renderStats(data.stats ?? [])}
      <div class="flex flex-col gap-12 lg:flex-row lg:items-center lg:gap-16 xl:gap-20">
        <div class="flex max-w-lg flex-col items-center text-center lg:items-start lg:text-left">
          ${data.eyebrow ? `<p class="leading-relaxed ui-type-accent-label mb-4">${data.eyebrow}</p>` : ''}
          ${data.heading ? `<h2 class="font-heading font-bold ui-type-heading-section-lg text-balance">${data.heading}</h2>` : ''}
          ${data.description ? `<p class="leading-relaxed ui-type-lead mt-5 text-pretty">${data.description}</p>` : ''}
          ${data.description2 ? `<p class="leading-relaxed ui-type-lead mt-3 text-pretty">${data.description2}</p>` : ''}
          ${renderCta(data.cta)}
        </div>
        ${renderBenefits(data.benefits ?? [])}
      </div>
    </div>
  </section>`;
}

describe('UspPremiumBlock, kontrakt renderowania', () => {
  it('renderuje <section> z ui-section, tone page, relative i id', () => {
    const $ = cheerio.load(renderUspPremiumHtml(PL_DATA));
    expect($('section').length).toBe(1);
    expect($('section').hasClass('ui-section')).toBe(true);
    expect($('section').hasClass('ui-bg-page')).toBe(true);
    expect($('section').hasClass('relative')).toBe(true);
    expect($('section').attr('id')).toBe('usp');
  });

  it('zawiera .ui-container', () => {
    const $ = cheerio.load(renderUspPremiumHtml(PL_DATA));
    expect($('.ui-container').length).toBe(1);
  });

  describe('statystyki', () => {
    it('renderuje co najmniej 3 statystyki w gridzie 3-kolumnowym', () => {
      const $ = cheerio.load(renderUspPremiumHtml(PL_DATA));
      const grid = $('.grid-cols-3');
      expect(grid.length).toBe(1);
      expect(grid.hasClass('grid')).toBe(true);
      expect(grid.hasClass('grid-cols-3')).toBe(true);
      expect(grid.hasClass('mb-16')).toBe(true);
      expect(grid.hasClass('md:mb-20')).toBe(true);
      expect(grid.hasClass('md:gap-8')).toBe(true);
      expect($('.grid-cols-3 > div.relative').length).toBe(PL_DATA.stats?.length);
    });

    it('wartości statystyk używają tokena text-brand-primary', () => {
      const $ = cheerio.load(renderUspPremiumHtml(PL_DATA));
      const values = $('.ui-type-heading-section-xl');
      expect(values.length).toBe(PL_DATA.stats?.length);
      expect(values.first().text()).toBe(PL_DATA.stats?.[0].value);
      values.each((_, el) => {
        expect($(el).hasClass('text-brand-primary')).toBe(true);
      });
    });

    it('etykiety statystyk używają text-brand-dark/70 i uppercase', () => {
      const $ = cheerio.load(renderUspPremiumHtml(PL_DATA));
      $('.grid-cols-3 > div.relative p:last-child').each((_, el) => {
        expect($(el).hasClass('text-brand-dark/70')).toBe(true);
        expect($(el).hasClass('uppercase')).toBe(true);
        expect($(el).hasClass('tracking-wide')).toBe(true);
      });
      expect($('.grid-cols-3 > div.relative p:last-child').first().text()).toBe(PL_DATA.stats?.[0].label);
    });

    it('renderuje separator pionowy między statystykami, ale nie przed pierwszą', () => {
      const $ = cheerio.load(renderUspPremiumHtml(PL_DATA));
      const separators = $('.grid-cols-3 .absolute');
      expect(separators.length).toBe(2);
      expect(separators.eq(0).hasClass('via-brand-dark/10')).toBe(true);
      const firstStat = $('.grid-cols-3 > div.relative').first();
      expect(firstStat.find('.absolute').length).toBe(0);
    });

    it('przy jednej statystyce nie renderuje separatorów', () => {
      const single = { ...PL_DATA, stats: [{ value: '100%', label: 'Jedna' }] };
      const $ = cheerio.load(renderUspPremiumHtml(single));
      expect($('.grid-cols-3 .absolute').length).toBe(0);
    });
  });

  describe('nagłówek i opis', () => {
    it('renderuje dokładnie jeden h2 z nagłówkiem sekcji', () => {
      const $ = cheerio.load(renderUspPremiumHtml(PL_DATA));
      expect($('h2').length).toBe(1);
      expect($('h2').hasClass('ui-type-heading-section-lg')).toBe(true);
      expect($('h2').hasClass('text-balance')).toBe(true);
      expect($('h2').text()).toBe(PL_DATA.heading);
    });

    it('renderuje etykietę akcentową (eyebrow) nad nagłówkiem', () => {
      const $ = cheerio.load(renderUspPremiumHtml(PL_DATA));
      const label = $('.ui-type-accent-label');
      expect(label.length).toBe(1);
      expect(label.hasClass('mb-4')).toBe(true);
      expect(label.text()).toBe(PL_DATA.eyebrow);
    });

    it('renderuje dwa opisy jako ui-type-lead z text-pretty', () => {
      const $ = cheerio.load(renderUspPremiumHtml(PL_DATA));
      const leads = $('.ui-type-lead');
      expect(leads.length).toBe(2);
      expect(leads.eq(0).hasClass('text-pretty')).toBe(true);
      expect(leads.eq(0).hasClass('mt-5')).toBe(true);
      expect(leads.eq(1).hasClass('text-pretty')).toBe(true);
      expect(leads.eq(1).hasClass('mt-3')).toBe(true);
    });
  });

  describe('przycisk CTA', () => {
    it('renderuje dokładnie jeden a.ui-button wariantu primary', () => {
      const $ = cheerio.load(renderUspPremiumHtml(PL_DATA));
      const button = $('a.ui-button');
      expect(button.length).toBe(1);
      expect(button.hasClass('ui-button-primary')).toBe(true);
      expect(button.text()).toBe(PL_DATA.cta?.label);
    });

    it('link wewnętrzny ma trailing slash (formatInternalLink)', () => {
      const $ = cheerio.load(renderUspPremiumHtml(PL_DATA));
      expect($('a.ui-button').attr('href')).toBe('/sample-page/');
    });

    it('href bez slasha zostaje uzupełniony o trailing slash', () => {
      const noSlash = { ...PL_DATA, cta: { label: 'Example', href: '/sample-page' } };
      const $ = cheerio.load(renderUspPremiumHtml(noSlash));
      expect($('a.ui-button').attr('href')).toBe('/sample-page/');
    });

    it('bez cta nie renderuje przycisku', () => {
      const withoutCta = { ...PL_DATA, cta: undefined };
      const $ = cheerio.load(renderUspPremiumHtml(withoutCta));
      expect($('a.ui-button').length).toBe(0);
    });
  });

  describe('karty benefitów', () => {
    it('renderuje co najmniej 4 karty w gridzie mobile-first', () => {
      const $ = cheerio.load(renderUspPremiumHtml(PL_DATA));
      const cards = $('article');
      expect(cards.length).toBe(PL_DATA.benefits?.length);
      const grid = $('.sm\\:grid-cols-2');
      expect(grid.length).toBe(1);
      expect(grid.hasClass('grid-cols-1')).toBe(true);
    });

    it('karta ma białe tło, brandową ramkę i hover uniesienia', () => {
      const $ = cheerio.load(renderUspPremiumHtml(PL_DATA));
      const card = $('article').first();
      expect(card.hasClass('bg-white')).toBe(true);
      expect(card.hasClass('border-brand-primary/10')).toBe(true);
      expect(card.hasClass('rounded-2xl')).toBe(true);
      expect(card.hasClass('hover:-translate-y-1')).toBe(true);
      expect(card.hasClass('hover:border-brand-primary/25')).toBe(true);
    });

    it('karta ma overlay z brandową poświatą (bez klienckich CSS var)', () => {
      const $ = cheerio.load(renderUspPremiumHtml(PL_DATA));
      const overlay = $('article .pointer-events-none').first();
      expect(overlay.hasClass('opacity-0')).toBe(true);
      expect(overlay.hasClass('group-hover:opacity-100')).toBe(true);
      expect(overlay.attr('style')).toContain('var(--color-brand-primary)');
      expect(overlay.attr('style')).not.toContain('--color-accent-primary');
    });

    it('ikonki renderują się jako ph ph-<nazwa> w boxie brandowym', () => {
      const $ = cheerio.load(renderUspPremiumHtml(PL_DATA));
      const icons = $('article i.ph');
      expect(icons.length).toBe(PL_DATA.benefits?.length);
      expect(icons.eq(0).hasClass('ph-magnifying-glass')).toBe(true);
      expect(icons.eq(1).hasClass('ph-path')).toBe(true);
      expect(icons.eq(2).hasClass('ph-users')).toBe(true);
      expect(icons.eq(3).hasClass('ph-chart-bar')).toBe(true);
      const box = icons.eq(0).parent();
      expect(box.hasClass('bg-brand-primary/10')).toBe(true);
      expect(box.hasClass('text-brand-primary')).toBe(true);
      expect(box.hasClass('size-12')).toBe(true);
      expect(box.hasClass('rounded-xl')).toBe(true);
    });

    it('tytuł karty to h3 z ui-type-feature-title i text-brand-dark', () => {
      const $ = cheerio.load(renderUspPremiumHtml(PL_DATA));
      const titles = $('article h3');
      expect(titles.length).toBe(PL_DATA.benefits?.length);
      titles.each((_, el) => {
        expect($(el).hasClass('ui-type-feature-title')).toBe(true);
        expect($(el).hasClass('text-brand-dark')).toBe(true);
      });
      expect(titles.first().text()).toBe(PL_DATA.benefits?.[0].title);
    });

    it('opis karty używa text-brand-dark/70 zamiast klienckiego text-on-surface-variant', () => {
      const $ = cheerio.load(renderUspPremiumHtml(PL_DATA));
      $('article p').each((_, el) => {
        expect($(el).hasClass('text-brand-dark/70')).toBe(true);
        expect($(el).hasClass('ui-type-text-feature-sm')).toBe(true);
      });
    });
  });

  describe('i18n (pl/en)', () => {
    it('EN renderuje angielskie nagłówki, statystyki i benefity', () => {
      const $ = cheerio.load(renderUspPremiumHtml(EN_DATA));
      expect($('h2').text()).toBe(EN_DATA.heading);
      expect($('.ui-type-accent-label').text()).toBe(EN_DATA.eyebrow);
      expect($('.ui-type-heading-section-xl').length).toBe(2);
      expect($('article').length).toBe(1);
      expect($('a.ui-button').text()).toBe(EN_DATA.cta?.label);
      expect($('a.ui-button').attr('href')).toBe('/sample-page/');
    });
  });

  describe('elastyczność danych', () => {
    it('bez benefitów nie renderuje gridu kart', () => {
      const noBenefits = { ...PL_DATA, benefits: [] };
      const $ = cheerio.load(renderUspPremiumHtml(noBenefits));
      expect($('article').length).toBe(0);
      expect($('.sm\\:grid-cols-2').length).toBe(0);
    });

    it('bez statystyk nie renderuje paska statystyk', () => {
      const noStats = { ...PL_DATA, stats: [] };
      const $ = cheerio.load(renderUspPremiumHtml(noStats));
      expect($('.grid-cols-3').length).toBe(0);
    });
  });

  it('nie zawiera danych projektu ani niestandardowych tokenów CSS', () => {
    const html = renderUspPremiumHtml(PL_DATA);
    expect(html).not.toContain('client-specific');
    expect(html).not.toContain('text-on-surface');
    expect(html).not.toContain('bg-surface');
    expect(html).not.toContain('--color-text-primary');
    expect(html).not.toContain('20+');
    expect(html).not.toContain('50+');
    expect(html).not.toContain('30%');
  });

  it('nie zawiera klienckiego systemu reveal ani href="#"', () => {
    const html = renderUspPremiumHtml(PL_DATA);
    expect(html).not.toContain('reveal');
    expect(html).not.toContain('data-reveal');
    expect(html).not.toContain('href="#"');
  });
});
